//! Binary-only placement for a complete source run with one target-only insertion.
//! Exact helper bodies alone do not identify their emitter. The two foreign
//! seams and a shared class-vtable relocation relationship provide that proof.

use super::*;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RelocationLinkedRun {
    pub unit: String,
    pub section: String,
    pub start: String,
    pub end: String,
    pub inserted: String,
    pub source_vtable: String,
    pub target_vtable: String,
    pub vtable_section: String,
    pub source_destructor: String,
    pub first_attribution_id: String,
    pub left_attribution_id: String,
    pub right_attribution_id: String,
}

impl ObservationIndex {
    pub(super) fn derive_relocation_linked_runs(&self) -> Vec<RelocationLinkedRun> {
        if self.report.schema < 22 {
            return Vec::new();
        }
        let mut result = Vec::new();
        for unit in &self.report.units {
            if unit.autogenerated {
                continue;
            }
            let source: Vec<_> = self
                .report
                .source_functions
                .iter()
                .filter(|function| {
                    function.unit == unit.unit
                        && function.module == EXECUTABLE_MODULE
                        && function.section == ".text"
                })
                .collect();
            if !(3..=8).contains(&source.len())
                || source.iter().any(|function| !function.extent_known)
                || source.windows(2).any(|pair| pair[0].end != pair[1].address)
            {
                continue;
            }
            let Some(first_attribution) = self.attribution_for_source(source[0]) else {
                continue;
            };
            if !self.ownership_independent(first_attribution)
                || !self.attribution_extents_known(first_attribution)
                || first_attribution.ambiguous
            {
                continue;
            }
            let all_source = &self.report.source_functions;
            let Some(source_index) = all_source.iter().position(|function| {
                function.module == EXECUTABLE_MODULE
                    && function.section == ".text"
                    && function.address == source[0].address
            }) else {
                continue;
            };
            let (Some(left_source), Some(right_source)) = (
                source_index.checked_sub(1).and_then(|index| all_source.get(index)),
                all_source.get(source_index + source.len()),
            ) else {
                continue;
            };
            if left_source.unit == unit.unit
                || right_source.unit == unit.unit
                || left_source.end != source[0].address
                || source.last().is_none_or(|item| item.end != right_source.address)
            {
                continue;
            }
            let (Some(left_attr), Some(right_attr)) = (
                self.attribution_for_source(left_source),
                self.attribution_for_source(right_source),
            ) else {
                continue;
            };
            if left_attr.ambiguous
                || !left_attr.binary_supported
                || !self.ownership_independent(right_attr)
                || !self.attribution_extents_known(left_attr)
                || !self.attribution_extents_known(right_attr)
                || left_attr.current_target_owner.as_deref() != Some(left_source.unit.as_str())
                || right_attr.current_target_owner.as_deref() != Some(right_source.unit.as_str())
            {
                continue;
            }
            let target = self.section_functions(EXECUTABLE_MODULE, ".text");
            let Some(start_index) = target
                .iter()
                .position(|function| function.address == first_attribution.target.address)
            else {
                continue;
            };
            let (Some(left_target), Some(right_target)) = (
                start_index.checked_sub(1).and_then(|index| target.get(index)),
                target.get(start_index + source.len() + 1),
            ) else {
                continue;
            };
            let inside = &target[start_index..start_index + source.len() + 1];
            if left_target.address != left_attr.target.address
                || right_target.address != right_attr.target.address
                || left_target.owner_autogenerated
                || right_target.owner_autogenerated
                || left_target.end != inside[0].address
                || inside.last().is_none_or(|item| item.end != right_target.address)
                || inside.iter().any(|function| {
                    !function.extent_known
                        || function.owner_autogenerated
                        || function.current_owner.as_deref().is_some_and(|owner| owner != unit.unit)
                })
                || inside.windows(2).any(|pair| pair[0].end != pair[1].address)
            {
                continue;
            }
            let mut possible = Vec::new();
            for skip in 1..inside.len() - 1 {
                let inserted = &inside[skip];
                if self
                    .at_target(EXECUTABLE_MODULE, ".text", parse_hex(&inserted.address))
                    .is_some()
                    || inserted.current_owner.is_some()
                {
                    continue;
                }
                let pairs: Vec<_> = source
                    .iter()
                    .enumerate()
                    .map(|(index, item)| (*item, &inside[index + usize::from(index >= skip)]))
                    .collect();
                if !pairs.iter().all(|(source, target)| {
                    if let Some(attr) =
                        self.at_target(EXECUTABLE_MODULE, ".text", parse_hex(&target.address))
                    {
                        attr.source.unit == unit.unit
                            && attr.source.address == source.address
                            && !attr.ambiguous
                            && self.attribution_extents_known(attr)
                    } else {
                        self.attribution_for_source(source).is_none()
                            && source.normalized_body_sha256.is_some()
                            && source.normalized_body_sha256 == target.normalized_body_sha256
                    }
                }) {
                    continue;
                }
                let contextual = pairs
                    .iter()
                    .filter(|(source, target)| {
                        self.attribution_for_source(source).is_none()
                            && source.normalized_body_sha256 == target.normalized_body_sha256
                    })
                    .count();
                if contextual < 2 {
                    continue;
                }
                if inserted.callers.len() != 1
                    || !pairs.iter().any(|(_, caller)| {
                        caller.address == inserted.callers[0].address
                            && caller.section == inserted.callers[0].section
                    })
                {
                    continue;
                }
                let Some(inserted_refs) = self.target_references(inserted) else {
                    continue;
                };
                if !inserted_refs.references.iter().any(|reference| {
                    reference.kind == "PpcRel24"
                        && reference.target_section.as_deref() == Some(".text")
                        && pairs.iter().any(|(_, later)| {
                            parse_hex(&later.address) > parse_hex(&inserted.address)
                                && reference.target_address == u64::from(parse_hex(&later.address))
                        })
                }) {
                    continue;
                }
                for (destructor, target_destructor) in
                    pairs.iter().copied().filter(|(source, _)| {
                        source.name.starts_with("__dt__") && source.normalized_body_sha256.is_some()
                    })
                {
                    let (Some(source_refs), Some(target_refs)) = (
                        self.source_references(destructor),
                        self.target_references(target_destructor),
                    ) else {
                        continue;
                    };
                    for reference in source_refs.references.iter().filter(|reference| {
                        reference.kind == "PpcAddr16Ha"
                            && reference.target.starts_with("__vt__")
                            && reference.target_section.as_deref() == Some(".data")
                            && destructor.name.starts_with(&format!(
                                "__dt__{}F",
                                reference.target.trim_start_matches("__vt__")
                            ))
                    }) {
                        let source_sites =
                            address_sites(&source_refs.references, reference.target_address);
                        if !has_ha_lo(&source_sites) {
                            continue;
                        }
                        for target_vtable in target_refs.references.iter().filter(|candidate| {
                            candidate.kind == "PpcAddr16Ha"
                                && candidate.target_section.as_deref() == Some(".data")
                        }) {
                            let target_sites = address_sites(
                                &target_refs.references,
                                target_vtable.target_address,
                            );
                            if source_sites != target_sites {
                                continue;
                            }
                            let corroborates = pairs.iter().any(|(other_source, other_target)| {
                                other_source.address != destructor.address
                                    && self.source_references(other_source).is_some_and(|raw| {
                                        let sites = address_sites(
                                            &raw.references,
                                            reference.target_address,
                                        );
                                        has_ha_lo(&sites)
                                            && self.target_references(other_target).is_some_and(
                                                |target_raw| {
                                                    sites
                                                        == address_sites(
                                                            &target_raw.references,
                                                            target_vtable.target_address,
                                                        )
                                                },
                                            )
                                    })
                            });
                            if corroborates
                                && let (Ok(source_vtable), Ok(target_vtable)) = (
                                    u32::try_from(reference.target_address),
                                    u32::try_from(target_vtable.target_address),
                                )
                            {
                                possible.push(RelocationLinkedRun {
                                    unit: unit.unit.clone(),
                                    section: ".text".into(),
                                    start: inside[0].address.clone(),
                                    end: right_target.address.clone(),
                                    inserted: inserted.address.clone(),
                                    source_vtable: hex(source_vtable),
                                    target_vtable: hex(target_vtable),
                                    vtable_section: ".data".into(),
                                    source_destructor: destructor.address.clone(),
                                    first_attribution_id: first_attribution.id.clone(),
                                    left_attribution_id: left_attr.id.clone(),
                                    right_attribution_id: right_attr.id.clone(),
                                });
                            }
                        }
                    }
                }
            }
            // A shared helper pattern may fit several skips or data addresses.
            // Only one complete interpretation can move ownership.
            possible.sort_by(|a, b| {
                (&a.inserted, &a.source_vtable, &a.target_vtable).cmp(&(
                    &b.inserted,
                    &b.source_vtable,
                    &b.target_vtable,
                ))
            });
            possible.dedup();
            if let [only] = possible.as_slice() {
                result.push(only.clone());
            }
        }
        result
    }

    fn attribution_for_source(
        &self,
        source: &SourceFunctionObservation,
    ) -> Option<&FunctionAttribution> {
        self.report.attributions.iter().find(|item| {
            item.source.unit == source.unit
                && item.source.module == source.module
                && item.source.section == source.section
                && item.source.address == source.address
                && item.source.end == source.end
        })
    }

    fn source_references(
        &self,
        source: &SourceFunctionObservation,
    ) -> Option<&TargetFunctionReferences> {
        self.report.unmatched_source_references.iter().find(|raw| {
            raw.section == source.section && raw.address == source.address && raw.end == source.end
        })
    }

    fn target_references(
        &self,
        target: &TargetFunctionObservation,
    ) -> Option<&TargetFunctionReferences> {
        self.report.unattributed_references.iter().find(|raw| {
            raw.section == target.section && raw.address == target.address && raw.end == target.end
        })
    }
}

fn address_sites(
    references: &[object_evidence::CompiledReference],
    address: u64,
) -> BTreeSet<(u32, String)> {
    references
        .iter()
        .filter(|reference| {
            reference.target_section.as_deref() == Some(".data")
                && reference.target_address == address
                && matches!(reference.kind.as_str(), "PpcAddr16Ha" | "PpcAddr16Lo")
        })
        .map(|reference| (reference.offset, reference.kind.clone()))
        .collect()
}

fn has_ha_lo(sites: &BTreeSet<(u32, String)>) -> bool {
    sites.len() == 2
        && sites.iter().any(|(_, kind)| kind == "PpcAddr16Ha")
        && sites.iter().any(|(_, kind)| kind == "PpcAddr16Lo")
}
