#!/usr/bin/env python3
"""Enable whole source files only after their compiled objects pass the retail hash.

Run from a dtk-template project after discovering splits. A generated block in
configure.py records accepted files. Trials are transactional; failures are bisected
and left disabled. No source code or hand-picked target addresses are changed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import split_confidence_loop as scl
from discover_splits import by_path, code_bytes

BEGIN = "# BEGIN AUTOMATED SOURCE VERIFICATION\n"
END = "# END AUTOMATED SOURCE VERIFICATION\n"


def render_config(original, version, names):
    """Keep project configuration intact; add a version-specific generated override."""
    original = original.replace("\r\n", "\n")
    marker = f"{BEGIN}# Version: {version}\n"
    text = re.sub(re.escape(marker) + r".*?" + re.escape(END) + r"\n?", "", original, flags=re.S)
    anchor = 'if args.mode == "configure":'
    if text.count(anchor) != 1:
        raise ValueError("Expected one configure-mode dispatch in configure.py")
    if not names:
        return text
    block = marker + "# Generated by verify_source_units.py after linking these compiled objects and checking retail.\n"
    block += f"if config.version == {version!r}:\n"
    block += "    _verified_source_units = {\n"
    block += "".join(f"        {name!r},\n" for name in sorted(names))
    block += "    }\n"
    block += '    for _verified_lib in config.libs:\n        for _verified_obj in _verified_lib["objects"]:\n'
    block += "            if _verified_obj.name in _verified_source_units:\n                _verified_obj.completed = True\n"
    block += END + "\n"
    return text.replace(anchor, block + anchor)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", required=True)
    parser.add_argument("--dtk", type=Path, required=True)
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()
    if args.limit is not None and args.limit < 1:
        parser.error("--limit must be positive")
    args.dtk = args.dtk.resolve()
    out = Path("build") / args.target / "source-verification"
    out.mkdir(parents=True, exist_ok=True)
    config_path = Path("configure.py")
    original = config_path.read_bytes()
    original_text = original.decode("utf-8").replace("\r\n", "\n")
    # Existing generated overrides stay in the original template; accepted names
    # are recovered from report metadata and need not be retried.
    accepted = set()
    events = []
    log = (out / "build.log").open("w", encoding="utf-8")

    def run(cmd, capture=False):
        log.write("+ " + " ".join(map(str, cmd)) + "\n")
        log.flush()
        if capture:
            p = subprocess.run(list(map(str, cmd)), check=True, capture_output=True, text=True)
            log.write(p.stdout + p.stderr)
            return p.stdout
        subprocess.run(list(map(str, cmd)), check=True, stdout=log, stderr=log)

    def write(names):
        config_path.write_text(render_config(original_text, args.target, names), encoding="utf-8")

    def build(names):
        run([sys.executable, "configure.py", "configure", "-v", args.target, "--dtk", args.dtk])
        run(["ninja", f"build/{args.target}/ok", f"build/{args.target}/report.json"])
        report = scl.load_report(args.target)
        units = by_path(report)
        # Check the actual linker dependency graph, not merely the completion flag.
        inputs = run(["ninja", "-t", "inputs", f"build/{args.target}/main.elf"], capture=True)
        inputs = {p.replace("\\", "/") for p in inputs.splitlines()}
        objdiff = json.loads(Path("objdiff.json").read_text(encoding="utf-8"))
        comparison_units = {scl.strip_source_root(u.get("metadata", {}).get("source_path", "")): u
                            for u in objdiff["units"]}
        for name in names:
            if units.get(name, {}).get("metadata", {}).get("complete") is not True:
                raise RuntimeError(f"{name} was not configured to link from source")
            obj_path = comparison_units.get(name, {}).get("base_path", "").replace("\\", "/")
            if not obj_path or obj_path not in inputs:
                raise RuntimeError(f"{name}'s compiled object is not an input to main.elf")
        retail = Path("orig") / args.target / "sys" / "main.dol"
        built = Path("build") / args.target / "main.dol"
        if retail.read_bytes() != built.read_bytes():
            raise RuntimeError("Retail DOL bytes differ despite a passing ninja checksum target")
        return report

    baseline = build(set())
    units = by_path(baseline)
    # Recover this script's previous accepted names, preserving them across reruns.
    marker = f"{BEGIN}# Version: {args.target}\n"
    if marker in original_text:
        body = original_text.split(marker, 1)[1].split(END, 1)[0]
        import ast
        tree = ast.parse(body)
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "_verified_source_units" for t in node.targets):
                accepted.update(ast.literal_eval(node.value))
    candidates = [name for name, u in units.items()
                  if not u.get("metadata", {}).get("complete") and code_bytes(u) > 0
                  and u.get("sections")
                  and all(s.get("fuzzy_match_percent", 0) == 100 for s in u["sections"])]
    candidates.sort(key=lambda n: -code_bytes(units[n]))
    if args.limit:
        candidates = candidates[:args.limit]
    print(f"Testing {len(candidates)} whole files as compiled link inputs", flush=True)

    def trial(names):
        if not names:
            return
        write(accepted | set(names))
        try:
            build(accepted | set(names))
        except subprocess.CalledProcessError:
            write(accepted)
            if len(names) > 1:
                mid = len(names) // 2
                trial(names[:mid])
                trial(names[mid:])
            else:
                events.append({"unit": names[0], "status": "failed-source-link-or-hash"})
                print(f"  deferred: {names[0]}", flush=True)
            return
        accepted.update(names)
        events.extend({"unit": n, "status": "retail-hash-verified-source"} for n in names)
        for n in names:
            print(f"  verified source: {n}", flush=True)

    try:
        trial(candidates)
        write(accepted)
        final = build(accepted)
        result = {"target": args.target, "baseline": baseline["measures"], "final": final["measures"],
                  "accepted": sorted(accepted), "events": events,
                  "dtk_sha256": hashlib.sha256(args.dtk.read_bytes()).hexdigest(),
                  "dol_sha1": hashlib.sha1((Path("build") / args.target / "main.dol").read_bytes()).hexdigest()}
        (out / "result.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
        print(json.dumps(final["measures"], indent=2))
    except BaseException:
        config_path.write_bytes(original)
        build(set())
        raise
    finally:
        log.close()


if __name__ == "__main__":
    main()
