//! A shared helper is placed only when *every* compiled copy has an
//! independently anchored, different retail occurrence.

use std::collections::BTreeSet;

use dtk_migrate::analysis::{
    matching::{MatchMethod, MatchTier},
    object_evidence::{
        BuildFreshness, CompiledDefinition, CompiledFunction, CompiledReference, ConfiguredObject,
        ObjectEvidence, ObjectRecord, ObjectStatus, ScanStatus, TargetFunctionReferences,
        emitted_owner_resolutions, order_matches, relocation_placements,
    },
    ownership::{
        AttributionOrigin, FunctionAttribution, FunctionLocation, IdentificationReport,
        ObservationIndex, SourceFunction, SourceFunctionObservation, TargetFunctionObservation,
        UnitIdentification, load_reference,
    },
};
use sha2::{Digest, Sha256};

fn function(name: &str, start: &str, end: &str, hash: char, weak: bool) -> CompiledFunction {
    CompiledFunction {
        name: name.into(),
        section: ".text".into(),
        address: start.into(),
        end: end.into(),
        normalized_body_sha256: Some(hash.to_string().repeat(64)),
        weak,
        references: Vec::new(),
    }
}

fn target(name: &str, start: &str, end: &str, hash: char) -> TargetFunctionObservation {
    TargetFunctionObservation {
        name: name.into(),
        module: "main".into(),
        section: ".text".into(),
        address: start.into(),
        end: end.into(),
        extent_known: true,
        current_owner: None,
        owner_autogenerated: false,
        callers: Vec::new(),
        normalized_body_sha256: Some(hash.to_string().repeat(64)),
        weak: name == "helper",
    }
}

fn anchor(unit: &str, name: &str, start: &str, end: &str) -> FunctionAttribution {
    FunctionAttribution {
        id: format!("{unit}:{name}"),
        target: FunctionLocation {
            module: "main".into(),
            section: ".text".into(),
            address: start.into(),
            end: end.into(),
        },
        source: SourceFunction {
            name: name.into(),
            unit: unit.into(),
            module: "main".into(),
            section: ".text".into(),
            address: start.into(),
            end: end.into(),
        },
        method: MatchMethod::ExactHash,
        tier: MatchTier::Confident,
        confidence: 1.0,
        evidence_count: 1,
        origin: AttributionOrigin::NormalizedBody,
        distinctive_body: true,
        unique_exact_body: true,
        binary_supported: true,
        independent: true,
        ambiguous: false,
        competing: None,
        source_weak: false,
        target_weak: false,
        template_instantiation: false,
        current_target_owner: None,
        evidence: Vec::new(),
    }
}

fn fixture() -> (
    ObjectEvidence,
    BTreeSet<String>,
    Vec<SourceFunctionObservation>,
    Vec<TargetFunctionObservation>,
    Vec<FunctionAttribution>,
) {
    let units = BTreeSet::from(["A.cpp".into(), "B.cpp".into()]);
    let mut objects = Vec::new();
    let mut definitions = Vec::new();
    let mut targets = Vec::new();
    let mut attributions = Vec::new();
    let mut target_references = Vec::new();
    for (unit, prefix, object_hash, target_start, left_hash, right_hash) in
        [("A.cpp", "A", 'b', 0x1000, '1', '2'), ("B.cpp", "B", 'c', 0x2000, '3', '4')]
    {
        let address = |offset: u32| format!("0x{:08X}", target_start + offset);
        let left = format!("{prefix}_left");
        let right = format!("{prefix}_right");
        let object_hash = object_hash.to_string().repeat(64);
        let flags = "-inline deferred".to_string();
        objects.push(ObjectRecord {
            unit: unit.into(),
            base_path: format!("build/PAL/src/{prefix}.o"),
            status: ObjectStatus::Available,
            sha256: Some(object_hash.clone()),
            compiler: Some("mwcc".into()),
            c_flags_sha256: Some(format!("{:x}", Sha256::digest(flags.as_bytes()))),
            c_flags: Some(flags),
            build_freshness: BuildFreshness::Clean,
            functions: vec![
                function(&left, "0x00000000", "0x00000020", left_hash, false),
                function("helper", "0x00000020", "0x00000030", 'a', true),
                function(&right, "0x00000030", "0x00000050", right_hash, false),
            ],
        });
        definitions.push(CompiledDefinition {
            unit: unit.into(),
            name: "helper".into(),
            section: ".text".into(),
            address: "0x00000020".into(),
            end: "0x00000030".into(),
            normalized_body_sha256: "a".repeat(64),
            weak: true,
            object_sha256: object_hash,
        });
        targets.extend([
            target(&left, &address(0), &address(0x20), left_hash),
            target("helper", &address(0x20), &address(0x30), 'a'),
            target(&right, &address(0x30), &address(0x50), right_hash),
        ]);
        attributions.extend([
            anchor(unit, &left, &address(0), &address(0x20)),
            anchor(unit, &right, &address(0x30), &address(0x50)),
        ]);
        target_references.push(TargetFunctionReferences {
            section: ".text".into(),
            address: address(0x20),
            end: address(0x30),
            references: Vec::new(),
        });
    }
    let mut evidence = ObjectEvidence {
        status: ScanStatus::Scanned,
        objdiff_sha256: Some("d".repeat(64)),
        build_graph_sha256: Some("e".repeat(64)),
        target_image_sha256: Some("f".repeat(64)),
        objects,
        configured_objects: Some(vec![
            ConfiguredObject {
                unit: Some("A.cpp".into()),
                base_path: "build/PAL/src/A.o".into(),
                target_path: Some("build/PAL/obj/A.o".into()),
            },
            ConfiguredObject {
                unit: Some("B.cpp".into()),
                base_path: "build/PAL/src/B.o".into(),
                target_path: Some("build/PAL/obj/B.o".into()),
            },
        ]),
        linked_object_inputs: Some(vec!["build/PAL/obj/A.o".into(), "build/PAL/obj/B.o".into()]),
        retail_only_inputs: Some(Vec::new()),
        unscanned_configured_units: 0,
        unmapped_units: Vec::new(),
        definitions,
        target_references,
        order_matches: Vec::new(),
        relocation_matches: Vec::new(),
        emitted_owners: Vec::new(),
        relocation_placements: Vec::new(),
    };
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    evidence.canonicalize_target_references(&targets).unwrap();
    let source_functions = attributions
        .iter()
        .map(|item| SourceFunctionObservation {
            name: item.source.name.clone(),
            unit: item.source.unit.clone(),
            module: item.source.module.clone(),
            section: item.source.section.clone(),
            address: item.source.address.clone(),
            end: item.source.end.clone(),
            extent_known: true,
            normalized_body_sha256: targets
                .iter()
                .find(|target| target.address == item.target.address)
                .unwrap()
                .normalized_body_sha256
                .clone(),
            weak: false,
        })
        .collect();
    (evidence, units, source_functions, targets, attributions)
}

fn relocation_fixture() -> (
    ObjectEvidence,
    BTreeSet<String>,
    Vec<SourceFunctionObservation>,
    Vec<TargetFunctionObservation>,
    Vec<FunctionAttribution>,
) {
    let (mut evidence, units, source, targets, attributions) = fixture();
    for (index, record) in evidence.objects.iter_mut().enumerate() {
        let target_address = if index == 0 { 0x1000 } else { 0x2000 };
        let endpoint_name = record.functions[0].name.clone();
        record.functions[1].references.push(CompiledReference {
            offset: 4,
            kind: "PpcRel24".into(),
            target: endpoint_name.clone(),
            target_section: Some(".text".into()),
            target_address: 0,
            addend: 0,
        });
        evidence.target_references[index].references.push(CompiledReference {
            offset: 4,
            kind: "PpcRel24".into(),
            target: endpoint_name,
            target_section: Some(".text".into()),
            target_address,
            addend: 0,
        });
    }
    (evidence, units, source, targets, attributions)
}

#[test]
fn two_shared_definitions_have_distinct_independently_placed_retail_copies() {
    let (evidence, units, source, targets, attributions) = fixture();
    let order = order_matches(&evidence, &targets, &attributions);
    assert_eq!(order.len(), 2);
    assert!(order.iter().all(|item| {
        item.before.as_ref().is_some_and(|before| before.independently_attributed)
            && item.after.as_ref().is_some_and(|after| after.independently_attributed)
    }));
    let resolved = emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions);
    assert_eq!(resolved.len(), 2);
    assert_eq!(resolved[0].unit, "A.cpp");
    assert_eq!(resolved[0].target_address, "0x00001020");
    assert_eq!(resolved[0].excluded_competitors, ["B.cpp"]);
    assert_eq!(resolved[1].unit, "B.cpp");
    assert_eq!(resolved[1].target_address, "0x00002020");
    assert_eq!(resolved[1].excluded_competitors, ["A.cpp"]);
}

#[test]
fn an_owned_competitor_can_exclude_itself_from_an_unowned_copy() {
    let (evidence, units, source, mut targets, attributions) = fixture();
    targets.iter_mut().find(|item| item.address == "0x00002020").unwrap().current_owner =
        Some("B.cpp".into());
    let resolved = emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions);
    assert_eq!(resolved.len(), 2);
    assert_eq!(resolved[0].unit, "A.cpp");
    assert_eq!(resolved[0].excluded_competitors, ["B.cpp"]);

    targets.iter_mut().find(|item| item.address == "0x00002020").unwrap().current_owner =
        Some("A.cpp".into());
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn the_linker_must_account_for_every_object_and_archive_input() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    evidence.linked_object_inputs.as_mut().unwrap().push("build/PAL/unknown.a".into());
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );

    evidence.linked_object_inputs.as_mut().unwrap().pop();
    evidence.configured_objects.as_mut().unwrap().push(ConfiguredObject {
        unit: Some("Unlisted.cpp".into()),
        base_path: "build/PAL/src/Unlisted.o".into(),
        target_path: Some("build/PAL/obj/Unlisted.o".into()),
    });
    evidence.unscanned_configured_units = 0; // A serialized count cannot hide this entry.
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    assert_eq!(evidence.unscanned_configured_units, 1);
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn configured_retail_only_inputs_are_accounted_for_without_compiled_definitions() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    let retail = "build/PAL/obj/auto_03_80003000_text.o".to_string();
    evidence.retail_only_inputs.as_mut().unwrap().push(retail.clone());
    evidence.linked_object_inputs.as_mut().unwrap().push(retail.clone());
    assert_eq!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).len(),
        2
    );
    evidence.retail_only_inputs.as_mut().unwrap().push(retail);
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn an_archive_cannot_be_whitelisted_as_one_retail_only_object() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    let archive = "build/PAL/obj/unknown.a".to_string();
    evidence.retail_only_inputs.as_mut().unwrap().push(archive.clone());
    evidence.linked_object_inputs.as_mut().unwrap().push(archive);
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn external_compiled_object_is_scanned_and_can_block_a_shared_body_claim() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    let mut external = evidence.objects[0].clone();
    external.unit = "NewTargetOnly.cpp".into();
    external.base_path = "build/PAL/src/NewTargetOnly.o".into();
    external.functions[1].normalized_body_sha256 = Some("f".repeat(64));
    evidence.configured_objects.as_mut().unwrap().push(ConfiguredObject {
        unit: Some(external.unit.clone()),
        base_path: external.base_path.clone(),
        target_path: Some("build/PAL/obj/NewTargetOnly.o".into()),
    });
    evidence.linked_object_inputs.as_mut().unwrap().push(external.base_path.clone());
    evidence.objects.push(external);
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    assert_eq!(evidence.unscanned_configured_units, 0);
    assert_eq!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).len(),
        2
    );

    evidence.objects[2].functions[1].normalized_body_sha256 = Some("a".repeat(64));
    let mut definition = evidence.definitions[0].clone();
    definition.unit = "NewTargetOnly.cpp".into();
    evidence.definitions.push(definition);
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );

    let mut report = IdentificationReport::empty("NTSC", "PAL");
    report.attributions = attributions;
    report.source_functions = source;
    report.target_functions = targets;
    report.object_evidence = Some(evidence);
    report.units =
        vec![UnitIdentification::absent("A.cpp", 2), UnitIdentification::absent("B.cpp", 2)];
    report.schema = 13;
    assert!(ObservationIndex::load_self_contained(report.clone(), "NTSC", "PAL").is_err());
    report.schema = 14;
    let loaded = ObservationIndex::load_self_contained(report, "NTSC", "PAL").unwrap();
    assert!(loaded.report().object_evidence.as_ref().unwrap().emitted_owners.is_empty());
}

#[test]
fn two_compiled_objects_mapped_to_one_unit_do_not_silently_replace_each_other() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    let mut duplicate = evidence.objects[0].clone();
    duplicate.base_path = "build/PAL/src/0A.o".into();
    duplicate.functions.clear();
    evidence.configured_objects.as_mut().unwrap().push(ConfiguredObject {
        unit: Some("A.cpp".into()),
        base_path: duplicate.base_path.clone(),
        target_path: None,
    });
    evidence.linked_object_inputs.as_mut().unwrap().push(duplicate.base_path.clone());
    evidence.objects.push(duplicate);
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn duplicated_configured_object_does_not_become_a_unique_emitter() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    let duplicate = evidence.configured_objects.as_ref().unwrap()[0].clone();
    evidence.configured_objects.as_mut().unwrap().push(duplicate);
    evidence.canonicalize(&units, &BTreeSet::from(["a".repeat(64)]), true).unwrap();
    assert_eq!(evidence.configured_objects.as_ref().unwrap().len(), 3);
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn a_competitor_without_two_independent_anchors_is_not_ruled_out() {
    let (evidence, units, source, targets, mut attributions) = fixture();
    attributions.retain(|item| item.id != "B.cpp:B_right");
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn a_serialized_independent_flag_cannot_replace_unique_body_evidence() {
    let (evidence, units, mut source, targets, attributions) = fixture();
    let mut duplicate = source[0].clone();
    duplicate.unit = "B.cpp".into();
    duplicate.address = "0x00004000".into();
    duplicate.end = "0x00004020".into();
    source.push(duplicate);
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn incomplete_or_stale_objects_and_surplus_target_copies_do_not_prove_emission() {
    let (mut evidence, units, source, mut targets, attributions) = fixture();
    evidence.objects[1].build_freshness = BuildFreshness::Dirty;
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
    evidence.objects[1].build_freshness = BuildFreshness::Clean;
    evidence.unscanned_configured_units = 1;
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
    evidence.unscanned_configured_units = 0;
    assert!(
        emitted_owner_resolutions(
            &evidence,
            &BTreeSet::from(["A.cpp".into(), "B.cpp".into(), "C.cpp".into()]),
            &source,
            &targets,
            &attributions,
        )
        .is_empty()
    );
    targets.push(target("helper", "0x00003020", "0x00003030", 'a'));
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn matching_instructions_with_unproved_relocations_do_not_prove_emission() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    evidence.objects[0].functions[1].references.push(CompiledReference {
        offset: 4,
        kind: "PpcRel24".into(),
        target: "external".into(),
        target_section: Some(".text".into()),
        target_address: 0,
        addend: 0,
    });
    assert!(
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions).is_empty()
    );
}

#[test]
fn relocation_endpoint_bodies_place_each_copy_and_name_the_excluded_competitor() {
    let (mut evidence, units, source, targets, attributions) = relocation_fixture();
    let placements = relocation_placements(&evidence, &units, &source, &targets, &attributions);
    assert_eq!(placements.len(), 2);
    assert_eq!(placements[0].unit, "A.cpp");
    assert_eq!(placements[0].target_address, "0x00001020");
    assert_eq!(placements[0].distinctive_offset, 4);
    assert_eq!(placements[0].excluded_competitors[0].unit, "B.cpp");
    assert_eq!(placements[0].excluded_competitors[0].target_address, "0x00002020");
    assert!(placements.iter().all(|item| item.inventory_complete));

    evidence.unscanned_configured_units = 1;
    let partial = relocation_placements(&evidence, &units, &source, &targets, &attributions);
    assert_eq!(partial.len(), 2);
    assert!(partial.iter().all(|item| !item.inventory_complete));

    evidence.unscanned_configured_units = 0;
    evidence.target_references[1].references[0].target_address = 0x1000;
    assert!(relocation_placements(&evidence, &units, &source, &targets, &attributions).is_empty());
}

#[test]
fn a_unique_endpoint_without_independent_identity_does_not_place_a_copy() {
    let (evidence, units, source, targets, mut attributions) = relocation_fixture();
    attributions.retain(|item| !item.id.ends_with("_left"));
    assert!(relocation_placements(&evidence, &units, &source, &targets, &attributions).is_empty());
}

#[test]
fn differing_relocations_inside_an_endpoint_refuse_the_family() {
    let (mut evidence, units, source, targets, attributions) = relocation_fixture();
    for (index, record) in evidence.objects.iter_mut().enumerate() {
        let reference = CompiledReference {
            offset: 8,
            kind: "PpcRel24".into(),
            target: "same_callee".into(),
            target_section: None,
            target_address: 0,
            addend: 0,
        };
        record.functions[0].references.push(reference.clone());
        evidence.target_references.push(TargetFunctionReferences {
            section: ".text".into(),
            address: if index == 0 { "0x00001000" } else { "0x00002000" }.into(),
            end: if index == 0 { "0x00001020" } else { "0x00002020" }.into(),
            references: vec![reference.clone()],
        });
    }
    assert_eq!(relocation_placements(&evidence, &units, &source, &targets, &attributions).len(), 2);
    evidence.target_references[2].references[0].target = "different_callee".into();
    assert!(relocation_placements(&evidence, &units, &source, &targets, &attributions).is_empty());
}

#[test]
fn endpoint_references_to_different_sections_do_not_agree_by_name() {
    let (mut evidence, units, source, targets, attributions) = relocation_fixture();
    let reference = CompiledReference {
        offset: 8,
        kind: "PpcAddr32".into(),
        target: "same_name".into(),
        target_section: Some(".rodata".into()),
        target_address: 0,
        addend: 0,
    };
    for (index, record) in evidence.objects.iter_mut().enumerate() {
        record.functions[0].references.push(reference.clone());
        evidence.target_references.push(TargetFunctionReferences {
            section: ".text".into(),
            address: if index == 0 { "0x00001000" } else { "0x00002000" }.into(),
            end: if index == 0 { "0x00001020" } else { "0x00002020" }.into(),
            references: vec![reference.clone()],
        });
    }
    assert_eq!(relocation_placements(&evidence, &units, &source, &targets, &attributions).len(), 2);
    evidence.target_references[2].references[0].target_section = Some(".data".into());
    assert!(relocation_placements(&evidence, &units, &source, &targets, &attributions).is_empty());
}

#[test]
fn an_endpoint_body_repeated_in_another_object_is_not_distinctive() {
    let (mut evidence, units, source, targets, attributions) = relocation_fixture();
    evidence.objects[1].functions.push(function("extra", "0x00000050", "0x00000070", '1', false));
    assert!(relocation_placements(&evidence, &units, &source, &targets, &attributions).is_empty());
}

#[test]
fn relocation_placement_survives_stripped_target_names() {
    let (evidence, units, source, mut targets, attributions) = relocation_fixture();
    let before = relocation_placements(&evidence, &units, &source, &targets, &attributions);
    for target in &mut targets {
        target.name = format!("fn_{}", target.address.trim_start_matches("0x"));
    }
    assert_eq!(relocation_placements(&evidence, &units, &source, &targets, &attributions), before);
}

#[test]
fn saved_resolutions_are_rebuilt_from_observations_and_rejected_in_older_schema() {
    let (mut evidence, _, source, targets, attributions) = fixture();
    let mut forged = emitted_owner_resolutions(
        &evidence,
        &BTreeSet::from(["A.cpp".into(), "B.cpp".into()]),
        &source,
        &targets,
        &attributions,
    );
    forged[0].unit = "forged.cpp".into();
    evidence.emitted_owners = forged;
    let mut report = IdentificationReport::empty("NTSC", "PAL");
    report.attributions = attributions;
    report.source_functions = source;
    report.target_functions = targets;
    report.object_evidence = Some(evidence);
    report.units =
        vec![UnitIdentification::absent("A.cpp", 2), UnitIdentification::absent("B.cpp", 2)];
    report.schema = 9;
    assert!(ObservationIndex::load_self_contained(report.clone(), "NTSC", "PAL").is_err());
    report.schema = 10;
    assert!(ObservationIndex::load_self_contained(report.clone(), "NTSC", "PAL").is_err());
    report.schema = dtk_migrate::analysis::ownership::IDENTIFICATION_SCHEMA;
    let index = ObservationIndex::load_self_contained(report.clone(), "NTSC", "PAL").unwrap();
    let resolved = &index.report().object_evidence.as_ref().unwrap().emitted_owners;
    assert_eq!(resolved.len(), 2);
    assert_eq!(resolved[0].unit, "A.cpp");
    assert_eq!(resolved[1].unit, "B.cpp");

    let (mut relocated, units, source, targets, attributions) = relocation_fixture();
    let mut fake = relocation_placements(&relocated, &units, &source, &targets, &attributions);
    fake[0].unit = "forged.cpp".into();
    relocated.relocation_placements = fake;
    report.object_evidence = Some(relocated);
    let reloaded = ObservationIndex::load_self_contained(report, "NTSC", "PAL").unwrap();
    let placements = &reloaded.report().object_evidence.as_ref().unwrap().relocation_placements;
    assert_eq!(placements.len(), 2);
    assert_eq!(placements[0].unit, "A.cpp");
}

#[test]
fn old_schemas_keep_their_diagnostic_records_and_saved_references() {
    let (mut evidence, units, source, targets, attributions) = fixture();
    evidence.emitted_owners =
        emitted_owner_resolutions(&evidence, &units, &source, &targets, &attributions);
    evidence.configured_objects = None;
    evidence.linked_object_inputs = None;
    evidence.retail_only_inputs = None;
    let old_resolutions = evidence.emitted_owners.clone();
    let mut report = IdentificationReport::empty("NTSC", "PAL");
    report.attributions = attributions;
    report.source_functions = source;
    report.target_functions = targets;
    report.object_evidence = Some(evidence);
    report.units =
        vec![UnitIdentification::absent("A.cpp", 2), UnitIdentification::absent("B.cpp", 2)];
    for schema in 10..=13 {
        report.schema = schema;
        let index = ObservationIndex::load_self_contained(report.clone(), "NTSC", "PAL").unwrap();
        assert_eq!(
            index.report().object_evidence.as_ref().unwrap().emitted_owners,
            old_resolutions
        );
        let directory = tempfile::tempdir().unwrap();
        let reference = index.persist(directory.path()).unwrap();
        assert_eq!(reference.schema, schema);
        assert!(load_reference(&reference, "NTSC", "PAL").is_ok());
    }
}
