//! Opt-in smoke test for compiled-source corroboration against a real project.

use std::{
    collections::{BTreeMap, BTreeSet},
    path::PathBuf,
    time::Instant,
};

use dtk_migrate::{
    analysis::{
        coverage::CoverageUnit,
        helpers::tail_hypotheses,
        matching::MatchTarget,
        object_evidence::{
            BuildFreshness, ObjectStatus, ScanStatus, capture_target_references,
            emitted_owner_resolutions, inspect, order_matches, relocation_matches,
            relocation_placements, target_image_digest,
        },
        ownership::{IDENTIFICATION_SCHEMA, IdentificationReport, ObservationIndex},
    },
    project::{
        analyze::load_analyzed,
        ownership_transaction::{OwnershipTransaction, Provenance},
    },
    stages::coverage::alternatives::{assess_member, build as coverage_alternatives},
};
use typed_path::Utf8NativePath;

#[test]
fn historical_pal_compiled_bridges_keep_emitted_ownership_separate() {
    let Some(path) = std::env::var_os("DTK_MIGRATE_SCHEMA18_REPORT") else {
        eprintln!("skipped: set DTK_MIGRATE_SCHEMA18_REPORT");
        return;
    };
    let report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
    assert_eq!(report.schema, 18);
    let canonical =
        ObservationIndex::load_self_contained(report.clone(), &report.source, &report.target)
            .unwrap();
    let saved = report.object_evidence.as_ref().unwrap();
    let rebuilt = canonical.report().object_evidence.as_ref().unwrap();
    assert_eq!(rebuilt.source_bridges, saved.source_bridges);
    assert!(rebuilt.source_bridges.iter().any(|item| {
        item.unit == "GuiSys/CGuiLight.cpp"
            && item.source_name == "BuildLight__9CGuiLightCFv"
            && item.target_address == "0x802AF85C"
            && !item.compiled_weak
    }));
    assert!(rebuilt.source_bridges.iter().any(|item| {
        item.unit != "MetroidPrime/TypesMatch.cpp"
            && item.current_owner.as_deref() == Some("MetroidPrime/TypesMatch.cpp")
            && !item.compiled_weak
    }));
    assert!(rebuilt.emitted_owners.is_empty());
}

#[test]
fn historical_pal_compiled_boundary_is_a_rederived_diagnostic() {
    let Some(path) = std::env::var_os("DTK_MIGRATE_SCHEMA18_REPORT") else {
        eprintln!("skipped: set DTK_MIGRATE_SCHEMA18_REPORT");
        return;
    };
    let mut report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
    report.schema = IDENTIFICATION_SCHEMA;
    let (source, target) = (report.source.clone(), report.target.clone());
    let index = ObservationIndex::load_self_contained(report, &source, &target).unwrap();
    let evidence = index.report().object_evidence.as_ref().unwrap();
    assert_eq!(evidence.compiled_boundaries.len(), 1);
    let boundary = &evidence.compiled_boundaries[0];
    assert_eq!(boundary.left_unit, "GuiSys/CGuiHeadWidget.cpp");
    assert_eq!(boundary.right_unit, "GuiSys/CGuiLight.cpp");
    assert_eq!(boundary.target_addresses[2..5], ["0x802AF844", "0x802AF850", "0x802AF85C"]);
    assert!(evidence.emitted_owners.is_empty());

    let mut blocks = indexmap::IndexMap::new();
    blocks.insert(boundary.left_unit.clone(), vec![
        "\t.text       start:0x802AF704 end:0x802AF844".into(),
    ]);
    blocks.insert(boundary.right_unit.clone(), vec![
        "\t.text       start:0x802AFA14 end:0x802AFDDC".into(),
    ]);
    let joint = OwnershipTransaction::build(
        &blocks,
        [
            (boundary.left_unit.clone(), vec![
                "\t.text       start:0x802AF704 end:0x802AF850".into(),
            ]),
            (boundary.right_unit.clone(), vec![
                "\t.text       start:0x802AF850 end:0x802AFDDC".into(),
            ]),
        ],
        Provenance { evidence: vec!["compiled-boundary".into()], ..Default::default() },
    )
    .unwrap();
    joint.preview(&blocks).unwrap();
    let left = assess_member(&index, &joint, &boundary.left_unit).unwrap();
    let right = assess_member(&index, &joint, &boundary.right_unit).unwrap();
    assert_eq!(left.new_compiled_boundary_members, 1);
    assert_eq!(right.new_compiled_boundary_members, 2);
    assert!(left.permits_automatic_claim() && right.permits_automatic_claim());
    let solo = OwnershipTransaction::build(
        &blocks,
        [(boundary.left_unit.clone(), vec![
            "\t.text       start:0x802AF704 end:0x802AF850".into(),
        ])],
        Provenance::default(),
    )
    .unwrap();
    assert!(!assess_member(&index, &solo, &boundary.left_unit).unwrap().permits_automatic_claim());

    let unit = |name: &str| -> CoverageUnit {
        serde_json::from_value(serde_json::json!({
            "name": name, "code_bytes": 0, "autogenerated": false,
            "source_functions": 0, "no_exact_target_body": 0,
            "name_only_candidates": 0, "ambiguous_exact_bodies": 0,
            "anchors": [], "layout_shift_candidates": 0,
            "layout_shift_anchors": [], "boundary_sequences": [],
            "adjacent_owner_transitions": [], "required_extracts": []
        }))
        .unwrap()
    };
    let left_unit = unit(&boundary.left_unit);
    let right_unit = unit(&boundary.right_unit);
    let source_units = BTreeMap::from([
        (boundary.left_unit.clone(), &left_unit),
        (boundary.right_unit.clone(), &right_unit),
    ]);
    let mut source_blocks = indexmap::IndexMap::new();
    source_blocks.insert(boundary.left_unit.clone(), vec![
        "\t.text       start:0x802C35F4 end:0x802C3740".into(),
    ]);
    source_blocks.insert(boundary.right_unit.clone(), vec![
        "\t.text       start:0x802C3740 end:0x802C3BB8".into(),
    ]);
    let alternatives =
        coverage_alternatives(&left_unit, &blocks, &source_units, &source_blocks, &index);
    let selected = alternatives.iter().find(|item| item.evidence == "compiled-boundary").unwrap();
    assert_eq!(selected.transaction.members.len(), 2);
    assert_eq!(
        selected.transaction.member(&boundary.left_unit).unwrap().after[0],
        "\t.text       start:0x802AF704 end:0x802AF850"
    );
    assert_eq!(
        selected.transaction.member(&boundary.right_unit).unwrap().after[0],
        "\t.text       start:0x802AF850 end:0x802AFDDC"
    );
    let mut truncated_source = source_blocks.clone();
    truncated_source[&boundary.left_unit][0] =
        "\t.text       start:0x802C35F4 end:0x802C3734".into();
    assert!(
        coverage_alternatives(&left_unit, &blocks, &source_units, &truncated_source, &index)
            .iter()
            .all(|item| item.evidence != "compiled-boundary")
    );

    let mut duplicate = evidence.clone();
    let mut stale =
        duplicate.objects.iter().find(|item| item.unit == boundary.left_unit).unwrap().clone();
    stale.build_freshness = BuildFreshness::Dirty;
    duplicate.objects.push(stale);
    assert!(
        dtk_migrate::analysis::object_boundary::compiled_boundaries(
            &duplicate,
            &index.report().source_functions,
            &index.report().target_functions,
            &index.report().attributions,
        )
        .is_empty()
    );

    let mut wrong_order = index.report().source_functions.clone();
    wrong_order
        .iter_mut()
        .find(|item| item.address == boundary.source_addresses[0])
        .unwrap()
        .unit = "MetroidPrime/TypesMatch.cpp".into();
    assert!(
        dtk_migrate::analysis::object_boundary::compiled_boundaries(
            evidence,
            &wrong_order,
            &index.report().target_functions,
            &index.report().attributions,
        )
        .is_empty()
    );

    let mut tampered = index.report().clone();
    tampered
        .target_functions
        .iter_mut()
        .find(|item| item.address == "0x802AF844")
        .unwrap()
        .current_owner = Some("MetroidPrime/TypesMatch.cpp".into());
    let rebuilt = ObservationIndex::load_self_contained(tampered, &source, &target).unwrap();
    assert!(rebuilt.report().object_evidence.as_ref().unwrap().compiled_boundaries.is_empty());
}

#[test]
fn historical_pal_report_identifies_collider_tail_from_caller() {
    let Some(path) = std::env::var_os("DTK_MIGRATE_HISTORICAL_COMPLETE_REPORT") else {
        eprintln!("skipped: set DTK_MIGRATE_HISTORICAL_COMPLETE_REPORT");
        return;
    };
    let mut report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
    let compiled = &report.object_evidence.as_ref().unwrap().definitions;
    let hypotheses = tail_hypotheses(
        &report.source_functions,
        &report.target_functions,
        &report.attributions,
        compiled,
    );
    assert!(hypotheses.iter().any(|item| {
        item.candidate_unit == "WorldFormat/CMetroidAreaCollider.cpp"
            && item.address == "0x802944F0"
            && item.generated_name_evidence.is_empty()
            && !item.candidate_definition_observed
            && item.candidate_caller_ids.len() == 1
            && item.other_or_unattributed_callers == 0
    }));
    report.schema = IDENTIFICATION_SCHEMA;
    let canonical =
        ObservationIndex::load_self_contained(report.clone(), &report.source, &report.target)
            .unwrap();
    assert_eq!(canonical.report().helper_tail_hypotheses, hypotheses);
}

#[test]
fn historical_pal_get_generator_desc_does_not_exclude_an_unproved_competitor() {
    let Some(path) = std::env::var_os("DTK_MIGRATE_HISTORICAL_COMPLETE_REPORT") else {
        eprintln!("skipped: set DTK_MIGRATE_HISTORICAL_COMPLETE_REPORT");
        return;
    };
    let report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
    let canonical =
        ObservationIndex::load_self_contained(report.clone(), &report.source, &report.target)
            .unwrap();
    let evidence = report.object_evidence.as_ref().unwrap();
    assert_eq!(evidence.unscanned_configured_units, 10);
    assert_eq!(evidence.unmapped_units.len(), 23);
    let units = report.units.iter().map(|item| item.unit.clone()).collect();
    let placements = relocation_placements(
        evidence,
        &units,
        &report.source_functions,
        &report.target_functions,
        &report.attributions,
    );
    assert_eq!(
        canonical.report().object_evidence.as_ref().unwrap().relocation_placements,
        evidence.relocation_placements
    );
    let old = evidence
        .relocation_placements
        .iter()
        .find(|item| item.target_address == "0x803485F4")
        .unwrap();
    assert_eq!(old.unit, "Kyoto/Particles/CParticleElectricDataFactory.cpp");
    assert_eq!(old.excluded_competitors.len(), 2);
    // The old family-wide placement overlooked two differing data-symbol
    // destinations inside Projectile's endpoint. One unresolved competitor
    // means the Electric occurrence cannot exclude the entire family.
    assert!(placements.iter().all(|item| item.target_address != "0x803485F4"));
    assert!(evidence.emitted_owners.is_empty());
}

#[test]
fn compiled_widget_body_is_available_without_assigning_its_retail_owner() {
    let (Some(root), Some(report_path)) = (
        std::env::var_os("DTK_MIGRATE_OBJECT_ROOT").map(PathBuf::from),
        std::env::var_os("DTK_MIGRATE_HELPER_REPORT").map(PathBuf::from),
    ) else {
        eprintln!("skipped: set DTK_MIGRATE_OBJECT_ROOT and DTK_MIGRATE_HELPER_REPORT");
        return;
    };
    let report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(report_path).unwrap()).unwrap();
    let hash = report
        .target_functions
        .iter()
        .find(|function| function.address == "0x802AF844")
        .unwrap()
        .normalized_body_sha256
        .as_ref()
        .unwrap()
        .clone();
    let unit = "GuiSys/CGuiHeadWidget.cpp".to_string();
    let original_directory = std::env::current_dir().unwrap();
    let evidence =
        inspect(&root, "GM8P01_00", &BTreeSet::from([unit.clone()]), &BTreeSet::from([hash]));
    assert_eq!(std::env::current_dir().unwrap(), original_directory);
    assert_eq!(evidence.status, ScanStatus::Scanned);
    assert_eq!(evidence.objects.len(), 1);
    assert_eq!(evidence.objects[0].status, ObjectStatus::Available);
    assert!(!evidence.objects[0].functions.is_empty());
    assert!(
        evidence.definitions.iter().any(
            |definition| definition.unit == unit && definition.name.contains("GetWidgetTypeID")
        )
    );
}

#[test]
fn frozen_sparse_objects_expose_immediate_order_without_assigning_an_owner() {
    let (Some(root), Some(report_path)) = (
        std::env::var_os("DTK_MIGRATE_FROZEN_OBJECT_ROOT").map(PathBuf::from),
        std::env::var_os("DTK_MIGRATE_OBJECT_REPORT").map(PathBuf::from),
    ) else {
        eprintln!("skipped: set DTK_MIGRATE_FROZEN_OBJECT_ROOT and DTK_MIGRATE_OBJECT_REPORT");
        return;
    };
    let report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(report_path).unwrap()).unwrap();
    let saved = report.object_evidence.as_ref().unwrap();
    let expected: Vec<_> =
        saved.objects.iter().filter(|record| record.status == ObjectStatus::Available).collect();
    let units = expected.iter().map(|record| record.unit.clone()).collect();
    let hashes = report
        .target_functions
        .iter()
        .filter(|function| function.current_owner.is_none() || function.owner_autogenerated)
        .filter_map(|function| function.normalized_body_sha256.clone())
        .collect();
    let mut evidence = inspect(&root, "GM8P01_00", &units, &hashes);
    assert_eq!(evidence.status, ScanStatus::Scanned);
    for record in expected {
        let scanned = evidence.objects.iter().find(|item| item.unit == record.unit).unwrap();
        assert_eq!(scanned.status, ObjectStatus::Available);
        assert_eq!(scanned.sha256, record.sha256);
    }
    evidence.canonicalize(&units, &hashes, true).unwrap();
    let matches = order_matches(&evidence, &report.target_functions, &report.attributions);
    assert_eq!(matches.len(), 2);
    assert!(matches.iter().any(|item| {
        item.unit == "GuiSys/CGuiHeadWidget.cpp"
            && item.target_address == "0x802AF844"
            && item.before.as_ref().is_some_and(|before| before.target_address == "0x802AF7E4")
    }));
    assert!(matches.iter().any(|item| {
        item.unit == "MetroidPrime/Weapons/CPowerBomb.cpp"
            && item.target_address == "0x80144E10"
            && item.before.as_ref().is_some_and(|before| before.target_address == "0x80144DA0")
    }));
    assert!(matches.iter().all(|item| {
        !item.before.as_ref().is_some_and(|before| before.independently_attributed)
            && !item.after.as_ref().is_some_and(|after| after.independently_attributed)
    }));
    let source_units = report.units.iter().map(|unit| unit.unit.clone()).collect();
    assert!(
        emitted_owner_resolutions(
            &evidence,
            &source_units,
            &report.source_functions,
            &report.target_functions,
            &report.attributions,
        )
        .is_empty()
    );
}

#[test]
fn frozen_sparse_objects_correlate_references_without_assigning_an_owner() {
    let (Some(root), Some(report_path), Some(config_path)) = (
        std::env::var_os("DTK_MIGRATE_FROZEN_OBJECT_ROOT").map(PathBuf::from),
        std::env::var_os("DTK_MIGRATE_OBJECT_REPORT").map(PathBuf::from),
        std::env::var_os("DTK_MIGRATE_TARGET_CONFIG").map(PathBuf::from),
    ) else {
        eprintln!("skipped: set frozen object root, report and target config");
        return;
    };
    let mut report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(report_path).unwrap()).unwrap();
    let expected: Vec<_> = report
        .object_evidence
        .as_ref()
        .unwrap()
        .objects
        .iter()
        .filter(|record| record.status == ObjectStatus::Available)
        .collect();
    let units = expected.iter().map(|record| record.unit.clone()).collect();
    let hashes = report
        .target_functions
        .iter()
        .filter_map(|function| function.normalized_body_sha256.clone())
        .collect();
    let mut evidence = inspect(&root, "GM8P01_00", &units, &hashes);
    evidence.canonicalize(&units, &hashes, true).unwrap();
    assert!(evidence.build_graph_sha256.is_some());
    for record in expected {
        let scanned = evidence.objects.iter().find(|item| item.unit == record.unit).unwrap();
        assert_eq!(scanned.sha256, record.sha256);
        assert_eq!(scanned.build_freshness, BuildFreshness::Clean);
        assert!(scanned.compiler.is_some());
        assert!(scanned.c_flags.is_some());
        assert!(scanned.c_flags_sha256.is_some());
    }
    let config = Utf8NativePath::new(config_path.to_str().unwrap());
    let (_, obj) = load_analyzed(config, None, "--target-root").unwrap();
    let target = MatchTarget::new(config.to_string(), obj);
    evidence.target_image_sha256 = Some(target_image_digest(&target));
    evidence.target_references =
        capture_target_references(&target, &report.target_functions, &evidence.definitions);
    evidence.canonicalize_target_references(&report.target_functions).unwrap();
    let matches = relocation_matches(&evidence, &report.target_functions, &report.attributions);
    assert_eq!(matches.len(), 8);
    assert!(matches.iter().any(|item| {
        item.unit == "GuiSys/CGuiGroup.cpp"
            && item.target_address == "0x802AD3DC"
            && item.correlated.iter().any(|reference| {
                reference.compiled_target == "__vt__9CGuiGroup"
                    && reference.basis
                        == dtk_migrate::analysis::object_evidence::ReferenceBasis::NamedSymbol
            })
    }));
    assert!(matches.iter().any(|item| {
        item.unit == "GuiSys/CGuiHeadWidget.cpp" && item.target_address == "0x802ADC9C"
    }));
    assert!(matches.iter().any(|item| {
        item.unit == "MetroidPrime/Weapons/CPowerBomb.cpp" && item.target_address == "0x8003B8B0"
    }));
    evidence.relocation_matches = matches.clone();
    evidence.relocation_matches[0].unit = "forged.cpp".into();
    report.schema = IDENTIFICATION_SCHEMA;
    report.object_evidence = Some(evidence);
    let source = report.source.clone();
    let target_name = report.target.clone();
    let index = ObservationIndex::load_self_contained(report, &source, &target_name).unwrap();
    assert_eq!(index.report().object_evidence.as_ref().unwrap().relocation_matches, matches);
    let saved = serde_json::to_vec(index.report()).unwrap();
    let reloaded = ObservationIndex::load_self_contained(
        serde_json::from_slice(&saved).unwrap(),
        &source,
        &target_name,
    )
    .unwrap();
    assert_eq!(reloaded.digest(), index.digest());
}

#[test]
fn a_full_object_inventory_remains_canonical_and_binary_only_fallback_exists() {
    let (Some(root), Some(report_path), Some(config_path)) = (
        std::env::var_os("DTK_MIGRATE_FULL_OBJECT_ROOT").map(PathBuf::from),
        std::env::var_os("DTK_MIGRATE_HELPER_REPORT").map(PathBuf::from),
        std::env::var_os("DTK_MIGRATE_TARGET_CONFIG").map(PathBuf::from),
    ) else {
        eprintln!("skipped: set full object root, helper report and target config");
        return;
    };
    let mut report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(report_path).unwrap()).unwrap();
    let mut binary_only_report = report.clone();
    binary_only_report.object_evidence = None;
    let units = report.units.iter().map(|unit| unit.unit.clone()).collect();
    let hashes = report
        .target_functions
        .iter()
        .filter_map(|function| function.normalized_body_sha256.clone())
        .collect();
    let mut evidence = inspect(&root, "GM8P01_00", &units, &hashes);
    assert_eq!(evidence.status, ScanStatus::Scanned);
    evidence.canonicalize(&units, &hashes, true).unwrap();
    let available =
        evidence.objects.iter().filter(|record| record.status == ObjectStatus::Available).count();
    let clean = evidence
        .objects
        .iter()
        .filter(|record| record.build_freshness == BuildFreshness::Clean)
        .count();
    let functions: usize = evidence.objects.iter().map(|record| record.functions.len()).sum();
    let matches = order_matches(&evidence, &report.target_functions, &report.attributions);
    let independent = matches
        .iter()
        .filter(|item| {
            item.before.as_ref().is_some_and(|before| before.independently_attributed)
                || item.after.as_ref().is_some_and(|after| after.independently_attributed)
        })
        .count();
    eprintln!(
        "available={available} ninja_clean={clean} functions={functions} definitions={} order_matches={} independent={} bytes={}",
        evidence.definitions.len(),
        matches.len(),
        independent,
        serde_json::to_vec(&evidence).unwrap().len(),
    );
    assert!(available > 100);
    assert!(functions > available);
    evidence.order_matches = matches;
    let config = Utf8NativePath::new(config_path.to_str().unwrap());
    let (_, obj) = load_analyzed(config, None, "--target-root").unwrap();
    let target = MatchTarget::new(config.to_string(), obj);
    evidence.target_image_sha256 = Some(target_image_digest(&target));
    evidence.target_references =
        capture_target_references(&target, &report.target_functions, &evidence.definitions);
    evidence.canonicalize_target_references(&report.target_functions).unwrap();
    let placed = emitted_owner_resolutions(
        &evidence,
        &units,
        &report.source_functions,
        &report.target_functions,
        &report.attributions,
    );
    eprintln!(
        "object owner placements={} unscanned_configured={} unmapped_source_units={}",
        placed.len(),
        evidence.unscanned_configured_units,
        evidence.unmapped_units.len(),
    );
    if evidence.unscanned_configured_units != 0 || !evidence.unmapped_units.is_empty() {
        assert!(placed.is_empty());
    }
    let first_correlation = Instant::now();
    evidence.relocation_matches =
        relocation_matches(&evidence, &report.target_functions, &report.attributions);
    let first_elapsed = first_correlation.elapsed();
    let cached_correlation = Instant::now();
    let cached = relocation_matches(&evidence, &report.target_functions, &report.attributions);
    let cached_elapsed = cached_correlation.elapsed();
    assert_eq!(cached, evidence.relocation_matches);
    eprintln!(
        "target reference functions={} discriminating relocation matches={} first={first_elapsed:?} cached={cached_elapsed:?}",
        evidence.target_references.len(),
        evidence.relocation_matches.len(),
    );
    report.schema = IDENTIFICATION_SCHEMA;
    binary_only_report.schema = report.schema;
    report.object_evidence = Some(evidence);
    let source = report.source.clone();
    let target = report.target.clone();
    let binary_only =
        ObservationIndex::load_self_contained(binary_only_report, &source, &target).unwrap();
    let first = ObservationIndex::load_self_contained(report, &source, &target).unwrap();
    assert_eq!(
        serde_json::to_value(&first.report().attributions).unwrap(),
        serde_json::to_value(&binary_only.report().attributions).unwrap(),
    );
    let saved = serde_json::to_vec(first.report()).unwrap();
    let reloaded = ObservationIndex::load_self_contained(
        serde_json::from_slice(&saved).unwrap(),
        &source,
        &target,
    )
    .unwrap();
    assert_eq!(reloaded.digest(), first.digest());
}

#[test]
fn sparse_historical_objects_remain_optional_and_canonical() {
    let Some(path) = std::env::var_os("DTK_MIGRATE_OBJECT_REPORT").map(PathBuf::from) else {
        eprintln!("skipped: set DTK_MIGRATE_OBJECT_REPORT to a frozen object-evidence report");
        return;
    };
    let report: IdentificationReport =
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap();
    let source = report.source.clone();
    let target = report.target.clone();
    let index = ObservationIndex::load_self_contained(report, &source, &target).unwrap();
    let evidence = index.report().object_evidence.as_ref().unwrap();
    assert_eq!(evidence.status, ScanStatus::Scanned);
    assert!(evidence.objects.iter().any(|record| {
        record.unit == "GuiSys/CGuiHeadWidget.cpp" && record.status == ObjectStatus::Available
    }));
    assert!(evidence.objects.iter().any(|record| record.status == ObjectStatus::Missing));
    assert!(!evidence.unmapped_units.is_empty());
    for (address, unit) in [
        ("0x802AF844", "GuiSys/CGuiHeadWidget.cpp"),
        ("0x802AF548", "GuiSys/CGuiGroup.cpp"),
        ("0x802B2374", "GuiSys/CGuiTableGroup.cpp"),
        ("0x80145158", "MetroidPrime/Weapons/CPowerBomb.cpp"),
    ] {
        let family = index
            .report()
            .helper_families
            .iter()
            .find(|family| family.target_occurrences.iter().any(|item| item.address == address))
            .unwrap();
        assert!(family.compiled_definitions.iter().any(|definition| definition.unit == unit));
    }
}
