"""Coverage candidate and transactional acceptance tests."""

import json
import subprocess
import tempfile
import unittest
from pathlib import Path

import coverage_adapter as adapter
import split_confidence_loop as scl
from calibrate_coverage import (
    ownership_at_layout,
    partition,
    score_candidate,
    summarize,
)
from migration_runtime import ValidationError


def anchor(start, end, *, eligible=True):
    return {
        "source_name": "large_function",
        "source_address": "0x00001000",
        "target_name": "target_function",
        "target_address": f"0x{start:08X}",
        "target_end": f"0x{end:08X}",
        "section": ".text",
        "size": end - start,
        "source_local": False,
        "target_local": False,
        "source_weak": False,
        "target_weak": False,
        "template_instantiation": False,
        "unique_source": True,
        "unique_target": True,
        "normalized_body_equal": True,
        "relocation_layout_equal": True,
        "required_alignment": 4,
        "existing_target_owner": None,
        "existing_owner_autogenerated": False,
        "eligible": eligible,
        "reasons": [] if eligible else ["test rejection"],
    }


def layout_anchor(
    start,
    end,
    group="layout-1",
    *,
    eligible=True,
    breakpoint=0xEC,
    source_address=None,
):
    value = anchor(start, end, eligible=eligible)
    value.update(
        {
            "normalized_body_equal": None,
            "layout_masked_body_equal": True,
            "support_group": group,
            "support_functions": 2,
            "support_bytes": 384,
            "support_changed_accesses": 8,
            "this_accesses": 5,
            "changed_this_accesses": 4,
            "offset_delta": 16,
            "inferred_breakpoint": breakpoint,
            "source_address": f"0x{source_address or start + 0x1000:08X}",
        }
    )
    return value


def candidate(name="A.cpp"):
    alternatives = [
        adapter._alternative(".text", 0x200, 0x300, [anchor(0x200, 0x300)]),
        adapter._alternative(".text", 0x400, 0x500, [anchor(0x400, 0x500)]),
    ]
    return {
        "name": name,
        "policy_version": adapter.POLICY_VERSION,
        "source_code_bytes": 1024,
        "required_extracts": [],
        "alternatives": alternatives,
    }


def required_extract():
    return {
        "source_symbol": "sDefaultFontData",
        "target_symbol": "lbl_00002000",
        "target_address": "0x00002000",
        "target_size": 0x904,
        "rename": "sDefaultFontData",
        "binary": "MetroidPrime/DefaultFontData.bin",
        "header": "MetroidPrime/DefaultFontData.inc",
        "relocations": None,
        "header_type": None,
        "custom_type": None,
        "custom_data": None,
        "reference_evidence": 2,
        "evidence": "boundary-sequence-data-reference",
    }


def boundary_sequence(start=0x200, end=0x800, *, eligible=True):
    functions = [
        {
            "source_name": f"function_{index}",
            "source_address": f"0x{0x1000 + index * 0x100:08X}",
            "target_address": f"0x{start + index * 0x100:08X}",
            "target_end": f"0x{start + index * 0x100 + 0x80:08X}",
            "size": 0x80,
            "tier": "confident",
            "method": "name",
            "confidence": 1.0,
            "primary": True,
        }
        for index in range(4)
    ]
    return {
        "section": ".text",
        "target_start": f"0x{start:08X}",
        "target_end": f"0x{end:08X}",
        "target_bytes": end - start,
        "previous_unit": "Previous.cpp",
        "next_unit": "Next.cpp",
        "source_functions": 4,
        "aligned_functions": 4,
        "aligned_bytes": 0x200,
        "strong_functions": 4,
        "direct_anchors": 4,
        "match_ratio": 1.0,
        "order_ratio": 1.0,
        "target_coverage": 0.5,
        "best_alignment_score": 512.0,
        "second_alignment_score": 0.0,
        "alignment_margin": 1.0,
        "functions": functions,
        "eligible": eligible,
        "reasons": [] if eligible else ["test rejection"],
    }


class FakeContext:
    def __init__(self, root, reject_first=False, regress=False, source_enabled=False):
        self.root, self.source, self.target = root, "S", "T"
        self.output, self.ninja = root / "evidence", "ninja"
        self.output.mkdir()
        path = root / "config/T/splits.txt"
        path.parent.mkdir(parents=True)
        path.write_text("Sections:\n\t.text type:code\n\n", encoding="utf-8")
        (root / "config/T/config.yml").write_text(
            "object: orig/T/main.dol\n\nmodules:\n", encoding="utf-8"
        )
        self.reject_first, self.regress, self.source_enabled = (
            reject_first,
            regress,
            source_enabled,
        )

    def build(self):
        blocks = scl.parse_splits((self.root / "config/T/splits.txt").read_text())[1]
        config = (self.root / "config/T/config.yml").read_text(encoding="utf-8")
        if "lbl_00002000" in config:
            header = self.root / "build/T/include/MetroidPrime/DefaultFontData.inc"
            header.parent.mkdir(parents=True, exist_ok=True)
            header.write_text("unsigned char sDefaultFontData[] = {};\n")
            binary = self.root / "build/T/bin/MetroidPrime/DefaultFontData.bin"
            binary.parent.mkdir(parents=True, exist_ok=True)
            binary.write_bytes(b"font")
        if self.reject_first and any(
            "0x00000200" in line for line in blocks.get("A.cpp", [])
        ):
            raise ValidationError(
                "Retail DOL bytes differ despite passing the checksum target"
            )
        units = [
            {
                "metadata": {"source_path": "src/existing.cpp", "complete": False},
                "measures": {"matched_code": 0 if self.regress and blocks else 10},
            }
        ]
        for name in blocks:
            units.append(
                {"metadata": {"complete": False}, "measures": {"matched_code": 0}}
            )
        objdiff = {
            "units": [
                {
                    "name": "main/" + Path(name).stem,
                    "target_path": f"build/T/obj/{Path(name).with_suffix('.o').as_posix()}",
                    "base_path": (
                        f"build/T/src/{Path(name).with_suffix('.o').as_posix()}"
                        if self.source_enabled
                        else None
                    ),
                }
                for name in blocks
            ]
        }
        (self.root / "objdiff.json").write_text(json.dumps(objdiff))
        dol = self.root / "build/T/main.dol"
        dol.parent.mkdir(parents=True, exist_ok=True)
        dol.write_bytes(b"retail")
        return {
            "units": units,
            "measures": {"matched_code": 10, "complete_code": "5", "total_code": "100"},
        }

    def run(self, command, capture=False):
        if command[1:3] == ["-t", "inputs"]:
            blocks = scl.parse_splits((self.root / "config/T/splits.txt").read_text())[
                1
            ]
            paths = [
                f"build/T/obj/{Path(name).with_suffix('.o').as_posix()}"
                for name in blocks
            ]
            if self.source_enabled:
                paths += [
                    f"build/T/src/{Path(name).with_suffix('.o').as_posix()}"
                    for name in blocks
                ]
            return "\n".join(paths)
        raise AssertionError(command)

    def dol_sha1(self):
        return "retail"


class CoverageTests(unittest.TestCase):
    def test_required_extract_renderer_is_idempotent_and_preserves_indentation(self):
        original = b'object: main.dol\nextract:\n  - symbol: "existing"\nmodules:\n'
        value = required_extract()
        value.update(
            {
                "relocations": "MetroidPrime/DefaultFontData.json",
                "header_type": "raw",
                "custom_type": "font",
                "custom_data": {"stride": 16},
            }
        )
        first = adapter.render_required_extracts(original, [value])
        second = adapter.render_required_extracts(first, [value])
        self.assertEqual(first, second)
        text = first.decode("utf-8")
        self.assertIn('  - symbol: "lbl_00002000"\n', text)
        self.assertIn('    rename: "sDefaultFontData"\n', text)
        self.assertIn('    relocations: "MetroidPrime/DefaultFontData.json"\n', text)
        self.assertIn('    custom_data: {"stride":16}\n', text)
        self.assertEqual(text.count('symbol: "lbl_00002000"'), 1)

    def test_required_extract_renderer_rejects_escaping_paths(self):
        value = required_extract()
        value["header"] = "../outside.inc"
        with self.assertRaisesRegex(ValueError, "Unsafe required extract path"):
            adapter.render_required_extracts(b"modules:\n", [value])

    def test_required_extract_is_accepted_with_candidate(self):
        with tempfile.TemporaryDirectory() as temporary:
            ctx = FakeContext(Path(temporary))
            value = candidate()
            value["required_extracts"] = [required_extract()]
            result = adapter.evaluate(ctx, [value])
            config = (ctx.root / "config/T/config.yml").read_text(encoding="utf-8")
            self.assertEqual(result["accepted"], [value])
            self.assertIn('symbol: "lbl_00002000"', config)
            self.assertIn('rename: "sDefaultFontData"', config)

    def test_required_extract_rolls_back_when_candidate_is_rejected(self):
        with tempfile.TemporaryDirectory() as temporary:
            ctx = FakeContext(Path(temporary), regress=True)
            path = ctx.root / "config/T/config.yml"
            original = path.read_bytes()
            value = candidate()
            value["required_extracts"] = [required_extract()]
            result = adapter.evaluate(ctx, [value])
            self.assertEqual(result["accepted"], [])
            self.assertEqual(path.read_bytes(), original)

    def test_boundary_sequence_is_preferred_as_one_bounded_range(self):
        unit = {
            "code_bytes": 0x800,
            "anchors": [anchor(0x300, 0x380)],
            "boundary_sequences": [boundary_sequence()],
        }
        alternatives = adapter.build_alternatives(unit, {})
        self.assertEqual(alternatives[0]["evidence"], "boundary-sequence")
        self.assertEqual(
            (alternatives[0]["start"], alternatives[0]["end"]),
            ("0x00000200", "0x00000800"),
        )
        self.assertEqual(len(alternatives[0]["anchors"]), 4)

    def test_boundary_sequence_revalidates_order_and_existing_ownership(self):
        value = boundary_sequence()
        value["functions"][2]["source_address"] = "0x00001010"
        unit = {"code_bytes": 0x800, "anchors": [], "boundary_sequences": [value]}
        self.assertEqual(adapter.build_alternatives(unit, {}), [])
        value = boundary_sequence()
        unit["boundary_sequences"] = [value]
        occupied = {"Other.cpp": ["\t.text start:0x00000400 end:0x00000500"]}
        self.assertEqual(adapter.build_alternatives(unit, occupied), [])

    def test_distant_anchors_stay_separate_and_contiguous_anchors_add_a_run(self):
        unit = {
            "anchors": [
                anchor(0x100, 0x180),
                anchor(0x180, 0x280),
                anchor(0x400, 0x500),
            ]
        }
        alternatives = adapter.build_alternatives(unit, {})
        ranges = [(item["start"], item["end"]) for item in alternatives]
        self.assertEqual(
            ranges[:3],
            [
                ("0x00000180", "0x00000280"),
                ("0x00000400", "0x00000500"),
                ("0x00000100", "0x00000180"),
            ],
        )
        self.assertIn(("0x00000100", "0x00000280"), ranges)
        self.assertNotIn(("0x00000100", "0x00000500"), ranges)

    def test_an_overlapping_anchor_does_not_discard_a_free_alternative(self):
        unit = {"anchors": [anchor(0x100, 0x200), anchor(0x400, 0x500)]}
        existing = {"other.cpp": ["\t.text start:0x00000180 end:0x00000280"]}
        self.assertEqual(
            [
                (a["start"], a["end"])
                for a in adapter.build_alternatives(unit, existing)
            ],
            [("0x00000400", "0x00000500")],
        )

    def test_layout_shift_evidence_is_only_proposed_as_a_corroborated_group(self):
        unit = {
            "code_bytes": 0x600,
            "anchors": [],
            "layout_shift_anchors": [
                layout_anchor(0x100, 0x180),
                layout_anchor(0x240, 0x340),
            ],
        }
        alternatives = adapter.build_alternatives(unit, {})
        self.assertEqual(len(alternatives), 1)
        self.assertEqual(
            (alternatives[0]["start"], alternatives[0]["end"]),
            ("0x00000100", "0x00000340"),
        )
        self.assertEqual(alternatives[0]["evidence"], "this-layout-shift")
        self.assertEqual(len(alternatives[0]["anchors"]), 2)

    def test_layout_shift_evidence_rejects_singletons_and_disagreement(self):
        singleton = {
            "code_bytes": 0x600,
            "anchors": [],
            "layout_shift_anchors": [layout_anchor(0x100, 0x180)],
        }
        self.assertEqual(adapter.build_alternatives(singleton, {}), [])
        disagreement = {
            "code_bytes": 0x600,
            "anchors": [],
            "layout_shift_anchors": [
                layout_anchor(0x100, 0x180),
                layout_anchor(0x240, 0x340, breakpoint=0x100),
            ],
        }
        self.assertEqual(adapter.build_alternatives(disagreement, {}), [])
        reversed_source_order = {
            "code_bytes": 0x600,
            "anchors": [],
            "layout_shift_anchors": [
                layout_anchor(0x100, 0x180, source_address=0x2000),
                layout_anchor(0x240, 0x340, source_address=0x1800),
            ],
        }
        self.assertEqual(adapter.build_alternatives(reversed_source_order, {}), [])

    def test_zero_objdiff_gain_is_accepted_with_extracted_link_input(self):
        with tempfile.TemporaryDirectory() as temporary:
            ctx = FakeContext(Path(temporary))
            value = candidate()
            result = adapter.evaluate(ctx, [value])
            self.assertEqual(result["accepted"], [value])
            self.assertEqual(
                result["selected"], {"A.cpp": value["alternatives"][0]["id"]}
            )
            self.assertEqual(result["report"]["measures"]["matched_code"], 10)

    def test_rejected_first_alternative_falls_back_without_widening(self):
        with tempfile.TemporaryDirectory() as temporary:
            ctx = FakeContext(Path(temporary), reject_first=True)
            value = candidate()
            result = adapter.evaluate(ctx, [value])
            self.assertEqual(
                result["selected"], {"A.cpp": value["alternatives"][1]["id"]}
            )
            self.assertEqual(result["events"][0]["category"], "retail-mismatch")

    def test_existing_unit_regression_rejects_every_alternative(self):
        with tempfile.TemporaryDirectory() as temporary:
            ctx = FakeContext(Path(temporary), regress=True)
            value = candidate()
            result = adapter.evaluate(ctx, [value])
            self.assertEqual(result["accepted"], [])
            self.assertEqual(result["deferred"], [value])

    def test_source_link_enablement_rejects_coverage(self):
        with tempfile.TemporaryDirectory() as temporary:
            value = candidate()
            result = adapter.evaluate(
                FakeContext(Path(temporary), source_enabled=True), [value]
            )
            self.assertEqual(result["accepted"], [])
            self.assertTrue(
                all(
                    event["category"] == "source-linkage-violation"
                    for event in result["events"]
                )
            )

    def test_calibration_scores_anchor_and_complete_range_ownership(self):
        value = candidate()
        oracle = {"A.cpp": ["\t.text start:0x00000200 end:0x00000500"]}
        owners = {(".text", "0x00000200"): "A.cpp"}
        record = score_candidate(value, oracle, owners)
        self.assertEqual(record["partition"], partition("A.cpp"))
        self.assertTrue(
            all(item["state"] == "correct" for item in record["alternatives"])
        )
        self.assertEqual(record["anchors"][0]["state"], "correct")
        measures = summarize([record])
        self.assertEqual(sum(item["tus"] for item in measures.values()), 1)
        partition_measures = measures[record["partition"]]
        self.assertEqual(partition_measures["ranges_unknown"], 0)
        self.assertEqual(partition_measures["ranges_incorrect"], 0)

    def test_calibration_separates_unowned_ranges_from_cross_unit_errors(self):
        value = candidate()
        unknown = score_candidate(value, {}, {})
        self.assertTrue(
            all(item["state"] == "unknown" for item in unknown["alternatives"])
        )
        other = {"B.cpp": ["\t.text start:0x00000200 end:0x00000300"]}
        incorrect = score_candidate(value, other, {})
        self.assertEqual(incorrect["alternatives"][0]["state"], "incorrect")

    def test_calibration_uses_the_explicit_oracle_split(self):
        layout = [
            {"section": ".text", "address": "0x00000200"},
            {"section": ".text", "address": "0x00000400"},
        ]
        blocks = {"A.cpp": ["\t.text start:0x00000200 end:0x00000300"]}
        self.assertEqual(
            ownership_at_layout(layout, blocks),
            {(".text", "0x00000200"): "A.cpp", (".text", "0x00000400"): None},
        )

    def test_summary_separates_metrics_and_reports_deferred_build_failure(self):
        value = candidate()
        prepared = {
            "candidates": [value],
            "inventory": {
                "policy": {"version": 1},
                "source": "S",
                "target": "T",
                "source_units": 2,
                "baseline_represented": 1,
                "dispositions": {"A.cpp": "eligible"},
            },
        }
        result = {
            "accepted": [],
            "deferred": [value],
            "selected": {},
            "events": [
                {"unit": "A.cpp", "status": "rejected", "category": "retail-mismatch"}
            ],
            "baseline": {"matched_code": "10", "complete_code": "4"},
            "report": {"measures": {"matched_code": "10", "complete_code": "4"}},
            "validation": adapter.VALIDATION,
        }
        report = adapter.summary(prepared, result)
        self.assertEqual(report["dispositions"], {"A.cpp": "build-failure"})
        self.assertEqual(
            report["metrics"]["objdiff_matching"],
            {"baseline_code_bytes": 10, "final_code_bytes": 10},
        )
        self.assertEqual(report["source"], "S")

    def test_toolchain_path_alone_is_not_a_compilation_diagnostic(self):
        error = subprocess.CalledProcessError(1, ["configure", "--compilers", "tools"])
        self.assertEqual(adapter._failure_category(error, ""), "unknown-failure")


if __name__ == "__main__":
    unittest.main()
