//! Building coverage evidence by hand, for tests that need the policy's input
//! without two analysable binaries to derive it from.
//!
//! A [`CoverageAnchor`] carries two dozen fields, nearly all of them gates the
//! policy checks before it will believe anything. Written out as JSON in a test
//! fixture, one wrong flag produces a report that parses, proposes nothing, and
//! makes the test pass for the wrong reason — so this builds them from types,
//! with every gate satisfied by default and only the interesting parts named at
//! the call site.
//!
//! This is test scaffolding that happens to live in the library, because the
//! integration tests need it and they compile against the library's public
//! surface. It analyses nothing and is never reached by a migration.

use crate::analysis::{
    coverage::{
        AdjacentOwnerSupport, AdjacentOwnerTransition, COVERAGE_SCHEMA, CoverageAnchor,
        CoverageReport, CoverageUnit, SequenceFunction, TargetFunction, current_policy,
    },
    matching::{MatchMethod, MatchTier},
    ownership::{
        AttributionOrigin, CandidateSequence, EdgeEvidence, FunctionAttribution, FunctionLocation,
        IDENTIFICATION_SCHEMA, IdentificationBasis, IdentificationConfidence, IdentificationReport,
        SourceFunction, SourceFunctionObservation, TargetFunctionObservation, UnitIdentification,
    },
};

fn hex(value: u32) -> String { format!("0x{value:08X}") }

/// One function matched between the versions, eligible by every gate.
///
/// The defaults are the *believable* case — a uniquely matched, non-weak,
/// non-template function of known extent, wholly owned by an explicit source
/// unit, with identical body and relocations. Anything a test wants to be
/// unbelievable it should say so explicitly.
pub fn anchor(source_name: &str, target: u32, end: u32) -> CoverageAnchor {
    CoverageAnchor {
        source_name: source_name.to_string(),
        source_address: hex(target),
        target_name: String::new(),
        target_address: hex(target),
        target_end: hex(end),
        section: ".text".to_string(),
        size: end - target,
        source_local: false,
        target_local: false,
        source_weak: false,
        target_weak: false,
        source_extent_known: true,
        target_extent_known: true,
        source_unit_explicit: true,
        source_unit_wholly_owned: true,
        template_instantiation: false,
        unique_source: true,
        unique_target: true,
        normalized_body_equal: true,
        relocation_layout_equal: true,
        required_alignment: 4,
        existing_target_owner: None,
        existing_owner_autogenerated: false,
        eligible: true,
        reasons: Vec::new(),
    }
}

/// The same anchor, present in the inventory but not yet usable.
///
/// Evidence arriving must not make a source unit appear to grow: the unit's
/// code is the same code it always was, and all that changed is whether the
/// policy will believe a match for it. A test staging evidence over several
/// rounds therefore lists every anchor from the start and withholds the gate,
/// rather than adding the anchor later.
pub fn withheld(mut anchor: CoverageAnchor, reason: &str) -> CoverageAnchor {
    anchor.eligible = false;
    anchor.normalized_body_equal = false;
    anchor.reasons.push(reason.to_string());
    anchor
}

/// Functions of `size` bytes tiling `start..end`, named `prefix0`, `prefix1`…
pub fn run(prefix: &str, start: u32, end: u32, size: u32) -> Vec<CoverageAnchor> {
    (start..end)
        .step_by(size as usize)
        .enumerate()
        .map(|(index, address)| anchor(&format!("{prefix}{index}"), address, address + size))
        .collect()
}

/// The same anchors, recorded as currently lying inside `owner`'s split.
pub fn owned_by(anchors: Vec<CoverageAnchor>, owner: &str) -> Vec<CoverageAnchor> {
    anchors
        .into_iter()
        .map(|mut anchor| {
            anchor.existing_target_owner = Some(owner.to_string());
            anchor
        })
        .collect()
}

fn sequence(anchors: &[CoverageAnchor]) -> Vec<SequenceFunction> {
    anchors
        .iter()
        .map(|anchor| SequenceFunction {
            source_name: anchor.source_name.clone(),
            source_address: anchor.source_address.clone(),
            target_address: anchor.target_address.clone(),
            target_end: anchor.target_end.clone(),
            size: anchor.size,
            tier: "confident".into(),
            method: "exact-hash".into(),
            confidence: 1.0,
            primary: true,
        })
        .collect()
}

/// A candidate whose functions occupy the head of the next unit's split: the
/// next unit gives up `original.0..claim.1` and keeps the rest.
///
/// `candidate` and `owner` are the two units' `.text` functions, which must
/// tile `claim` and `claim.1..original.1` respectively — the same functions
/// the units' own anchors describe, so that the observations agree.
pub fn next_prefix_transition(
    previous: &str,
    next: &str,
    claim: (u32, u32),
    original: (u32, u32),
    candidate: &[CoverageAnchor],
    owner: &[CoverageAnchor],
) -> AdjacentOwnerTransition {
    let bytes = claim.1 - claim.0;
    let kept = original.1 - claim.1;
    AdjacentOwnerTransition {
        section: ".text".into(),
        side: "next-prefix".into(),
        target_start: hex(claim.0),
        target_end: hex(claim.1),
        target_bytes: bytes,
        source_bytes: bytes,
        previous_unit: previous.into(),
        next_unit: next.into(),
        source_functions: candidate.len() as u32,
        aligned_functions: candidate.len() as u32,
        strong_functions: candidate.len() as u32,
        direct_anchors: candidate.len() as u32,
        match_ratio: 1.0,
        target_coverage: 1.0,
        best_alignment_score: 10.0,
        second_alignment_score: 1.0,
        alignment_margin: 0.9,
        size_delta: 0.0,
        owner: AdjacentOwnerSupport {
            unit: next.into(),
            original_start: hex(original.0),
            original_end: hex(original.1),
            revised_start: hex(claim.1),
            revised_end: hex(original.1),
            source_bytes: kept,
            target_bytes: kept,
            size_delta: 0.0,
            source_functions: owner.len() as u32,
            aligned_functions: owner.len() as u32,
            target_functions: owner.len() as u32,
            strong_functions: owner.len() as u32,
            functions: sequence(owner),
            gap_helpers: Vec::new(),
        },
        functions: sequence(candidate),
        eligible: true,
        reasons: Vec::new(),
    }
}

/// One source unit and the functions matched inside it.
pub fn unit(name: &str, anchors: Vec<CoverageAnchor>) -> CoverageUnit {
    CoverageUnit {
        name: name.to_string(),
        code_bytes: anchors.iter().map(|a| u64::from(a.size)).sum(),
        autogenerated: false,
        source_functions: anchors.len() as u32,
        no_exact_target_body: 0,
        name_only_candidates: 0,
        ambiguous_exact_bodies: 0,
        anchors,
        layout_shift_candidates: 0,
        layout_shift_anchors: Vec::new(),
        boundary_sequences: Vec::new(),
        adjacent_owner_transitions: Vec::new(),
        required_extracts: Vec::new(),
    }
}

/// A whole report, at the schema and policy the stage will insist on.
pub fn report(source: &str, target: &str, units: Vec<CoverageUnit>) -> CoverageReport {
    let layout: Vec<TargetFunction> = units
        .iter()
        .flat_map(|unit| {
            unit.anchors.iter().map(|a| TargetFunction {
                address: a.target_address.clone(),
                end: a.target_end.clone(),
                section: a.section.clone(),
                current_owner: None,
                owner_autogenerated: false,
            })
        })
        .collect();
    let attributions: Vec<FunctionAttribution> = units
        .iter()
        .flat_map(|unit| {
            unit.anchors.iter().enumerate().map(|(index, anchor)| FunctionAttribution {
                id: format!("{}:{index}:{}", unit.name, anchor.target_address),
                target: FunctionLocation {
                    module: "main".into(),
                    section: anchor.section.clone(),
                    address: anchor.target_address.clone(),
                    end: anchor.target_end.clone(),
                },
                source: SourceFunction {
                    name: anchor.source_name.clone(),
                    unit: unit.name.clone(),
                    module: "main".into(),
                    section: anchor.section.clone(),
                    address: anchor.source_address.clone(),
                    end: hex(u32::from_str_radix(
                        anchor.source_address.trim_start_matches("0x"),
                        16,
                    )
                    .unwrap()
                        + anchor.size),
                },
                method: MatchMethod::ExactHash,
                tier: MatchTier::Confident,
                confidence: 1.0,
                evidence_count: 1,
                origin: AttributionOrigin::NormalizedBody,
                // An anchor withheld by its body is not independent evidence
                // in the identification either: both describe one match.
                distinctive_body: anchor.normalized_body_equal,
                unique_exact_body: anchor.normalized_body_equal,
                binary_supported: true,
                independent: true,
                ambiguous: false,
                competing: None,
                source_weak: anchor.source_weak,
                target_weak: anchor.target_weak,
                template_instantiation: anchor.template_instantiation,
                current_target_owner: anchor.existing_target_owner.clone(),
                evidence: Vec::new(),
            })
        })
        .collect();
    let identifications = IdentificationReport {
        schema: IDENTIFICATION_SCHEMA,
        source: source.to_string(),
        target: target.to_string(),
        attributions: attributions.clone(),
        source_functions: attributions
            .iter()
            .map(|item| SourceFunctionObservation {
                name: item.source.name.clone(),
                unit: item.source.unit.clone(),
                module: item.source.module.clone(),
                section: item.source.section.clone(),
                address: item.source.address.clone(),
                end: item.source.end.clone(),
                normalized_body_sha256: None,
                weak: item.source_weak,
            })
            .collect(),
        target_functions: layout
            .iter()
            .enumerate()
            .map(|(index, function)| TargetFunctionObservation {
                name: format!("fixture_target_{index}"),
                module: "main".into(),
                section: function.section.clone(),
                address: function.address.clone(),
                end: function.end.clone(),
                current_owner: function.current_owner.clone(),
                owner_autogenerated: function.owner_autogenerated,
                callers: Vec::new(),
                normalized_body_sha256: None,
                weak: false,
            })
            .collect(),
        helper_families: Vec::new(),
        unresolved_target_clusters: Vec::new(),
        units: units
            .iter()
            .map(|unit| {
                let matched = unit.anchors.len() as u32;
                let mut identification =
                    UnitIdentification::absent(&unit.name, unit.source_functions);
                identification.autogenerated = unit.autogenerated;
                identification.matched_functions = matched;
                identification.strong_functions = matched;
                identification.binary_functions = matched;
                identification.independently_supported_functions = matched;
                identification.confidence = if matched >= 2 {
                    IdentificationConfidence::Corroborated
                } else if matched == 1 {
                    IdentificationConfidence::Tentative
                } else {
                    IdentificationConfidence::Absent
                };
                identification.basis = if matched == 0 {
                    IdentificationBasis::None
                } else {
                    IdentificationBasis::Binary
                };
                if matched > 0 {
                    identification.boundary_blockers.clear();
                    identification.application_blockers.clear();
                }
                let ids: Vec<String> = attributions
                    .iter()
                    .filter(|item| item.source.unit == unit.name)
                    .map(|item| item.id.clone())
                    .collect();
                if !ids.is_empty() {
                    let first = attributions.iter().find(|item| item.id == ids[0]).unwrap();
                    let last = attributions
                        .iter()
                        .rev()
                        .find(|item| item.source.unit == unit.name)
                        .unwrap();
                    identification.candidates.push(CandidateSequence {
                        module: "main".into(),
                        source_section: first.source.section.clone(),
                        section: first.target.section.clone(),
                        start: first.target.address.clone(),
                        end: last.target.end.clone(),
                        attribution_ids: ids,
                        matched_members: matched,
                        target_functions_in_envelope: matched,
                        contiguous_target_members: true,
                        left_source_edge_observed: true,
                        right_source_edge_observed: true,
                        left_target_edge: EdgeEvidence {
                            supported: true,
                            reason: "fixture boundary".into(),
                            adjacent_attribution_id: None,
                        },
                        right_target_edge: EdgeEvidence {
                            supported: true,
                            reason: "fixture boundary".into(),
                            adjacent_attribution_id: None,
                        },
                        unexplained_target_members: Vec::new(),
                        current_owners: Vec::new(),
                    });
                    identification.evidence = identification.candidates[0].attribution_ids.clone();
                }
                identification
            })
            .collect(),
    };
    CoverageReport {
        schema: COVERAGE_SCHEMA,
        policy: current_policy(),
        source: source.to_string(),
        target: target.to_string(),
        mask: Default::default(),
        identifications,
        source_units: units,
        target_layout: layout,
    }
}
