//! Building coverage evidence by hand, for tests that need the policy's input
//! without two analysable binaries to derive it from.
//!
//! A [`CoverageAnchor`] carries two dozen fields, nearly all of them gates the
//! policy checks before it will believe anything. Written out as JSON in a test
//! fixture, one wrong flag produces a report that parses, proposes nothing, and
//! makes the test pass for the wrong reason — so this builds them from types,
//! with every gate satisfied by default and only the interesting parts named at
//! the call site.
//!
//! This is test scaffolding that happens to live in the library, because the
//! integration tests need it and they compile against the library's public
//! surface. It analyses nothing and is never reached by a migration.

use crate::analysis::{
    coverage::{
        COVERAGE_SCHEMA, CoverageAnchor, CoverageReport, CoverageUnit, TargetFunction,
        current_policy,
    },
    ownership::{
        IDENTIFICATION_SCHEMA, IdentificationBasis, IdentificationConfidence, IdentificationReport,
        UnitIdentification,
    },
};

fn hex(value: u32) -> String { format!("0x{value:08X}") }

/// One function matched between the versions, eligible by every gate.
///
/// The defaults are the *believable* case — a uniquely matched, non-weak,
/// non-template function of known extent, wholly owned by an explicit source
/// unit, with identical body and relocations. Anything a test wants to be
/// unbelievable it should say so explicitly.
pub fn anchor(source_name: &str, target: u32, end: u32) -> CoverageAnchor {
    CoverageAnchor {
        source_name: source_name.to_string(),
        source_address: hex(target),
        target_name: String::new(),
        target_address: hex(target),
        target_end: hex(end),
        section: ".text".to_string(),
        size: end - target,
        source_local: false,
        target_local: false,
        source_weak: false,
        target_weak: false,
        source_extent_known: true,
        target_extent_known: true,
        source_unit_explicit: true,
        source_unit_wholly_owned: true,
        template_instantiation: false,
        unique_source: true,
        unique_target: true,
        normalized_body_equal: true,
        relocation_layout_equal: true,
        required_alignment: 4,
        existing_target_owner: None,
        existing_owner_autogenerated: false,
        eligible: true,
        reasons: Vec::new(),
    }
}

/// The same anchor, present in the inventory but not yet usable.
///
/// Evidence arriving must not make a source unit appear to grow: the unit's
/// code is the same code it always was, and all that changed is whether the
/// policy will believe a match for it. A test staging evidence over several
/// rounds therefore lists every anchor from the start and withholds the gate,
/// rather than adding the anchor later.
pub fn withheld(mut anchor: CoverageAnchor, reason: &str) -> CoverageAnchor {
    anchor.eligible = false;
    anchor.reasons.push(reason.to_string());
    anchor
}

/// One source unit and the functions matched inside it.
pub fn unit(name: &str, anchors: Vec<CoverageAnchor>) -> CoverageUnit {
    CoverageUnit {
        name: name.to_string(),
        code_bytes: anchors.iter().map(|a| u64::from(a.size)).sum(),
        autogenerated: false,
        source_functions: anchors.len() as u32,
        no_exact_target_body: 0,
        name_only_candidates: 0,
        ambiguous_exact_bodies: 0,
        anchors,
        layout_shift_candidates: 0,
        layout_shift_anchors: Vec::new(),
        boundary_sequences: Vec::new(),
        adjacent_owner_transitions: Vec::new(),
        required_extracts: Vec::new(),
    }
}

/// A whole report, at the schema and policy the stage will insist on.
pub fn report(source: &str, target: &str, units: Vec<CoverageUnit>) -> CoverageReport {
    let layout = units
        .iter()
        .flat_map(|unit| {
            unit.anchors.iter().map(|a| TargetFunction {
                address: a.target_address.clone(),
                end: a.target_end.clone(),
                section: a.section.clone(),
                current_owner: None,
                owner_autogenerated: false,
            })
        })
        .collect();
    let identifications = IdentificationReport {
        schema: IDENTIFICATION_SCHEMA,
        source: source.to_string(),
        target: target.to_string(),
        attributions: Vec::new(),
        units: units
            .iter()
            .map(|unit| {
                let matched = unit.anchors.len() as u32;
                let mut identification =
                    UnitIdentification::absent(&unit.name, unit.source_functions);
                identification.autogenerated = unit.autogenerated;
                identification.matched_functions = matched;
                identification.strong_functions = matched;
                identification.binary_functions = matched;
                identification.independently_supported_functions = matched;
                identification.confidence = if matched >= 2 {
                    IdentificationConfidence::Corroborated
                } else if matched == 1 {
                    IdentificationConfidence::Tentative
                } else {
                    IdentificationConfidence::Absent
                };
                identification.basis = if matched == 0 {
                    IdentificationBasis::None
                } else {
                    IdentificationBasis::Binary
                };
                if matched > 0 {
                    identification.boundary_blockers.clear();
                    identification.application_blockers.clear();
                }
                identification
            })
            .collect(),
    };
    CoverageReport {
        schema: COVERAGE_SCHEMA,
        policy: current_policy(),
        source: source.to_string(),
        target: target.to_string(),
        mask: Default::default(),
        identifications,
        source_units: units,
        target_layout: layout,
    }
}
