//! Binary-only helper hypotheses and target clusters with no source TU.
//!
//! These records describe evidence, not emitted ownership. In particular, a
//! source definition in a body family says the unit can emit that body; it does
//! not say which unit supplied a target occurrence to the linker.

use std::collections::{BTreeMap, BTreeSet};

use decomp_toolkit::obj::ObjInfo;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::analysis::{
    callgraph::FunctionNode,
    fingerprint::normalized_body,
    object_evidence::CompiledDefinition,
    ownership::{FunctionAttribution, SourceFunctionObservation, TargetFunctionObservation},
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceDefinition {
    pub name: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
    pub unit: String,
    pub weak: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TargetOccurrence {
    pub name: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_owner: Option<String>,
    pub weak: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum HelperSignal {
    DuplicateSourceBody,
    DuplicateTargetBody,
    WeakDefinition,
    StaticInitializerName,
    DestructorShapedName,
    CompiledObjectBody,
    DuplicateCompiledBody,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HelperFamily {
    /// Stable across a symbol rename or changed split map.
    pub id: String,
    pub normalized_body_sha256: String,
    /// A definition is available from this source TU; it is not proof that the
    /// TU emitted any particular target copy.
    pub source_definitions: Vec<SourceDefinition>,
    pub target_occurrences: Vec<TargetOccurrence>,
    /// Exact body present in an existing object mapped to the target version.
    /// This does not prove a fresh build or linker emission of the retail copy.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub compiled_definitions: Vec<CompiledDefinition>,
    pub signals: Vec<HelperSignal>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClusterBoundary {
    pub function_address: String,
    pub current_owner: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attribution_id: Option<String>,
    pub independently_attributed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClusterMember {
    pub name: String,
    pub address: String,
    pub end: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub autogenerated_split: Option<String>,
}

/// A bounded inventory gap, not a proposed split or guessed filename. One
/// cluster can still contain more than one future source TU.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UnresolvedTargetCluster {
    pub id: String,
    pub module: String,
    pub section: String,
    pub start: String,
    pub end: String,
    pub members: Vec<ClusterMember>,
    pub left: ClusterBoundary,
    pub right: ClusterBoundary,
}

/// A collision-resistant key for an exact normalized body. Unknown function
/// sizes and one-instruction stubs are withheld from family evidence.
pub fn body_digest(obj: &ObjInfo, node: &FunctionNode) -> Option<String> {
    if !obj.symbols[node.symbol].size_known || node.size < 8 {
        return None;
    }
    let body = normalized_body(obj, node);
    (body.len() == node.size as usize).then(|| format!("{:x}", Sha256::digest(body)))
}

/// Regenerate family summaries from the per-function digest inventory. The
/// summaries supplied by a saved report are never taken as policy input.
pub fn families(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, &[], true, false)
}

pub fn families_with_compiled(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    compiled: &[CompiledDefinition],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, compiled, true, false)
}

/// Schema 7 uses the complete object inventory. Ordinary, already-owned
/// functions must not become helper families merely because they also compile.
pub fn families_with_inventory(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    compiled: &[CompiledDefinition],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, compiled, true, true)
}

/// Preserve schema 4's target-name-only classifier when loading its saved
/// references. Schema 5 also recognizes source names when target names were
/// stripped, and therefore has a different canonical digest.
pub fn families_schema_4(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, &[], false, false)
}

#[derive(Default)]
struct FamilyMembers {
    source_definitions: Vec<SourceDefinition>,
    target_occurrences: Vec<TargetOccurrence>,
    compiled_definitions: Vec<CompiledDefinition>,
}

fn families_with_name_scope(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    compiled: &[CompiledDefinition],
    source_generated_names: bool,
    complete_compiled: bool,
) -> Vec<HelperFamily> {
    let unresolved_hashes: BTreeSet<&str> = target
        .iter()
        .filter(|function| function.current_owner.is_none() || function.owner_autogenerated)
        .filter_map(|function| function.normalized_body_sha256.as_deref())
        .collect();
    let mut groups: BTreeMap<&str, FamilyMembers> = BTreeMap::new();
    for function in source {
        let Some(hash) = function.normalized_body_sha256.as_deref() else { continue };
        groups.entry(hash).or_default().source_definitions.push(SourceDefinition {
            name: function.name.clone(),
            module: function.module.clone(),
            section: function.section.clone(),
            address: function.address.clone(),
            end: function.end.clone(),
            unit: function.unit.clone(),
            weak: function.weak,
        });
    }
    for function in target {
        let Some(hash) = function.normalized_body_sha256.as_deref() else { continue };
        groups.entry(hash).or_default().target_occurrences.push(TargetOccurrence {
            name: function.name.clone(),
            module: function.module.clone(),
            section: function.section.clone(),
            address: function.address.clone(),
            end: function.end.clone(),
            current_owner: function.current_owner.clone(),
            weak: function.weak,
        });
    }
    for function in compiled {
        groups
            .entry(&function.normalized_body_sha256)
            .or_default()
            .compiled_definitions
            .push(function.clone());
    }
    groups
        .into_iter()
        .filter_map(|(hash, members)| {
            let FamilyMembers {
                mut source_definitions,
                mut target_occurrences,
                mut compiled_definitions,
            } = members;
            if target_occurrences.is_empty() {
                return None;
            }
            source_definitions.sort_by(|left, right| {
                (&left.module, &left.section, &left.address, &left.name).cmp(&(
                    &right.module,
                    &right.section,
                    &right.address,
                    &right.name,
                ))
            });
            target_occurrences.sort_by(|left, right| {
                (&left.module, &left.section, &left.address, &left.name).cmp(&(
                    &right.module,
                    &right.section,
                    &right.address,
                    &right.name,
                ))
            });
            compiled_definitions.sort_by(|left, right| {
                (&left.unit, &left.section, &left.address, &left.name).cmp(&(
                    &right.unit,
                    &right.section,
                    &right.address,
                    &right.name,
                ))
            });
            let defining_units: BTreeSet<&str> =
                source_definitions.iter().map(|item| item.unit.as_str()).collect();
            let compiled_units: BTreeSet<&str> =
                compiled_definitions.iter().map(|item| item.unit.as_str()).collect();
            let mut signals = Vec::new();
            if defining_units.len() > 1 {
                signals.push(HelperSignal::DuplicateSourceBody);
            }
            if target_occurrences.len() > 1 {
                signals.push(HelperSignal::DuplicateTargetBody);
            }
            if complete_compiled && compiled_units.len() > 1 {
                signals.push(HelperSignal::DuplicateCompiledBody);
            }
            if source_definitions.iter().any(|item| item.weak)
                || target_occurrences.iter().any(|item| item.weak)
                || complete_compiled && compiled_definitions.iter().any(|item| item.weak)
            {
                signals.push(HelperSignal::WeakDefinition);
            }
            if (source_generated_names
                && source_definitions.iter().any(|item| {
                    item.name.starts_with("__sinit_") || item.name.starts_with("__sti__")
                }))
                || target_occurrences.iter().any(|item| {
                    item.name.starts_with("__sinit_") || item.name.starts_with("__sti__")
                })
                || complete_compiled
                    && compiled_definitions.iter().any(|item| {
                        item.name.starts_with("__sinit_") || item.name.starts_with("__sti__")
                    })
            {
                signals.push(HelperSignal::StaticInitializerName);
            }
            // A destructor-shaped symbol may denote explicit source or a
            // compiler-emitted tail. The signal deliberately makes no choice.
            if (source_generated_names
                && source_definitions.iter().any(|item| item.name.starts_with("__dt__")))
                || target_occurrences.iter().any(|item| item.name.starts_with("__dt__"))
                || complete_compiled
                    && compiled_definitions.iter().any(|item| item.name.starts_with("__dt__"))
            {
                signals.push(HelperSignal::DestructorShapedName);
            }
            if !compiled_definitions.is_empty()
                && (!complete_compiled || !signals.is_empty() || unresolved_hashes.contains(hash))
            {
                signals.push(HelperSignal::CompiledObjectBody);
            }
            (!signals.is_empty()).then(|| HelperFamily {
                id: format!("normalized-body:{hash}"),
                normalized_body_sha256: hash.into(),
                source_definitions,
                target_occurrences,
                compiled_definitions,
                signals,
            })
        })
        .collect()
}

fn boundary(
    function: &TargetFunctionObservation,
    attributions: &BTreeMap<(&str, &str, &str), &FunctionAttribution>,
) -> Option<ClusterBoundary> {
    let current_owner = function.current_owner.clone()?;
    if function.owner_autogenerated {
        return None;
    }
    let attribution = attributions.get(&(
        function.module.as_str(),
        function.section.as_str(),
        function.address.as_str(),
    ));
    Some(ClusterBoundary {
        function_address: function.address.clone(),
        current_owner,
        attribution_id: attribution.map(|item| item.id.clone()),
        independently_attributed: attribution.is_some_and(|item| item.independent),
    })
}

/// Inventory maximal runs of unmatched, unowned target functions. Requiring
/// distinct represented neighbours avoids relabelling one unit's ordinary
/// unplaced helper as a missing TU. The neighbours are observations, not proof
/// of the cluster's exact source identity or final end boundary.
pub fn unresolved_clusters(
    functions: &[TargetFunctionObservation],
    attributions: &[FunctionAttribution],
) -> Vec<UnresolvedTargetCluster> {
    let by_target: BTreeMap<(&str, &str, &str), &FunctionAttribution> = attributions
        .iter()
        .map(|item| {
            (
                (
                    item.target.module.as_str(),
                    item.target.section.as_str(),
                    item.target.address.as_str(),
                ),
                item,
            )
        })
        .collect();
    let mut ordered: Vec<&TargetFunctionObservation> = functions.iter().collect();
    ordered.sort_by_key(|item| (&item.module, &item.section, &item.address));
    let orphan = |item: &TargetFunctionObservation| {
        (item.current_owner.is_none() || item.owner_autogenerated)
            && !by_target.contains_key(&(
                item.module.as_str(),
                item.section.as_str(),
                item.address.as_str(),
            ))
    };
    let mut clusters = Vec::new();
    let mut index = 0;
    while index < ordered.len() {
        if !orphan(ordered[index]) {
            index += 1;
            continue;
        }
        let start = index;
        let module = &ordered[index].module;
        let section = &ordered[index].section;
        while index < ordered.len()
            && &ordered[index].module == module
            && &ordered[index].section == section
            && orphan(ordered[index])
        {
            index += 1;
        }
        if index - start < 2 || start == 0 || index == ordered.len() {
            continue;
        }
        let left = ordered[start - 1];
        let right = ordered[index];
        if &left.module != module
            || &left.section != section
            || &right.module != module
            || &right.section != section
        {
            continue;
        }
        let (Some(left), Some(right)) = (boundary(left, &by_target), boundary(right, &by_target))
        else {
            continue;
        };
        if left.current_owner == right.current_owner {
            continue;
        }
        let first = ordered[start];
        let last = ordered[index - 1];
        clusters.push(UnresolvedTargetCluster {
            id: format!("unresolved:{}:{}:{}", module, section, first.address),
            module: module.clone(),
            section: section.clone(),
            start: first.address.clone(),
            end: last.end.clone(),
            members: ordered[start..index]
                .iter()
                .map(|item| ClusterMember {
                    name: item.name.clone(),
                    address: item.address.clone(),
                    end: item.end.clone(),
                    autogenerated_split: item
                        .owner_autogenerated
                        .then(|| item.current_owner.clone())
                        .flatten(),
                })
                .collect(),
            left,
            right,
        });
    }
    clusters
}

#[cfg(test)]
mod tests {
    use super::*;

    fn source(unit: &str, name: &str, address: &str, hash: &str) -> SourceFunctionObservation {
        let end = format!("0x{:08X}", u32::from_str_radix(&address[2..], 16).unwrap() + 0x20);
        SourceFunctionObservation {
            name: name.into(),
            unit: unit.into(),
            module: "main".into(),
            section: ".text".into(),
            address: address.into(),
            end,
            normalized_body_sha256: Some(hash.into()),
            weak: true,
        }
    }

    fn target(
        name: &str,
        address: &str,
        owner: Option<&str>,
        hash: Option<&str>,
    ) -> TargetFunctionObservation {
        let end = format!("0x{:08X}", u32::from_str_radix(&address[2..], 16).unwrap() + 0x20);
        TargetFunctionObservation {
            name: name.into(),
            module: "main".into(),
            section: ".text".into(),
            address: address.into(),
            end,
            current_owner: owner.map(str::to_string),
            owner_autogenerated: false,
            callers: Vec::new(),
            normalized_body_sha256: hash.map(str::to_string),
            weak: false,
        }
    }

    #[test]
    fn duplicate_definitions_are_availability_not_an_emitted_owner() {
        let hash = "a".repeat(64);
        let families = families(
            &[
                source("A.cpp", "helper", "0x00001000", &hash),
                source("B.cpp", "helper", "0x00002000", &hash),
            ],
            &[target("fn_3000", "0x00003000", Some("A.cpp"), Some(&hash))],
        );
        assert_eq!(families.len(), 1);
        assert_eq!(families[0].signals, vec![
            HelperSignal::DuplicateSourceBody,
            HelperSignal::WeakDefinition
        ]);
        assert_eq!(families[0].source_definitions.len(), 2);
        assert_eq!(families[0].target_occurrences[0].current_owner.as_deref(), Some("A.cpp"));
    }

    #[test]
    fn bounded_orphan_run_has_no_invented_source_tu() {
        let mut functions = [
            target("left", "0x80356944", Some("Kyoto/CFrameDelayedKiller.cpp"), None),
            target("fn_80356EDC", "0x80356EDC", Some("auto_80356EDC"), None),
            target("fn_80356F30", "0x80356F30", Some("auto_80356EDC"), None),
            target("right", "0x80357064", Some("dolphin/ai.c"), None),
        ];
        functions[1].owner_autogenerated = true;
        functions[2].owner_autogenerated = true;
        let clusters = unresolved_clusters(&functions, &[]);
        assert_eq!(clusters.len(), 1);
        assert_eq!(clusters[0].start, "0x80356EDC");
        assert_eq!(clusters[0].members.len(), 2);
        assert_eq!(clusters[0].members[0].autogenerated_split.as_deref(), Some("auto_80356EDC"));
        assert!(
            !serde_json::to_string(&clusters[0]).unwrap().contains("CTimeRemainderAndFraction")
        );
    }

    #[test]
    fn duplicate_target_bodies_are_visible_without_compiled_source_objects() {
        let hash = "b".repeat(64);
        let families = families(&[], &[
            target("fn_1000", "0x00001000", None, Some(&hash)),
            target("fn_2000", "0x00002000", None, Some(&hash)),
        ]);
        assert_eq!(families.len(), 1);
        assert!(families[0].source_definitions.is_empty());
        assert_eq!(families[0].signals, vec![HelperSignal::DuplicateTargetBody]);
    }

    #[test]
    fn a_destructor_shape_is_only_a_hypothesis() {
        let hash = "c".repeat(64);
        let families =
            families(&[], &[target("__dt__12CInstructionFv", "0x00001000", None, Some(&hash))]);
        assert_eq!(families[0].signals, vec![HelperSignal::DestructorShapedName]);
        assert!(families[0].source_definitions.is_empty());
    }

    #[test]
    fn a_source_generated_name_survives_an_opaque_target_symbol() {
        let hash = "d".repeat(64);
        let initializer_families = families(
            &[source("CPowerBomb.cpp", "__sinit_CPowerBomb_cpp", "0x00001000", &hash)],
            &[target("fn_80145158", "0x80145158", None, Some(&hash))],
        );
        assert_eq!(initializer_families.len(), 1);
        assert!(initializer_families[0].signals.contains(&HelperSignal::StaticInitializerName));

        let destructor_hash = "e".repeat(64);
        let destructor_families = families(
            &[source("CInstruction.cpp", "__dt__12CInstructionFv", "0x00002000", &destructor_hash)],
            &[target("fn_80202000", "0x80202000", None, Some(&destructor_hash))],
        );
        assert_eq!(destructor_families.len(), 1);
        assert!(destructor_families[0].signals.contains(&HelperSignal::DestructorShapedName));
    }

    #[test]
    fn compiled_availability_keeps_emitted_target_ownership_unknown() {
        let hash = "f".repeat(64);
        let compiled = CompiledDefinition {
            unit: "A.cpp".into(),
            name: "helper".into(),
            section: ".text".into(),
            address: "0x00000000".into(),
            end: "0x00000020".into(),
            normalized_body_sha256: hash.clone(),
            weak: true,
            object_sha256: "a".repeat(64),
        };
        let families =
            families_with_compiled(&[], &[target("fn_1000", "0x00001000", None, Some(&hash))], &[
                compiled,
            ]);
        assert_eq!(families.len(), 1);
        assert!(families[0].source_definitions.is_empty());
        assert_eq!(families[0].compiled_definitions[0].unit, "A.cpp");
        assert_eq!(families[0].target_occurrences[0].current_owner, None);
        assert_eq!(families[0].signals, [HelperSignal::CompiledObjectBody]);
    }

    #[test]
    fn complete_inventory_does_not_turn_every_owned_body_into_a_helper() {
        let hash = "a".repeat(64);
        let compiled = CompiledDefinition {
            unit: "A.cpp".into(),
            name: "ordinary".into(),
            section: ".text".into(),
            address: "0x00000000".into(),
            end: "0x00000020".into(),
            normalized_body_sha256: hash.clone(),
            weak: false,
            object_sha256: "b".repeat(64),
        };
        let owned = [target("ordinary", "0x00001000", Some("A.cpp"), Some(&hash))];
        assert!(families_with_inventory(&[], &owned, std::slice::from_ref(&compiled)).is_empty());
        // Schema 6's classifier must retain its original saved-report shape.
        assert_eq!(families_with_compiled(&[], &owned, std::slice::from_ref(&compiled)).len(), 1);

        let mut other = compiled.clone();
        other.unit = "B.cpp".into();
        let duplicated = families_with_inventory(&[], &owned, &[compiled.clone(), other]);
        assert_eq!(duplicated.len(), 1);
        assert!(duplicated[0].signals.contains(&HelperSignal::DuplicateCompiledBody));

        let mut weak = compiled;
        weak.weak = true;
        let weak_family = families_with_inventory(&[], &owned, &[weak]);
        assert_eq!(weak_family.len(), 1);
        assert!(weak_family[0].signals.contains(&HelperSignal::WeakDefinition));
    }
}
