//! Binary-only helper hypotheses and target clusters with no source TU.
//!
//! These records describe evidence, not emitted ownership. In particular, a
//! source definition in a body family says the unit can emit that body; it does
//! not say which unit supplied a target occurrence to the linker.

use std::collections::{BTreeMap, BTreeSet};

use decomp_toolkit::obj::ObjInfo;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::analysis::{
    callgraph::FunctionNode,
    fingerprint::normalized_body,
    object_evidence::CompiledDefinition,
    ownership::{FunctionAttribution, SourceFunctionObservation, TargetFunctionObservation},
};

// Frozen for identification schema 12. Changing a policy threshold must not
// reinterpret saved identification artifacts or invalidate their references.
const MAX_TAIL_HYPOTHESIS_GAP: u32 = 31;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceDefinition {
    pub name: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
    pub unit: String,
    pub weak: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TargetOccurrence {
    pub name: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_owner: Option<String>,
    pub weak: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum HelperSignal {
    DuplicateSourceBody,
    DuplicateTargetBody,
    WeakDefinition,
    StaticInitializerName,
    DestructorShapedName,
    CompiledObjectBody,
    DuplicateCompiledBody,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HelperFamily {
    /// Stable across a symbol rename or changed split map.
    pub id: String,
    pub normalized_body_sha256: String,
    /// A definition is available from this source TU; it is not proof that the
    /// TU emitted any particular target copy.
    pub source_definitions: Vec<SourceDefinition>,
    pub target_occurrences: Vec<TargetOccurrence>,
    /// Exact body present in an existing object mapped to the target version.
    /// This does not prove a fresh build or linker emission of the retail copy.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub compiled_definitions: Vec<CompiledDefinition>,
    pub signals: Vec<HelperSignal>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClusterBoundary {
    pub function_address: String,
    pub current_owner: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attribution_id: Option<String>,
    pub independently_attributed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClusterMember {
    pub name: String,
    pub address: String,
    pub end: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub autogenerated_split: Option<String>,
}

/// A bounded inventory gap, not a proposed split or guessed filename. One
/// cluster can still contain more than one future source TU.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UnresolvedTargetCluster {
    pub id: String,
    pub module: String,
    pub section: String,
    pub start: String,
    pub end: String,
    pub members: Vec<ClusterMember>,
    pub left: ClusterBoundary,
    pub right: ClusterBoundary,
}

/// A generated-looking or caller-supported function at a TU seam. The candidate is a
/// hypothesis, never an emitted-owner resolution or a proposed split.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HelperTailHypothesis {
    pub id: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
    pub candidate_unit: String,
    pub preceding_attribution_id: String,
    pub following_attribution_id: String,
    /// Names retain their source; a matching name or body is not linker proof.
    pub generated_name_evidence: Vec<GeneratedNameEvidence>,
    /// Whether either observed source version contains this body in the candidate TU.
    pub candidate_definition_observed: bool,
    /// Other observed TUs with this normalized body; none is ruled out.
    pub other_defining_units: Vec<String>,
    pub candidate_caller_ids: Vec<String>,
    pub other_or_unattributed_callers: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum GeneratedNameOrigin {
    Target,
    Source,
    CompiledObject,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct GeneratedNameEvidence {
    pub name: String,
    pub origin: GeneratedNameOrigin,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object_sha256: Option<String>,
}

fn generated_name(name: &str) -> bool {
    name.starts_with("__dt__") || name.starts_with("__sinit_") || name.starts_with("__sti__")
}

/// Report a one-function tail only when an attributed outermost source member
/// precedes it and an independently attributed different unit bounds it on
/// the other side. Calls and generated names are retained as corroboration,
/// not used to turn the positional hypothesis into ownership.
pub fn tail_hypotheses(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    attributions: &[FunctionAttribution],
    compiled: &[CompiledDefinition],
) -> Vec<HelperTailHypothesis> {
    let by_target: BTreeMap<(&str, &str, &str), &FunctionAttribution> = attributions
        .iter()
        .map(|item| {
            (
                (
                    item.target.module.as_str(),
                    item.target.section.as_str(),
                    item.target.address.as_str(),
                ),
                item,
            )
        })
        .collect();
    let outermost: BTreeMap<(&str, &str, &str), &str> =
        source.iter().fold(BTreeMap::new(), |mut map, item| {
            let key = (item.unit.as_str(), item.module.as_str(), item.section.as_str());
            let current = map.entry(key).or_insert(item.address.as_str());
            if item.address.as_str() > *current {
                *current = &item.address;
            }
            map
        });
    let first: BTreeMap<(&str, &str, &str), &str> =
        source.iter().fold(BTreeMap::new(), |mut map, item| {
            let key = (item.unit.as_str(), item.module.as_str(), item.section.as_str());
            let current = map.entry(key).or_insert(item.address.as_str());
            if item.address.as_str() < *current {
                *current = &item.address;
            }
            map
        });
    let mut ordered: Vec<_> = target.iter().collect();
    ordered.sort_by_key(|item| (&item.module, &item.section, &item.address));
    let mut result = Vec::new();
    for window in ordered.windows(3) {
        let [left, tail, right] = window else { unreachable!() };
        if left.module != tail.module
            || tail.module != right.module
            || left.section != tail.section
            || tail.section != right.section
            || tail.current_owner.is_some() && !tail.owner_autogenerated
            || by_target.contains_key(&(
                tail.module.as_str(),
                tail.section.as_str(),
                tail.address.as_str(),
            ))
        {
            continue;
        }
        let Some(before) =
            by_target.get(&(left.module.as_str(), left.section.as_str(), left.address.as_str()))
        else {
            continue;
        };
        let Some(after) =
            by_target.get(&(right.module.as_str(), right.section.as_str(), right.address.as_str()))
        else {
            continue;
        };
        if !before.independent
            || before.ambiguous
            || !after.independent
            || after.ambiguous
            || before.source.unit == after.source.unit
            || outermost
                .get(&(
                    before.source.unit.as_str(),
                    before.source.module.as_str(),
                    before.source.section.as_str(),
                ))
                .copied()
                != Some(before.source.address.as_str())
            || first
                .get(&(
                    after.source.unit.as_str(),
                    after.source.module.as_str(),
                    after.source.section.as_str(),
                ))
                .copied()
                != Some(after.source.address.as_str())
        {
            continue;
        }
        let (Some(left_end), Some(tail_start), Some(tail_end), Some(right_start)) = (
            parse_address(&left.end),
            parse_address(&tail.address),
            parse_address(&tail.end),
            parse_address(&right.address),
        ) else {
            continue;
        };
        if tail_start < left_end
            || right_start < tail_end
            || tail_start - left_end > MAX_TAIL_HYPOTHESIS_GAP
            || right_start - tail_end > MAX_TAIL_HYPOTHESIS_GAP
        {
            continue;
        }
        let mut names = BTreeSet::new();
        if generated_name(&tail.name) {
            names.insert(GeneratedNameEvidence {
                name: tail.name.clone(),
                origin: GeneratedNameOrigin::Target,
                object_sha256: None,
            });
        }
        if let Some(hash) = tail.normalized_body_sha256.as_deref() {
            for item in source.iter().filter(|item| {
                item.unit == before.source.unit
                    && item.normalized_body_sha256.as_deref() == Some(hash)
                    && generated_name(&item.name)
            }) {
                names.insert(GeneratedNameEvidence {
                    name: item.name.clone(),
                    origin: GeneratedNameOrigin::Source,
                    object_sha256: None,
                });
            }
            for item in compiled.iter().filter(|item| {
                item.unit == before.source.unit
                    && item.normalized_body_sha256 == hash
                    && generated_name(&item.name)
            }) {
                names.insert(GeneratedNameEvidence {
                    name: item.name.clone(),
                    origin: GeneratedNameOrigin::CompiledObject,
                    object_sha256: Some(item.object_sha256.clone()),
                });
            }
        }
        let mut candidate_callers = BTreeSet::new();
        let mut other_callers = 0;
        for caller in &tail.callers {
            match by_target.get(&(
                tail.module.as_str(),
                caller.section.as_str(),
                caller.address.as_str(),
            )) {
                Some(item)
                    if item.source.unit == before.source.unit
                        && item.independent
                        && !item.ambiguous =>
                {
                    candidate_callers.insert(item.id.clone());
                }
                _ => other_callers += 1,
            }
        }
        if names.is_empty() && candidate_callers.is_empty() {
            continue;
        }
        let defining_units: BTreeSet<_> = tail
            .normalized_body_sha256
            .as_deref()
            .into_iter()
            .flat_map(|hash| {
                source
                    .iter()
                    .filter(move |item| item.normalized_body_sha256.as_deref() == Some(hash))
                    .map(|item| item.unit.clone())
                    .chain(
                        compiled
                            .iter()
                            .filter(move |item| item.normalized_body_sha256 == hash)
                            .map(|item| item.unit.clone()),
                    )
            })
            .collect();
        let candidate_definition_observed = defining_units.contains(&before.source.unit);
        let other_defining_units =
            defining_units.into_iter().filter(|unit| *unit != before.source.unit).collect();
        result.push(HelperTailHypothesis {
            id: format!("helper-tail:{}:{}:{}", tail.module, tail.section, tail.address),
            module: tail.module.clone(),
            section: tail.section.clone(),
            address: tail.address.clone(),
            end: tail.end.clone(),
            candidate_unit: before.source.unit.clone(),
            preceding_attribution_id: before.id.clone(),
            following_attribution_id: after.id.clone(),
            generated_name_evidence: names.into_iter().collect(),
            candidate_definition_observed,
            other_defining_units,
            candidate_caller_ids: candidate_callers.into_iter().collect(),
            other_or_unattributed_callers: other_callers,
        });
    }
    result
}

fn parse_address(text: &str) -> Option<u32> {
    u32::from_str_radix(text.strip_prefix("0x")?, 16).ok()
}

/// A collision-resistant key for an exact normalized body. Unknown function
/// sizes and one-instruction stubs are withheld from family evidence.
pub fn body_digest(obj: &ObjInfo, node: &FunctionNode) -> Option<String> {
    if !obj.symbols[node.symbol].size_known || node.size < 8 {
        return None;
    }
    let body = normalized_body(obj, node);
    (body.len() == node.size as usize).then(|| format!("{:x}", Sha256::digest(body)))
}

/// Regenerate family summaries from the per-function digest inventory. The
/// summaries supplied by a saved report are never taken as policy input.
pub fn families(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, &[], true, false)
}

pub fn families_with_compiled(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    compiled: &[CompiledDefinition],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, compiled, true, false)
}

/// Schema 7 uses the complete object inventory. Ordinary, already-owned
/// functions must not become helper families merely because they also compile.
pub fn families_with_inventory(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    compiled: &[CompiledDefinition],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, compiled, true, true)
}

/// Preserve schema 4's target-name-only classifier when loading its saved
/// references. Schema 5 also recognizes source names when target names were
/// stripped, and therefore has a different canonical digest.
pub fn families_schema_4(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
) -> Vec<HelperFamily> {
    families_with_name_scope(source, target, &[], false, false)
}

#[derive(Default)]
struct FamilyMembers {
    source_definitions: Vec<SourceDefinition>,
    target_occurrences: Vec<TargetOccurrence>,
    compiled_definitions: Vec<CompiledDefinition>,
}

fn families_with_name_scope(
    source: &[SourceFunctionObservation],
    target: &[TargetFunctionObservation],
    compiled: &[CompiledDefinition],
    source_generated_names: bool,
    complete_compiled: bool,
) -> Vec<HelperFamily> {
    let unresolved_hashes: BTreeSet<&str> = target
        .iter()
        .filter(|function| function.current_owner.is_none() || function.owner_autogenerated)
        .filter_map(|function| function.normalized_body_sha256.as_deref())
        .collect();
    let mut groups: BTreeMap<&str, FamilyMembers> = BTreeMap::new();
    for function in source {
        let Some(hash) = function.normalized_body_sha256.as_deref() else { continue };
        groups.entry(hash).or_default().source_definitions.push(SourceDefinition {
            name: function.name.clone(),
            module: function.module.clone(),
            section: function.section.clone(),
            address: function.address.clone(),
            end: function.end.clone(),
            unit: function.unit.clone(),
            weak: function.weak,
        });
    }
    for function in target {
        let Some(hash) = function.normalized_body_sha256.as_deref() else { continue };
        groups.entry(hash).or_default().target_occurrences.push(TargetOccurrence {
            name: function.name.clone(),
            module: function.module.clone(),
            section: function.section.clone(),
            address: function.address.clone(),
            end: function.end.clone(),
            current_owner: function.current_owner.clone(),
            weak: function.weak,
        });
    }
    for function in compiled {
        groups
            .entry(&function.normalized_body_sha256)
            .or_default()
            .compiled_definitions
            .push(function.clone());
    }
    groups
        .into_iter()
        .filter_map(|(hash, members)| {
            let FamilyMembers {
                mut source_definitions,
                mut target_occurrences,
                mut compiled_definitions,
            } = members;
            if target_occurrences.is_empty() {
                return None;
            }
            source_definitions.sort_by(|left, right| {
                (&left.module, &left.section, &left.address, &left.name).cmp(&(
                    &right.module,
                    &right.section,
                    &right.address,
                    &right.name,
                ))
            });
            target_occurrences.sort_by(|left, right| {
                (&left.module, &left.section, &left.address, &left.name).cmp(&(
                    &right.module,
                    &right.section,
                    &right.address,
                    &right.name,
                ))
            });
            compiled_definitions.sort_by(|left, right| {
                (&left.unit, &left.section, &left.address, &left.name).cmp(&(
                    &right.unit,
                    &right.section,
                    &right.address,
                    &right.name,
                ))
            });
            let defining_units: BTreeSet<&str> =
                source_definitions.iter().map(|item| item.unit.as_str()).collect();
            let compiled_units: BTreeSet<&str> =
                compiled_definitions.iter().map(|item| item.unit.as_str()).collect();
            let mut signals = Vec::new();
            if defining_units.len() > 1 {
                signals.push(HelperSignal::DuplicateSourceBody);
            }
            if target_occurrences.len() > 1 {
                signals.push(HelperSignal::DuplicateTargetBody);
            }
            if complete_compiled && compiled_units.len() > 1 {
                signals.push(HelperSignal::DuplicateCompiledBody);
            }
            if source_definitions.iter().any(|item| item.weak)
                || target_occurrences.iter().any(|item| item.weak)
                || complete_compiled && compiled_definitions.iter().any(|item| item.weak)
            {
                signals.push(HelperSignal::WeakDefinition);
            }
            if (source_generated_names
                && source_definitions.iter().any(|item| {
                    item.name.starts_with("__sinit_") || item.name.starts_with("__sti__")
                }))
                || target_occurrences.iter().any(|item| {
                    item.name.starts_with("__sinit_") || item.name.starts_with("__sti__")
                })
                || complete_compiled
                    && compiled_definitions.iter().any(|item| {
                        item.name.starts_with("__sinit_") || item.name.starts_with("__sti__")
                    })
            {
                signals.push(HelperSignal::StaticInitializerName);
            }
            // A destructor-shaped symbol may denote explicit source or a
            // compiler-emitted tail. The signal deliberately makes no choice.
            if (source_generated_names
                && source_definitions.iter().any(|item| item.name.starts_with("__dt__")))
                || target_occurrences.iter().any(|item| item.name.starts_with("__dt__"))
                || complete_compiled
                    && compiled_definitions.iter().any(|item| item.name.starts_with("__dt__"))
            {
                signals.push(HelperSignal::DestructorShapedName);
            }
            if !compiled_definitions.is_empty()
                && (!complete_compiled || !signals.is_empty() || unresolved_hashes.contains(hash))
            {
                signals.push(HelperSignal::CompiledObjectBody);
            }
            (!signals.is_empty()).then(|| HelperFamily {
                id: format!("normalized-body:{hash}"),
                normalized_body_sha256: hash.into(),
                source_definitions,
                target_occurrences,
                compiled_definitions,
                signals,
            })
        })
        .collect()
}

fn boundary(
    function: &TargetFunctionObservation,
    attributions: &BTreeMap<(&str, &str, &str), &FunctionAttribution>,
) -> Option<ClusterBoundary> {
    let current_owner = function.current_owner.clone()?;
    if function.owner_autogenerated {
        return None;
    }
    let attribution = attributions.get(&(
        function.module.as_str(),
        function.section.as_str(),
        function.address.as_str(),
    ));
    Some(ClusterBoundary {
        function_address: function.address.clone(),
        current_owner,
        attribution_id: attribution.map(|item| item.id.clone()),
        independently_attributed: attribution.is_some_and(|item| item.independent),
    })
}

/// Inventory maximal runs of unmatched, unowned target functions. Requiring
/// distinct represented neighbours avoids relabelling one unit's ordinary
/// unplaced helper as a missing TU. The neighbours are observations, not proof
/// of the cluster's exact source identity or final end boundary.
pub fn unresolved_clusters(
    functions: &[TargetFunctionObservation],
    attributions: &[FunctionAttribution],
) -> Vec<UnresolvedTargetCluster> {
    let by_target: BTreeMap<(&str, &str, &str), &FunctionAttribution> = attributions
        .iter()
        .map(|item| {
            (
                (
                    item.target.module.as_str(),
                    item.target.section.as_str(),
                    item.target.address.as_str(),
                ),
                item,
            )
        })
        .collect();
    let mut ordered: Vec<&TargetFunctionObservation> = functions.iter().collect();
    ordered.sort_by_key(|item| (&item.module, &item.section, &item.address));
    let orphan = |item: &TargetFunctionObservation| {
        (item.current_owner.is_none() || item.owner_autogenerated)
            && !by_target.contains_key(&(
                item.module.as_str(),
                item.section.as_str(),
                item.address.as_str(),
            ))
    };
    let mut clusters = Vec::new();
    let mut index = 0;
    while index < ordered.len() {
        if !orphan(ordered[index]) {
            index += 1;
            continue;
        }
        let start = index;
        let module = &ordered[index].module;
        let section = &ordered[index].section;
        while index < ordered.len()
            && &ordered[index].module == module
            && &ordered[index].section == section
            && orphan(ordered[index])
        {
            index += 1;
        }
        if index - start < 2 || start == 0 || index == ordered.len() {
            continue;
        }
        let left = ordered[start - 1];
        let right = ordered[index];
        if &left.module != module
            || &left.section != section
            || &right.module != module
            || &right.section != section
        {
            continue;
        }
        let (Some(left), Some(right)) = (boundary(left, &by_target), boundary(right, &by_target))
        else {
            continue;
        };
        if left.current_owner == right.current_owner {
            continue;
        }
        let first = ordered[start];
        let last = ordered[index - 1];
        clusters.push(UnresolvedTargetCluster {
            id: format!("unresolved:{}:{}:{}", module, section, first.address),
            module: module.clone(),
            section: section.clone(),
            start: first.address.clone(),
            end: last.end.clone(),
            members: ordered[start..index]
                .iter()
                .map(|item| ClusterMember {
                    name: item.name.clone(),
                    address: item.address.clone(),
                    end: item.end.clone(),
                    autogenerated_split: item
                        .owner_autogenerated
                        .then(|| item.current_owner.clone())
                        .flatten(),
                })
                .collect(),
            left,
            right,
        });
    }
    clusters
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analysis::{
        matching::{MatchMethod, MatchTier},
        ownership::{
            AttributionOrigin, CallerReference, FunctionLocation, IdentificationReport,
            ObservationIndex, SourceFunction,
        },
    };

    fn source(unit: &str, name: &str, address: &str, hash: &str) -> SourceFunctionObservation {
        let end = format!("0x{:08X}", u32::from_str_radix(&address[2..], 16).unwrap() + 0x20);
        SourceFunctionObservation {
            name: name.into(),
            unit: unit.into(),
            module: "main".into(),
            section: ".text".into(),
            address: address.into(),
            end,
            extent_known: true,
            normalized_body_sha256: Some(hash.into()),
            weak: true,
            callers: Vec::new(),
        }
    }

    fn target(
        name: &str,
        address: &str,
        owner: Option<&str>,
        hash: Option<&str>,
    ) -> TargetFunctionObservation {
        let end = format!("0x{:08X}", u32::from_str_radix(&address[2..], 16).unwrap() + 0x20);
        TargetFunctionObservation {
            name: name.into(),
            module: "main".into(),
            section: ".text".into(),
            address: address.into(),
            end,
            extent_known: true,
            current_owner: owner.map(str::to_string),
            owner_autogenerated: false,
            callers: Vec::new(),
            normalized_body_sha256: hash.map(str::to_string),
            weak: false,
        }
    }

    fn anchor(
        source: &SourceFunctionObservation,
        target: &TargetFunctionObservation,
    ) -> FunctionAttribution {
        FunctionAttribution {
            id: format!("{}:{}", source.unit, source.name),
            target: FunctionLocation {
                module: target.module.clone(),
                section: target.section.clone(),
                address: target.address.clone(),
                end: target.end.clone(),
            },
            source: SourceFunction {
                name: source.name.clone(),
                unit: source.unit.clone(),
                module: source.module.clone(),
                section: source.section.clone(),
                address: source.address.clone(),
                end: source.end.clone(),
            },
            method: MatchMethod::ExactHash,
            tier: MatchTier::Confident,
            confidence: 1.0,
            evidence_count: 1,
            origin: AttributionOrigin::NormalizedBody,
            distinctive_body: true,
            unique_exact_body: true,
            binary_supported: true,
            independent: true,
            ambiguous: false,
            competing: None,
            source_weak: false,
            target_weak: false,
            template_instantiation: false,
            current_target_owner: target.current_owner.clone(),
            evidence: Vec::new(),
        }
    }

    fn tail_fixture()
    -> (Vec<SourceFunctionObservation>, Vec<TargetFunctionObservation>, Vec<FunctionAttribution>)
    {
        let source = vec![
            source("A.cpp", "last", "0x00001000", &"a".repeat(64)),
            source("B.cpp", "first", "0x00002000", &"b".repeat(64)),
        ];
        let mut tail = target("__dt__8CExampleFv", "0x00001020", None, Some(&"c".repeat(64)));
        tail.callers = vec![
            CallerReference { section: ".text".into(), address: "0x00001000".into() },
            CallerReference { section: ".text".into(), address: "0x00008888".into() },
        ];
        let target = vec![
            target("last", "0x00001000", Some("A.cpp"), Some(&"a".repeat(64))),
            tail,
            target("first", "0x00001040", Some("B.cpp"), Some(&"b".repeat(64))),
        ];
        let attributions = vec![anchor(&source[0], &target[0]), anchor(&source[1], &target[2])];
        (source, target, attributions)
    }

    #[test]
    fn generated_tail_is_a_hypothesis_with_its_counterevidence() {
        let (source, target, attributions) = tail_fixture();
        let hypotheses = tail_hypotheses(&source, &target, &attributions, &[]);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].candidate_unit, "A.cpp");
        assert_eq!(hypotheses[0].address, "0x00001020");
        assert_eq!(hypotheses[0].generated_name_evidence.len(), 1);
        assert_eq!(hypotheses[0].generated_name_evidence[0].name, "__dt__8CExampleFv");
        assert_eq!(hypotheses[0].generated_name_evidence[0].origin, GeneratedNameOrigin::Target);
        assert_eq!(hypotheses[0].candidate_caller_ids, ["A.cpp:last"]);
        assert_eq!(hypotheses[0].other_or_unattributed_callers, 1);
        assert!(!hypotheses[0].candidate_definition_observed);
        assert!(hypotheses[0].other_defining_units.is_empty());
    }

    #[test]
    fn tail_requires_outermost_member_and_independent_foreign_bound() {
        let (mut sources, mut target, mut attributions) = tail_fixture();
        sources.push(source("A.cpp", "later", "0x00001100", &"d".repeat(64)));
        assert!(tail_hypotheses(&sources, &target, &attributions, &[]).is_empty());
        sources.pop();
        attributions[0].independent = false;
        assert!(tail_hypotheses(&sources, &target, &attributions, &[]).is_empty());
        attributions[0].independent = true;
        attributions[1].independent = false;
        assert!(tail_hypotheses(&sources, &target, &attributions, &[]).is_empty());
        attributions[1].independent = true;
        target[1].current_owner = Some("Other.cpp".into());
        assert!(tail_hypotheses(&sources, &target, &attributions, &[]).is_empty());
    }

    #[test]
    fn compiled_generated_name_exposes_an_opaque_target_tail() {
        let (source, mut target, attributions) = tail_fixture();
        target[1].name = "fn_1020".into();
        target[1].callers.clear();
        assert!(tail_hypotheses(&source, &target, &attributions, &[]).is_empty());
        let compiled = CompiledDefinition {
            unit: "A.cpp".into(),
            name: "__dt__8CExampleFv".into(),
            section: ".text".into(),
            address: "0x00000020".into(),
            end: "0x00000040".into(),
            normalized_body_sha256: "c".repeat(64),
            weak: true,
            object_sha256: "f".repeat(64),
        };
        let hypotheses = tail_hypotheses(&source, &target, &attributions, &[compiled]);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].generated_name_evidence.len(), 1);
        assert_eq!(
            hypotheses[0].generated_name_evidence[0].origin,
            GeneratedNameOrigin::CompiledObject
        );
        assert_eq!(
            hypotheses[0].generated_name_evidence[0].object_sha256.as_deref(),
            Some("f".repeat(64).as_str())
        );
        assert!(hypotheses[0].candidate_definition_observed);
    }

    #[test]
    fn a_candidate_caller_exposes_an_opaque_tail_without_a_generated_name() {
        let (source, mut target, mut attributions) = tail_fixture();
        target[1].name = "fn_1020".into();
        let hypotheses = tail_hypotheses(&source, &target, &attributions, &[]);
        assert_eq!(hypotheses.len(), 1);
        assert!(hypotheses[0].generated_name_evidence.is_empty());
        assert_eq!(hypotheses[0].candidate_caller_ids, ["A.cpp:last"]);
        assert_eq!(hypotheses[0].other_or_unattributed_callers, 1);
        attributions[0].independent = false;
        assert!(tail_hypotheses(&source, &target, &attributions, &[]).is_empty());
    }

    #[test]
    fn source_generated_name_keeps_its_distinct_provenance() {
        let (mut sources, mut target, attributions) = tail_fixture();
        target[1].name = "fn_1020".into();
        target[1].callers.clear();
        sources.push(source("A.cpp", "__sinit_CExample_cpp", "0x00000FE0", &"c".repeat(64)));
        let hypotheses = tail_hypotheses(&sources, &target, &attributions, &[]);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].generated_name_evidence[0].origin, GeneratedNameOrigin::Source);
        assert!(hypotheses[0].candidate_definition_observed);
    }

    #[test]
    fn shared_body_availability_stays_visible_on_a_tail_hypothesis() {
        let (mut sources, target, attributions) = tail_fixture();
        sources.push(source("C.cpp", "shared", "0x00003000", &"c".repeat(64)));
        let hypotheses = tail_hypotheses(&sources, &target, &attributions, &[]);
        assert_eq!(hypotheses.len(), 1);
        assert_eq!(hypotheses[0].other_defining_units, ["C.cpp"]);
    }

    #[test]
    fn serialized_tail_hypotheses_are_rederived_only_in_schema_twelve() {
        let mut report = IdentificationReport::empty("NTSC", "PAL");
        report.helper_tail_hypotheses.push(HelperTailHypothesis {
            id: "forged".into(),
            module: "main".into(),
            section: ".text".into(),
            address: "0x00001020".into(),
            end: "0x00001040".into(),
            candidate_unit: "A.cpp".into(),
            preceding_attribution_id: "forged".into(),
            following_attribution_id: "forged".into(),
            generated_name_evidence: vec![GeneratedNameEvidence {
                name: "__dt__8CExampleFv".into(),
                origin: GeneratedNameOrigin::Target,
                object_sha256: None,
            }],
            candidate_definition_observed: false,
            other_defining_units: Vec::new(),
            candidate_caller_ids: Vec::new(),
            other_or_unattributed_callers: 0,
        });
        report.schema = 11;
        assert!(ObservationIndex::load_self_contained(report.clone(), "NTSC", "PAL").is_err());
        report.schema = 12;
        let loaded = ObservationIndex::load_self_contained(report, "NTSC", "PAL").unwrap();
        assert!(loaded.report().helper_tail_hypotheses.is_empty());
    }

    #[test]
    fn duplicate_definitions_are_availability_not_an_emitted_owner() {
        let hash = "a".repeat(64);
        let families = families(
            &[
                source("A.cpp", "helper", "0x00001000", &hash),
                source("B.cpp", "helper", "0x00002000", &hash),
            ],
            &[target("fn_3000", "0x00003000", Some("A.cpp"), Some(&hash))],
        );
        assert_eq!(families.len(), 1);
        assert_eq!(families[0].signals, vec![
            HelperSignal::DuplicateSourceBody,
            HelperSignal::WeakDefinition
        ]);
        assert_eq!(families[0].source_definitions.len(), 2);
        assert_eq!(families[0].target_occurrences[0].current_owner.as_deref(), Some("A.cpp"));
    }

    #[test]
    fn bounded_orphan_run_has_no_invented_source_tu() {
        let mut functions = [
            target("left", "0x80356944", Some("Kyoto/CFrameDelayedKiller.cpp"), None),
            target("fn_80356EDC", "0x80356EDC", Some("auto_80356EDC"), None),
            target("fn_80356F30", "0x80356F30", Some("auto_80356EDC"), None),
            target("right", "0x80357064", Some("dolphin/ai.c"), None),
        ];
        functions[1].owner_autogenerated = true;
        functions[2].owner_autogenerated = true;
        let clusters = unresolved_clusters(&functions, &[]);
        assert_eq!(clusters.len(), 1);
        assert_eq!(clusters[0].start, "0x80356EDC");
        assert_eq!(clusters[0].members.len(), 2);
        assert_eq!(clusters[0].members[0].autogenerated_split.as_deref(), Some("auto_80356EDC"));
        assert!(
            !serde_json::to_string(&clusters[0]).unwrap().contains("CTimeRemainderAndFraction")
        );
    }

    #[test]
    fn duplicate_target_bodies_are_visible_without_compiled_source_objects() {
        let hash = "b".repeat(64);
        let families = families(&[], &[
            target("fn_1000", "0x00001000", None, Some(&hash)),
            target("fn_2000", "0x00002000", None, Some(&hash)),
        ]);
        assert_eq!(families.len(), 1);
        assert!(families[0].source_definitions.is_empty());
        assert_eq!(families[0].signals, vec![HelperSignal::DuplicateTargetBody]);
    }

    #[test]
    fn a_destructor_shape_is_only_a_hypothesis() {
        let hash = "c".repeat(64);
        let families =
            families(&[], &[target("__dt__12CInstructionFv", "0x00001000", None, Some(&hash))]);
        assert_eq!(families[0].signals, vec![HelperSignal::DestructorShapedName]);
        assert!(families[0].source_definitions.is_empty());
    }

    #[test]
    fn a_source_generated_name_survives_an_opaque_target_symbol() {
        let hash = "d".repeat(64);
        let initializer_families = families(
            &[source("CPowerBomb.cpp", "__sinit_CPowerBomb_cpp", "0x00001000", &hash)],
            &[target("fn_80145158", "0x80145158", None, Some(&hash))],
        );
        assert_eq!(initializer_families.len(), 1);
        assert!(initializer_families[0].signals.contains(&HelperSignal::StaticInitializerName));

        let destructor_hash = "e".repeat(64);
        let destructor_families = families(
            &[source("CInstruction.cpp", "__dt__12CInstructionFv", "0x00002000", &destructor_hash)],
            &[target("fn_80202000", "0x80202000", None, Some(&destructor_hash))],
        );
        assert_eq!(destructor_families.len(), 1);
        assert!(destructor_families[0].signals.contains(&HelperSignal::DestructorShapedName));
    }

    #[test]
    fn compiled_availability_keeps_emitted_target_ownership_unknown() {
        let hash = "f".repeat(64);
        let compiled = CompiledDefinition {
            unit: "A.cpp".into(),
            name: "helper".into(),
            section: ".text".into(),
            address: "0x00000000".into(),
            end: "0x00000020".into(),
            normalized_body_sha256: hash.clone(),
            weak: true,
            object_sha256: "a".repeat(64),
        };
        let families =
            families_with_compiled(&[], &[target("fn_1000", "0x00001000", None, Some(&hash))], &[
                compiled,
            ]);
        assert_eq!(families.len(), 1);
        assert!(families[0].source_definitions.is_empty());
        assert_eq!(families[0].compiled_definitions[0].unit, "A.cpp");
        assert_eq!(families[0].target_occurrences[0].current_owner, None);
        assert_eq!(families[0].signals, [HelperSignal::CompiledObjectBody]);
    }

    #[test]
    fn complete_inventory_does_not_turn_every_owned_body_into_a_helper() {
        let hash = "a".repeat(64);
        let compiled = CompiledDefinition {
            unit: "A.cpp".into(),
            name: "ordinary".into(),
            section: ".text".into(),
            address: "0x00000000".into(),
            end: "0x00000020".into(),
            normalized_body_sha256: hash.clone(),
            weak: false,
            object_sha256: "b".repeat(64),
        };
        let owned = [target("ordinary", "0x00001000", Some("A.cpp"), Some(&hash))];
        assert!(families_with_inventory(&[], &owned, std::slice::from_ref(&compiled)).is_empty());
        // Schema 6's classifier must retain its original saved-report shape.
        assert_eq!(families_with_compiled(&[], &owned, std::slice::from_ref(&compiled)).len(), 1);

        let mut other = compiled.clone();
        other.unit = "B.cpp".into();
        let duplicated = families_with_inventory(&[], &owned, &[compiled.clone(), other]);
        assert_eq!(duplicated.len(), 1);
        assert!(duplicated[0].signals.contains(&HelperSignal::DuplicateCompiledBody));

        let mut weak = compiled;
        weak.weak = true;
        let weak_family = families_with_inventory(&[], &owned, &[weak]);
        assert_eq!(weak_family.len(), 1);
        assert!(weak_family[0].signals.contains(&HelperSignal::WeakDefinition));
    }
}
