//! Optional compiled-source evidence for helper families.
//!
//! A compiled definition proves that an existing object mapped to the target
//! version contains a body. It does not prove that the object was rebuilt from
//! the checkout's current source, that the linker selected it, or that its
//! function supplied a particular target occurrence. Object paths come from
//! objdiff's `base_path`; `target_path` is the extracted retail object and is
//! deliberately not used as compiled-source evidence.

use std::{
    collections::{BTreeMap, BTreeSet},
    io::ErrorKind,
    path::{Component, Path},
};

use anyhow::{Result, bail};
use decomp_toolkit::{obj::ObjSectionKind, util::elf::process_elf};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use typed_path::Utf8NativePath;

use crate::{
    analysis::{
        callgraph::CallGraph,
        helpers::body_digest,
        ownership::{FunctionAttribution, TargetFunctionObservation},
    },
    project::{analyze::with_working_directory, report::ObjdiffConfig},
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ScanStatus {
    Scanned,
    MissingObjdiff,
    UnreadableObjdiff,
    InvalidObjdiff,
    MismatchedVersion,
    InvalidObjectInventory,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ObjectStatus {
    Available,
    Missing,
    Unreadable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ObjectRecord {
    pub unit: String,
    pub base_path: String,
    pub status: ObjectStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
    /// Complete sized code-symbol inventory, including bodies that do not
    /// match a target function. Available from identification schema 7.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub functions: Vec<CompiledFunction>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompiledReference {
    /// Offset from the start of the compiled function.
    pub offset: u32,
    pub kind: String,
    pub target: String,
    pub target_section: Option<String>,
    pub target_address: u64,
    pub addend: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompiledFunction {
    pub name: String,
    pub section: String,
    pub address: String,
    pub end: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub normalized_body_sha256: Option<String>,
    pub weak: bool,
    pub references: Vec<CompiledReference>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompiledDefinition {
    pub unit: String,
    pub name: String,
    pub section: String,
    /// Addresses are relative to the compiled ELF section, not retail VAs.
    pub address: String,
    pub end: String,
    pub normalized_body_sha256: String,
    pub weak: bool,
    pub object_sha256: String,
}

/// An adjacent exact-body match between a compiled source object and the
/// target executable. The neighbour's existing owner or independent
/// attribution is the unit named by the compiled object. A non-independent
/// match is diagnostic only; neither kind decides linker emission by itself.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OrderNeighbour {
    pub compiled_name: String,
    pub compiled_address: String,
    pub target_address: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_owner: Option<String>,
    pub owner_autogenerated: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attribution_id: Option<String>,
    pub independently_attributed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ObjectOrderMatch {
    pub unit: String,
    pub object_sha256: String,
    pub section: String,
    pub compiled_address: String,
    pub target_address: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_owner: Option<String>,
    pub owner_autogenerated: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub before: Option<OrderNeighbour>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after: Option<OrderNeighbour>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ObjectEvidence {
    pub status: ScanStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub objdiff_sha256: Option<String>,
    pub objects: Vec<ObjectRecord>,
    /// Source units without a compiled-object mapping in objdiff.json.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub unmapped_units: Vec<String>,
    pub definitions: Vec<CompiledDefinition>,
    /// Derived from complete object order and target function facts on load.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub order_matches: Vec<ObjectOrderMatch>,
}

impl ObjectEvidence {
    pub(crate) fn unavailable(status: ScanStatus) -> Self {
        Self {
            status,
            objdiff_sha256: None,
            objects: Vec::new(),
            unmapped_units: Vec::new(),
            definitions: Vec::new(),
            order_matches: Vec::new(),
        }
    }

    pub fn canonicalize(
        &mut self,
        units: &BTreeSet<String>,
        target_hashes: &BTreeSet<String>,
        require_inventory: bool,
    ) -> Result<()> {
        if (self.status == ScanStatus::Scanned) != self.objdiff_sha256.is_some()
            || self.objdiff_sha256.as_deref().is_some_and(|hash| !valid_digest(hash))
        {
            bail!("Compiled-object evidence has invalid objdiff provenance");
        }
        if self.status != ScanStatus::Scanned
            && (!self.objects.is_empty()
                || !self.definitions.is_empty()
                || !self.unmapped_units.is_empty()
                || !self.order_matches.is_empty())
        {
            bail!("Unavailable compiled-object channel contains observations");
        }
        let mut seen = BTreeSet::new();
        let mut available = BTreeSet::new();
        let mut inventory = BTreeSet::new();
        for record in &mut self.objects {
            let status_and_hash_valid = match record.status {
                ObjectStatus::Available => record.sha256.is_some(),
                ObjectStatus::Missing => record.sha256.is_none(),
                ObjectStatus::Unreadable => true,
            };
            if !units.contains(&record.unit)
                || !safe_relative(&record.base_path)
                || !seen.insert((&record.unit, &record.base_path))
                || record.sha256.as_deref().is_some_and(|hash| !valid_digest(hash))
                || !status_and_hash_valid
                || (record.status != ObjectStatus::Available && !record.functions.is_empty())
            {
                bail!("Compiled-object evidence has an invalid object record");
            }
            if record.status == ObjectStatus::Available {
                available.insert((&record.unit, record.sha256.as_deref().unwrap()));
            }
            let mut seen_functions = BTreeSet::new();
            for function in &mut record.functions {
                let (Some(start), Some(end)) =
                    (parse_hex(&function.address), parse_hex(&function.end))
                else {
                    bail!("Compiled-object evidence has an invalid function address");
                };
                function.address = hex(start);
                function.end = hex(end);
                if function.section.is_empty()
                    || function
                        .normalized_body_sha256
                        .as_deref()
                        .is_some_and(|hash| !valid_digest(hash))
                    || end <= start
                    || !seen_functions.insert((
                        function.section.clone(),
                        function.address.clone(),
                        function.name.clone(),
                    ))
                {
                    bail!("Compiled-object evidence has an invalid function inventory");
                }
                let size = end - start;
                if function.references.iter().any(|reference| {
                    reference.offset >= size
                        || reference.kind.is_empty()
                        || reference.target_section.as_deref() == Some("")
                }) {
                    bail!("Compiled-object evidence has an invalid relocation reference");
                }
                function.references.sort_by(|left, right| {
                    (
                        left.offset,
                        &left.kind,
                        &left.target,
                        &left.target_section,
                        left.target_address,
                        left.addend,
                    )
                        .cmp(&(
                            right.offset,
                            &right.kind,
                            &right.target,
                            &right.target_section,
                            right.target_address,
                            right.addend,
                        ))
                });
                if let Some(hash) = &function.normalized_body_sha256 {
                    inventory.insert((
                        record.unit.clone(),
                        record.sha256.clone().unwrap(),
                        function.section.clone(),
                        function.address.clone(),
                        function.end.clone(),
                        function.name.clone(),
                        hash.clone(),
                        function.weak,
                    ));
                }
            }
            record.functions.sort_by(|left, right| {
                (&left.section, &left.address, &left.end, &left.name).cmp(&(
                    &right.section,
                    &right.address,
                    &right.end,
                    &right.name,
                ))
            });
        }
        let mut definitions = BTreeSet::new();
        for definition in &mut self.definitions {
            let (Some(start), Some(end)) =
                (parse_hex(&definition.address), parse_hex(&definition.end))
            else {
                bail!("Compiled-object evidence has an invalid function definition address");
            };
            if require_inventory {
                definition.address = hex(start);
                definition.end = hex(end);
            }
            if !units.contains(&definition.unit)
                || definition.name.is_empty()
                || definition.section.is_empty()
                || !valid_digest(&definition.normalized_body_sha256)
                || !valid_digest(&definition.object_sha256)
                || !target_hashes.contains(&definition.normalized_body_sha256)
                || !available.contains(&(&definition.unit, definition.object_sha256.as_str()))
                || (require_inventory
                    && !inventory.contains(&(
                        definition.unit.clone(),
                        definition.object_sha256.clone(),
                        definition.section.clone(),
                        definition.address.clone(),
                        definition.end.clone(),
                        definition.name.clone(),
                        definition.normalized_body_sha256.clone(),
                        definition.weak,
                    )))
                || end <= start
                || !definitions.insert((
                    &definition.unit,
                    &definition.section,
                    &definition.address,
                    &definition.name,
                    &definition.object_sha256,
                ))
            {
                bail!("Compiled-object evidence has an invalid function definition");
            }
        }
        self.objects.sort_by(|a, b| (&a.unit, &a.base_path).cmp(&(&b.unit, &b.base_path)));
        if self.status == ScanStatus::Scanned {
            let mapped: BTreeSet<&str> =
                self.objects.iter().map(|item| item.unit.as_str()).collect();
            self.unmapped_units =
                units.iter().filter(|unit| !mapped.contains(unit.as_str())).cloned().collect();
        }
        self.definitions.sort_by(|a, b| {
            (&a.unit, &a.section, &a.address, &a.name, &a.object_sha256).cmp(&(
                &b.unit,
                &b.section,
                &b.address,
                &b.name,
                &b.object_sha256,
            ))
        });
        Ok(())
    }
}

fn safe_relative(path: &str) -> bool {
    !path.is_empty()
        && !path.contains(':')
        && !path.starts_with('\\')
        && Path::new(path).components().all(|component| matches!(component, Component::Normal(_)))
}

fn hex(value: u32) -> String { format!("0x{value:08X}") }

fn parse_hex(value: &str) -> Option<u32> { u32::from_str_radix(value.strip_prefix("0x")?, 16).ok() }

fn valid_digest(value: &str) -> bool {
    value.len() == 64
        && value.bytes().all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// Scan existing compiled source objects. Missing files and unreadable objects
/// are recorded as unavailable; neither blocks binary-only identification.
/// Only functions matching a known target body digest are retained, so a
/// complete scan does not duplicate the whole compiled-object symbol table.
pub fn inspect(
    root: &Path,
    target_version: &str,
    units: &BTreeSet<String>,
    target_hashes: &BTreeSet<String>,
) -> ObjectEvidence {
    let config_path = root.join("objdiff.json");
    let config_bytes = match std::fs::read(&config_path) {
        Ok(bytes) => bytes,
        Err(error) => {
            return ObjectEvidence::unavailable(if error.kind() == ErrorKind::NotFound {
                ScanStatus::MissingObjdiff
            } else {
                ScanStatus::UnreadableObjdiff
            });
        }
    };
    let Ok(config) = serde_json::from_slice::<ObjdiffConfig>(&config_bytes) else {
        return ObjectEvidence::unavailable(ScanStatus::InvalidObjdiff);
    };
    let Ok(canonical_root) = root.canonicalize() else {
        return ObjectEvidence::unavailable(ScanStatus::UnreadableObjdiff);
    };
    // A checkout can retain objdiff.json from its last configure, even when
    // match loads another version's config.yml. Never label those objects as
    // compiled for the target version.
    if config.units.iter().any(|entry| {
        entry.metadata.module_id == 0
            && ObjdiffConfig::source_name_of(entry).is_some_and(|unit| units.contains(unit))
            && entry.base_path.as_deref().is_some_and(|base| {
                !versioned_object_path(base, target_version)
                    || entry
                        .target_path
                        .as_deref()
                        .is_some_and(|target| !versioned_object_path(target, target_version))
            })
    }) {
        return ObjectEvidence::unavailable(ScanStatus::MismatchedVersion);
    }
    let mut evidence = ObjectEvidence {
        status: ScanStatus::Scanned,
        objdiff_sha256: Some(format!("{:x}", Sha256::digest(config_bytes))),
        objects: Vec::new(),
        unmapped_units: Vec::new(),
        definitions: Vec::new(),
        order_matches: Vec::new(),
    };
    let mut seen = BTreeSet::new();
    for entry in config.units {
        if entry.metadata.module_id != 0 {
            continue;
        }
        let Some(unit) = ObjdiffConfig::source_name_of(&entry) else { continue };
        if !units.contains(unit) {
            continue;
        }
        let Some(base_path) = entry.base_path.as_deref() else { continue };
        // An objdiff path outside this checkout cannot be attributed to this
        // build. Leave its unit unmapped rather than emitting a record that
        // canonical loading would have to reject.
        if !safe_relative(base_path) {
            continue;
        }
        if !seen.insert((unit.to_string(), base_path.to_string())) {
            continue;
        }
        let mut record = ObjectRecord {
            unit: unit.to_string(),
            base_path: base_path.to_string(),
            status: ObjectStatus::Unreadable,
            sha256: None,
            functions: Vec::new(),
        };
        let path = root.join(base_path);
        // Lexical checks alone do not stop a build directory symlink from
        // pointing at another checkout or drive.
        let resolved = match path.canonicalize() {
            Ok(resolved) if resolved.starts_with(&canonical_root) => resolved,
            Err(error) if error.kind() == ErrorKind::NotFound => {
                record.status = ObjectStatus::Missing;
                evidence.objects.push(record);
                continue;
            }
            _ => {
                evidence.objects.push(record);
                continue;
            }
        };
        let bytes = match std::fs::read(&resolved) {
            Ok(bytes) => bytes,
            Err(error) => {
                if error.kind() == ErrorKind::NotFound {
                    record.status = ObjectStatus::Missing;
                }
                evidence.objects.push(record);
                continue;
            }
        };
        let digest = format!("{:x}", Sha256::digest(&bytes));
        record.sha256 = Some(digest.clone());
        let Ok(relative) = resolved.strip_prefix(&canonical_root) else {
            evidence.objects.push(record);
            continue;
        };
        let Some(path_text) = relative.to_str() else {
            evidence.objects.push(record);
            continue;
        };
        let Ok(obj) =
            with_working_directory(&canonical_root, || process_elf(Utf8NativePath::new(path_text)))
        else {
            evidence.objects.push(record);
            continue;
        };
        record.status = ObjectStatus::Available;
        let mut definitions = Vec::new();
        let mut functions = Vec::new();
        for (_, function) in CallGraph::build(&obj).iter() {
            if obj.sections[function.section].kind != ObjSectionKind::Code {
                continue;
            }
            let Some(end) = function.address.checked_add(function.size) else { continue };
            let name = obj.symbols[function.symbol].name.clone();
            let section = obj.sections[function.section].name.clone();
            let body_hash = body_digest(&obj, function);
            let weak = obj.symbols[function.symbol].flags.is_weak();
            functions.push(CompiledFunction {
                name: name.clone(),
                section: section.clone(),
                address: hex(function.address),
                end: hex(end),
                normalized_body_sha256: body_hash.clone(),
                weak,
                references: function
                    .refs
                    .iter()
                    .map(|reference| {
                        let target = &obj.symbols[reference.target_symbol];
                        CompiledReference {
                            offset: reference.offset,
                            kind: format!("{:?}", reference.kind),
                            target: target.name.clone(),
                            target_section: target
                                .section
                                .map(|section| obj.sections[section].name.clone()),
                            target_address: target.address,
                            addend: reference.addend,
                        }
                    })
                    .collect(),
            });
            let Some(body_hash) =
                body_hash.filter(|hash| !name.is_empty() && target_hashes.contains(hash))
            else {
                continue;
            };
            definitions.push(CompiledDefinition {
                unit: unit.to_string(),
                name: obj.symbols[function.symbol].name.clone(),
                section,
                address: hex(function.address),
                end: hex(end),
                normalized_body_sha256: body_hash,
                weak,
                object_sha256: digest.clone(),
            });
        }
        // process_elf opens the file separately from the hash read. If a
        // concurrent build changed it during the scan, neither snapshot is
        // reliable evidence for this object hash.
        if std::fs::read(&resolved).ok().as_deref() != Some(bytes.as_slice()) {
            record.status = ObjectStatus::Unreadable;
        } else {
            for function in &mut functions {
                function.references.sort_by(|left, right| {
                    (
                        left.offset,
                        &left.kind,
                        &left.target,
                        &left.target_section,
                        left.target_address,
                        left.addend,
                    )
                        .cmp(&(
                            right.offset,
                            &right.kind,
                            &right.target,
                            &right.target_section,
                            right.target_address,
                            right.addend,
                        ))
                });
            }
            functions.sort_by(|left, right| {
                (&left.section, &left.address, &left.end, &left.name).cmp(&(
                    &right.section,
                    &right.address,
                    &right.end,
                    &right.name,
                ))
            });
            let duplicate = functions.windows(2).any(|pair| {
                (&pair[0].section, &pair[0].address, &pair[0].name)
                    == (&pair[1].section, &pair[1].address, &pair[1].name)
            });
            if duplicate {
                record.status = ObjectStatus::Unreadable;
            } else {
                record.functions = functions;
                evidence.definitions.extend(definitions);
            }
        }
        evidence.objects.push(record);
    }
    evidence.objects.sort_by(|a, b| (&a.unit, &a.base_path).cmp(&(&b.unit, &b.base_path)));
    let mapped: BTreeSet<&str> = evidence.objects.iter().map(|item| item.unit.as_str()).collect();
    evidence.unmapped_units =
        units.iter().filter(|unit| !mapped.contains(unit.as_str())).cloned().collect();
    evidence.definitions.sort_by(|a, b| {
        (&a.unit, &a.section, &a.address, &a.name, &a.object_sha256).cmp(&(
            &b.unit,
            &b.section,
            &b.address,
            &b.name,
            &b.object_sha256,
        ))
    });
    evidence.definitions.dedup_by(|a, b| {
        (&a.unit, &a.section, &a.address, &a.name, &a.object_sha256)
            == (&b.unit, &b.section, &b.address, &b.name, &b.object_sha256)
    });
    evidence
}

fn versioned_object_path(path: &str, target_version: &str) -> bool {
    if !safe_relative(path) {
        return false;
    }
    let normalized = path.replace('\\', "/");
    let mut parts = normalized.split('/');
    matches!((parts.next(), parts.next(), parts.next()), (Some("build"), Some(version), Some(rest)) if version == target_version && !rest.is_empty())
}

/// Rebuild exact immediate-order observations from object and target function
/// facts. An order match is never an ownership assignment: it may be a shared
/// body, and the linker can select another definition of the same helper.
pub fn order_matches(
    evidence: &ObjectEvidence,
    target_functions: &[TargetFunctionObservation],
    attributions: &[FunctionAttribution],
) -> Vec<ObjectOrderMatch> {
    if evidence.status != ScanStatus::Scanned {
        return Vec::new();
    }
    let mut target_sections: BTreeMap<&str, Vec<&TargetFunctionObservation>> = BTreeMap::new();
    for function in target_functions.iter().filter(|function| function.module == "main") {
        target_sections.entry(&function.section).or_default().push(function);
    }
    for functions in target_sections.values_mut() {
        functions.sort_by(|left, right| left.address.cmp(&right.address));
    }
    let mut target_by_hash: BTreeMap<(&str, &str), Vec<usize>> = BTreeMap::new();
    for (&section, functions) in &target_sections {
        for (index, function) in functions.iter().enumerate() {
            if let Some(hash) = function.normalized_body_sha256.as_deref() {
                target_by_hash.entry((section, hash)).or_default().push(index);
            }
        }
    }
    let attributed: BTreeMap<(&str, &str), &FunctionAttribution> = attributions
        .iter()
        .filter(|attribution| attribution.target.module == "main")
        .map(|attribution| {
            (
                (attribution.target.section.as_str(), attribution.target.address.as_str()),
                attribution,
            )
        })
        .collect();
    let mut matches = Vec::new();
    for record in evidence.objects.iter().filter(|record| record.status == ObjectStatus::Available)
    {
        let mut compiled_sections: BTreeMap<&str, Vec<&CompiledFunction>> = BTreeMap::new();
        for function in &record.functions {
            compiled_sections.entry(&function.section).or_default().push(function);
        }
        for functions in compiled_sections.values_mut() {
            functions.sort_by(|left, right| {
                (&left.address, &left.end, &left.name).cmp(&(
                    &right.address,
                    &right.end,
                    &right.name,
                ))
            });
        }
        let mut compiled_positions: BTreeMap<(&str, &str, &str, &str), usize> = BTreeMap::new();
        for (&section, functions) in &compiled_sections {
            for (index, function) in functions.iter().enumerate() {
                compiled_positions
                    .insert((section, &function.address, &function.end, &function.name), index);
            }
        }
        for definition in evidence.definitions.iter().filter(|definition| {
            definition.unit == record.unit
                && record.sha256.as_deref() == Some(definition.object_sha256.as_str())
        }) {
            let Some(compiled) = compiled_sections.get(definition.section.as_str()) else {
                continue;
            };
            let Some(&compiled_index) = compiled_positions.get(&(
                definition.section.as_str(),
                definition.address.as_str(),
                definition.end.as_str(),
                definition.name.as_str(),
            )) else {
                continue;
            };
            let Some(targets) = target_sections.get(definition.section.as_str()) else {
                continue;
            };
            let Some(target_indices) = target_by_hash
                .get(&(definition.section.as_str(), definition.normalized_body_sha256.as_str()))
            else {
                continue;
            };
            for &target_index in target_indices {
                let target = targets[target_index];
                if target.current_owner.as_deref() == Some(record.unit.as_str())
                    && !target.owner_autogenerated
                {
                    continue;
                }
                let before = compiled_index
                    .checked_sub(1)
                    .zip(target_index.checked_sub(1))
                    .and_then(|(compiled_index, target_index)| {
                        matching_neighbour(
                            compiled[compiled_index],
                            &definition.address,
                            targets[target_index],
                            &target.address,
                            &record.unit,
                            &attributed,
                            true,
                        )
                    });
                let after = compiled
                    .get(compiled_index + 1)
                    .zip(targets.get(target_index + 1))
                    .and_then(|(compiled, target_neighbour)| {
                        matching_neighbour(
                            compiled,
                            &definition.end,
                            target_neighbour,
                            &target.end,
                            &record.unit,
                            &attributed,
                            false,
                        )
                    });
                if before.is_some() || after.is_some() {
                    matches.push(ObjectOrderMatch {
                        unit: record.unit.clone(),
                        object_sha256: definition.object_sha256.clone(),
                        section: definition.section.clone(),
                        compiled_address: definition.address.clone(),
                        target_address: target.address.clone(),
                        current_owner: target.current_owner.clone(),
                        owner_autogenerated: target.owner_autogenerated,
                        before,
                        after,
                    });
                }
            }
        }
    }
    matches.sort_by(|left, right| {
        (&left.unit, &left.section, &left.target_address, &left.compiled_address).cmp(&(
            &right.unit,
            &right.section,
            &right.target_address,
            &right.compiled_address,
        ))
    });
    matches.dedup();
    matches
}

fn matching_neighbour(
    compiled: &CompiledFunction,
    compiled_edge: &str,
    target: &TargetFunctionObservation,
    target_edge: &str,
    unit: &str,
    attributions: &BTreeMap<(&str, &str), &FunctionAttribution>,
    before: bool,
) -> Option<OrderNeighbour> {
    let contiguous = if before {
        compiled.end == compiled_edge && target.end == target_edge
    } else {
        compiled.address == compiled_edge && target.address == target_edge
    };
    if !contiguous
        || compiled.normalized_body_sha256.is_none()
        || compiled.normalized_body_sha256 != target.normalized_body_sha256
    {
        return None;
    }
    let attribution =
        attributions.get(&(target.section.as_str(), target.address.as_str())).copied();
    let independent = attribution.is_some_and(|item| item.source.unit == unit && item.independent);
    if attribution.is_some_and(|item| item.independent && item.source.unit != unit)
        || !independent
            && (target.current_owner.as_deref() != Some(unit) || target.owner_autogenerated)
    {
        return None;
    }
    Some(OrderNeighbour {
        compiled_name: compiled.name.clone(),
        compiled_address: compiled.address.clone(),
        target_address: target.address.clone(),
        current_owner: target.current_owner.clone(),
        owner_autogenerated: target.owner_autogenerated,
        attribution_id: attribution
            .filter(|item| item.source.unit == unit)
            .map(|item| item.id.clone()),
        independently_attributed: independent,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_objdiff_is_an_unavailable_channel() {
        let root = tempfile::tempdir().unwrap();
        let evidence = inspect(root.path(), "PAL", &BTreeSet::new(), &BTreeSet::new());
        assert_eq!(evidence.status, ScanStatus::MissingObjdiff);
        assert!(evidence.definitions.is_empty());
    }

    #[test]
    fn paths_cannot_escape_the_selected_project_root() {
        assert!(safe_relative("build/PAL/src/A.o"));
        assert!(!safe_relative("../elsewhere/A.o"));
        assert!(!safe_relative("C:/elsewhere/A.o"));
    }

    #[test]
    fn objdiff_for_another_version_is_not_target_object_evidence() {
        let root = tempfile::tempdir().unwrap();
        for (base, target) in [
            ("build/NTSC/src/A.o", "build/PAL/obj/A.o"),
            ("build/PAL/src/A.o", "build/NTSC/obj/A.o"),
        ] {
            std::fs::write(
                root.path().join("objdiff.json"),
                serde_json::to_vec(&serde_json::json!({
                    "units": [{
                        "name": "main/A",
                        "base_path": base,
                        "target_path": target,
                        "metadata": {"source_path": "src/A.cpp"}
                    }]
                }))
                .unwrap(),
            )
            .unwrap();
            let evidence =
                inspect(root.path(), "PAL", &BTreeSet::from(["A.cpp".into()]), &BTreeSet::new());
            assert_eq!(evidence.status, ScanStatus::MismatchedVersion);
            assert!(evidence.objects.is_empty());
        }
    }

    #[test]
    fn a_compiled_definition_must_bind_to_an_available_object_and_target_body() {
        let object_hash = "a".repeat(64);
        let body_hash = "b".repeat(64);
        let mut evidence = ObjectEvidence {
            status: ScanStatus::Scanned,
            objdiff_sha256: Some("c".repeat(64)),
            objects: vec![ObjectRecord {
                unit: "A.cpp".into(),
                base_path: "build/PAL/src/A.o".into(),
                status: ObjectStatus::Available,
                sha256: Some(object_hash.clone()),
                functions: Vec::new(),
            }],
            unmapped_units: Vec::new(),
            definitions: vec![CompiledDefinition {
                unit: "A.cpp".into(),
                name: "helper".into(),
                section: ".text".into(),
                address: "0x00000000".into(),
                end: "0x00000020".into(),
                normalized_body_sha256: body_hash.clone(),
                weak: true,
                object_sha256: object_hash,
            }],
            order_matches: Vec::new(),
        };
        let units = BTreeSet::from(["A.cpp".into(), "B.cpp".into()]);
        let targets = BTreeSet::from([body_hash]);
        evidence.canonicalize(&units, &targets, false).unwrap();
        assert_eq!(evidence.unmapped_units, ["B.cpp"]);
        evidence.objects[0].status = ObjectStatus::Missing;
        assert!(evidence.canonicalize(&units, &targets, false).is_err());
    }

    #[test]
    fn an_immediate_object_neighbour_matches_without_assigning_the_helper() {
        let anchor_hash = "a".repeat(64);
        let helper_hash = "b".repeat(64);
        let object_hash = "c".repeat(64);
        let function = |name: &str, start: &str, end: &str, hash: &str| CompiledFunction {
            name: name.into(),
            section: ".text".into(),
            address: start.into(),
            end: end.into(),
            normalized_body_sha256: Some(hash.into()),
            weak: false,
            references: Vec::new(),
        };
        let mut evidence = ObjectEvidence {
            status: ScanStatus::Scanned,
            objdiff_sha256: Some("d".repeat(64)),
            objects: vec![ObjectRecord {
                unit: "A.cpp".into(),
                base_path: "build/PAL/src/A.o".into(),
                status: ObjectStatus::Available,
                sha256: Some(object_hash.clone()),
                functions: vec![
                    function("anchor", "0x00000000", "0x00000020", &anchor_hash),
                    function("helper", "0x00000020", "0x0000002C", &helper_hash),
                ],
            }],
            unmapped_units: Vec::new(),
            definitions: vec![CompiledDefinition {
                unit: "A.cpp".into(),
                name: "helper".into(),
                section: ".text".into(),
                address: "0x00000020".into(),
                end: "0x0000002C".into(),
                normalized_body_sha256: helper_hash.clone(),
                weak: false,
                object_sha256: object_hash,
            }],
            order_matches: Vec::new(),
        };
        evidence
            .canonicalize(
                &BTreeSet::from(["A.cpp".into()]),
                &BTreeSet::from([helper_hash.clone()]),
                true,
            )
            .unwrap();
        let target = |name: &str, start: &str, end: &str, hash: &str, owner: Option<&str>| {
            TargetFunctionObservation {
                name: name.into(),
                module: "main".into(),
                section: ".text".into(),
                address: start.into(),
                end: end.into(),
                current_owner: owner.map(str::to_string),
                owner_autogenerated: false,
                callers: Vec::new(),
                normalized_body_sha256: Some(hash.into()),
                weak: false,
            }
        };
        let mut targets = vec![
            target("anchor", "0x00001000", "0x00001020", &anchor_hash, Some("A.cpp")),
            target("helper", "0x00001020", "0x0000102C", &helper_hash, None),
        ];
        let matches = order_matches(&evidence, &targets, &[]);
        assert_eq!(matches.len(), 1);
        assert_eq!(matches[0].target_address, "0x00001020");
        assert_eq!(matches[0].before.as_ref().unwrap().compiled_name, "anchor");
        assert!(!matches[0].before.as_ref().unwrap().independently_attributed);
        targets[1].current_owner = Some("B.cpp".into());
        let misplaced = order_matches(&evidence, &targets, &[]);
        assert_eq!(misplaced.len(), 1);
        assert_eq!(misplaced[0].current_owner.as_deref(), Some("B.cpp"));
        targets[0].current_owner = Some("B.cpp".into());
        assert!(order_matches(&evidence, &targets, &[]).is_empty());
        let mut duplicate = evidence.clone();
        let mut alias = duplicate.objects[0].functions[0].clone();
        alias.address = "0x0".into();
        alias.end = "0x20".into();
        duplicate.objects[0].functions.push(alias);
        assert!(
            duplicate
                .canonicalize(
                    &BTreeSet::from(["A.cpp".into()]),
                    &BTreeSet::from([helper_hash]),
                    true,
                )
                .is_err()
        );
    }
}
