//! Source-independent observations about function identity and translation-unit membership.
//!
//! This module deliberately stops before deciding whether a split may be changed. Existing
//! ownership, policy byte thresholds, `--only`, source-object availability and build results are
//! application concerns. Keeping the observations separate means an uncompilable project still
//! gets a useful inventory, and a rejected mutation does not erase what identified the unit.

use std::collections::{BTreeMap, BTreeSet, HashMap};

use serde::{Deserialize, Serialize};

use crate::analysis::{
    callgraph::NodeIndex,
    fingerprint::normalized_body,
    matching::{Match, MatchMethod, MatchResult, MatchTarget, MatchTier},
};

pub const IDENTIFICATION_SCHEMA: u32 = 1;
const EXECUTABLE_MODULE: &str = "main";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdentificationReport {
    pub schema: u32,
    pub source: String,
    pub target: String,
    pub attributions: Vec<FunctionAttribution>,
    pub units: Vec<UnitIdentification>,
}

impl IdentificationReport {
    pub fn empty(source: impl Into<String>, target: impl Into<String>) -> Self {
        Self {
            schema: IDENTIFICATION_SCHEMA,
            source: source.into(),
            target: target.into(),
            attributions: Vec::new(),
            units: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionAttribution {
    /// Stable within this source/target pair and suitable for references from unit records.
    pub id: String,
    pub target: FunctionLocation,
    pub source: SourceFunction,
    pub method: MatchMethod,
    pub tier: MatchTier,
    pub confidence: f32,
    pub evidence_count: u32,
    pub origin: AttributionOrigin,
    pub binary_supported: bool,
    pub independent: bool,
    /// True only when an alternative is close enough to make the selected
    /// identity non-decisive. Weaker runner-ups remain in `competing` without
    /// poisoning the unit-level result.
    pub ambiguous: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub competing: Option<CompetingAttribution>,
    pub source_weak: bool,
    pub target_weak: bool,
    pub template_instantiation: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_target_owner: Option<String>,
    pub evidence: Vec<EvidenceReference>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionLocation {
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceFunction {
    pub name: String,
    pub unit: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AttributionOrigin {
    InputName,
    NormalizedBody,
    StringReference,
    CallGraph,
    LinkOrder,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetingAttribution {
    pub source_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_unit: Option<String>,
    pub relative_score: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceReference {
    pub kind: String,
    pub detail: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnitIdentification {
    pub unit: String,
    pub autogenerated: bool,
    pub confidence: IdentificationConfidence,
    pub basis: IdentificationBasis,
    pub source_functions: u32,
    pub matched_functions: u32,
    pub strong_functions: u32,
    pub binary_functions: u32,
    pub independently_supported_functions: u32,
    pub name_only_functions: u32,
    pub candidates: Vec<CandidateSequence>,
    pub evidence: Vec<String>,
    pub competing_explanations: Vec<CompetingExplanation>,
    pub missing_members: Vec<MissingMember>,
    pub unresolved_helpers: Vec<String>,
    pub boundary_blockers: Vec<String>,
    pub application_blockers: Vec<String>,
}

impl UnitIdentification {
    pub fn absent(unit: impl Into<String>, source_functions: u32) -> Self {
        Self {
            unit: unit.into(),
            autogenerated: false,
            confidence: IdentificationConfidence::Absent,
            basis: IdentificationBasis::None,
            source_functions,
            matched_functions: 0,
            strong_functions: 0,
            binary_functions: 0,
            independently_supported_functions: 0,
            name_only_functions: 0,
            candidates: Vec::new(),
            evidence: Vec::new(),
            competing_explanations: Vec::new(),
            missing_members: Vec::new(),
            unresolved_helpers: Vec::new(),
            boundary_blockers: vec!["no target function is attributed to this source unit".into()],
            application_blockers: vec![
                "no target function is attributed to this source unit".into(),
            ],
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum IdentificationConfidence {
    Absent,
    Tentative,
    Corroborated,
    Ambiguous,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum IdentificationBasis {
    None,
    NamesOnly,
    Binary,
    Mixed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateSequence {
    pub module: String,
    pub source_section: String,
    pub section: String,
    pub start: String,
    pub end: String,
    pub attribution_ids: Vec<String>,
    pub matched_members: u32,
    pub target_functions_in_envelope: u32,
    pub contiguous_target_members: bool,
    pub left_source_edge_observed: bool,
    pub right_source_edge_observed: bool,
    pub left_target_edge: EdgeEvidence,
    pub right_target_edge: EdgeEvidence,
    pub unexplained_target_members: Vec<TargetMember>,
    pub current_owners: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdgeEvidence {
    pub supported: bool,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adjacent_attribution_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TargetMember {
    pub name: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetingExplanation {
    pub target_address: String,
    pub source_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_unit: Option<String>,
    pub relative_score: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MissingMember {
    pub source_name: String,
    pub section: String,
    pub address: String,
}

#[derive(Debug, Clone)]
struct SourceMember {
    name: String,
    section: String,
    address: u32,
    matched: bool,
}

/// Build the complete observation inventory directly from the function matcher.
pub fn identify_units(
    source: &MatchTarget,
    target: &MatchTarget,
    result: &MatchResult,
) -> IdentificationReport {
    let by_source: BTreeMap<NodeIndex, &Match> =
        result.matches.iter().map(|matched| (matched.source, matched)).collect();
    let mut source_members: BTreeMap<String, Vec<SourceMember>> = BTreeMap::new();
    // Seed from split ownership rather than call-graph membership. This keeps
    // data-only and empty code units in the complete identification inventory.
    for (_, _, _, split) in source.obj.sections.all_splits() {
        source_members.entry(split.unit.clone()).or_default();
    }
    for (node, function) in source.graph.iter() {
        let Some(unit) = source.unit_of(node) else { continue };
        source_members.entry(unit.to_string()).or_default().push(SourceMember {
            name: source.symbol_name(node).to_string(),
            section: source.obj.sections[function.section].name.clone(),
            address: function.address,
            matched: by_source.contains_key(&node),
        });
    }
    for members in source_members.values_mut() {
        members.sort_by_key(|member| (member.section.clone(), member.address));
    }

    let source_hash_counts = exact_hash_counts(source);
    let target_hash_counts = exact_hash_counts(target);
    let mut attributions = Vec::new();
    for matched in &result.matches {
        let Some(unit) = source.unit_of(matched.source) else { continue };
        attributions.push(attribution(
            source,
            target,
            matched,
            unit,
            &source_hash_counts,
            &target_hash_counts,
        ));
    }
    attributions.sort_by(|left, right| {
        left.target
            .module
            .cmp(&right.target.module)
            .then(left.target.section.cmp(&right.target.section))
            .then(left.target.address.cmp(&right.target.address))
            .then(left.source.unit.cmp(&right.source.unit))
    });

    let attributions_by_unit: BTreeMap<&str, Vec<&FunctionAttribution>> = source_members
        .keys()
        .map(|unit| {
            (unit.as_str(), attributions.iter().filter(|item| item.source.unit == *unit).collect())
        })
        .collect();
    let attributions_by_target: BTreeMap<(&str, &str, u32), &FunctionAttribution> = attributions
        .iter()
        .map(|item| {
            (
                (
                    item.target.module.as_str(),
                    item.target.section.as_str(),
                    parse_hex(&item.target.address),
                ),
                item,
            )
        })
        .collect();
    let units = source_members
        .iter()
        .map(|(unit, members)| {
            identify_unit(
                unit,
                members,
                attributions_by_unit.get(unit.as_str()).map(Vec::as_slice).unwrap_or_default(),
                target,
                &attributions_by_target,
                source.obj.is_unit_autogenerated(unit),
            )
        })
        .collect();

    IdentificationReport {
        schema: IDENTIFICATION_SCHEMA,
        source: source.name.clone(),
        target: target.name.clone(),
        attributions,
        units,
    }
}

fn attribution(
    source: &MatchTarget,
    target: &MatchTarget,
    matched: &Match,
    unit: &str,
    source_hash_counts: &HashMap<u64, u32>,
    target_hash_counts: &HashMap<u64, u32>,
) -> FunctionAttribution {
    let source_node = source.graph.node(matched.source);
    let target_node = target.graph.node(matched.target);
    let source_name = source.symbol_name(matched.source);
    let target_section = target.obj.sections[target_node.section].name.clone();
    let source_section = source.obj.sections[source_node.section].name.clone();
    let competing = matched.runner_up.map(|alternative| CompetingAttribution {
        source_name: source.symbol_name(alternative.source).to_string(),
        source_unit: source.unit_of(alternative.source).map(str::to_string),
        relative_score: round(alternative.relative_score),
    });
    let template = is_template(source, matched.source) || is_template(target, matched.target);
    let source_weak = source.is_weak(matched.source);
    let target_weak = target.is_weak(matched.target);
    let unique_exact =
        unique_exact_body(source, target, matched, source_hash_counts, target_hash_counts);
    let binary_supported = matched.method != MatchMethod::Name || matched.distinctive_body;
    let independent = !source_weak
        && !target_weak
        && !template
        && (unique_exact
            || matched.method == MatchMethod::StringRef
            || (matches!(matched.method, MatchMethod::CallSite | MatchMethod::CallerSite)
                && matched.evidence >= 2
                && !matched.is_contested()));
    let mut evidence = vec![EvidenceReference {
        kind: matched.method.as_str().to_string(),
        detail: method_detail(matched.method).to_string(),
    }];
    if unique_exact && matched.method != MatchMethod::ExactHash {
        evidence.push(EvidenceReference {
            kind: "unique-exact-body".into(),
            detail: "relocation-masked bodies are equal and unique in both binaries".into(),
        });
    } else if matched.distinctive_body && matched.method != MatchMethod::ExactHash {
        evidence.push(EvidenceReference {
            kind: "normalized-body".into(),
            detail: "relocation-masked bodies are equal but do not uniquely identify the pair"
                .into(),
        });
    }
    if matched.evidence > 1 {
        evidence.push(EvidenceReference {
            kind: "corroboration".into(),
            detail: format!("{} independently agreeing neighbours", matched.evidence),
        });
    }
    FunctionAttribution {
        id: format!(
            "{}:{}:{}<-{}:{}:{}",
            EXECUTABLE_MODULE,
            target_section,
            hex(target_node.address),
            EXECUTABLE_MODULE,
            source_section,
            hex(source_node.address)
        ),
        target: FunctionLocation {
            module: EXECUTABLE_MODULE.into(),
            section: target_section,
            address: hex(target_node.address),
            end: hex(target_node.address + target_node.size),
        },
        source: SourceFunction {
            name: source_name.to_string(),
            unit: unit.to_string(),
            module: EXECUTABLE_MODULE.into(),
            section: source_section,
            address: hex(source_node.address),
            end: hex(source_node.address + source_node.size),
        },
        method: matched.method,
        tier: matched.tier(),
        confidence: round(matched.confidence),
        evidence_count: matched.evidence,
        origin: origin(matched.method),
        binary_supported,
        independent,
        ambiguous: matched.is_contested(),
        competing,
        source_weak,
        target_weak,
        template_instantiation: template,
        current_target_owner: target.unit_of(matched.target).map(str::to_string),
        evidence,
    }
}

fn identify_unit(
    unit: &str,
    members: &[SourceMember],
    attributions: &[&FunctionAttribution],
    target: &MatchTarget,
    attributions_by_target: &BTreeMap<(&str, &str, u32), &FunctionAttribution>,
    autogenerated: bool,
) -> UnitIdentification {
    let strong_functions = attributions
        .iter()
        .filter(|item| item.binary_supported && item.tier != MatchTier::Candidate)
        .count() as u32;
    let binary_functions = attributions.iter().filter(|item| item.binary_supported).count() as u32;
    let independently_supported_functions =
        attributions.iter().filter(|item| item.independent).count() as u32;
    let named_functions =
        attributions.iter().filter(|item| item.origin == AttributionOrigin::InputName).count()
            as u32;
    let name_only_functions = attributions
        .iter()
        .filter(|item| item.origin == AttributionOrigin::InputName && !item.binary_supported)
        .count() as u32;
    let competing_explanations: Vec<CompetingExplanation> = attributions
        .iter()
        .filter_map(|item| {
            let competing = item.competing.as_ref()?;
            Some(CompetingExplanation {
                target_address: item.target.address.clone(),
                source_name: competing.source_name.clone(),
                source_unit: competing.source_unit.clone(),
                relative_score: competing.relative_score,
            })
        })
        .collect();
    let basis = match (binary_functions, named_functions) {
        (0, 0) => IdentificationBasis::None,
        (0, _) => IdentificationBasis::NamesOnly,
        (_, 0) => IdentificationBasis::Binary,
        _ => IdentificationBasis::Mixed,
    };
    let confidence = confidence_for(
        attributions.len(),
        independently_supported_functions,
        attributions.iter().any(|item| item.ambiguous),
    );

    let missing_members: Vec<MissingMember> = members
        .iter()
        .filter(|member| !member.matched)
        .map(|member| MissingMember {
            source_name: member.name.clone(),
            section: member.section.clone(),
            address: hex(member.address),
        })
        .collect();
    let unresolved_helpers: Vec<String> = attributions
        .iter()
        .filter(|item| item.source_weak || item.target_weak || item.template_instantiation)
        .map(|item| item.id.clone())
        .collect();

    let mut grouped: BTreeMap<(&str, &str, &str), Vec<&FunctionAttribution>> = BTreeMap::new();
    for item in attributions {
        grouped
            .entry((&item.target.module, &item.source.section, &item.target.section))
            .or_default()
            .push(item);
    }
    let candidates: Vec<CandidateSequence> = grouped
        .into_values()
        .map(|items| candidate_sequence(unit, items, members, target, attributions_by_target))
        .collect();

    let mut boundary_blockers = Vec::new();
    if attributions.is_empty() {
        boundary_blockers.push("no target function is attributed to this source unit".into());
    }
    if basis == IdentificationBasis::NamesOnly {
        boundary_blockers.push("identity is supported only by pre-existing names".into());
    }
    if attributions.iter().any(|item| item.ambiguous) {
        boundary_blockers
            .push("one or more function identities have a competing explanation".into());
    }
    if !missing_members.is_empty() {
        boundary_blockers.push("some source members have no target attribution".into());
    }
    for candidate in &candidates {
        if !candidate.contiguous_target_members {
            boundary_blockers.push(format!(
                "{} has unmatched target functions inside the observed envelope",
                candidate.section
            ));
        }
        if !candidate.left_source_edge_observed {
            boundary_blockers
                .push(format!("{} left source edge is not observed", candidate.section));
        }
        if !candidate.right_source_edge_observed {
            boundary_blockers
                .push(format!("{} right source edge is not observed", candidate.section));
        }
        if !candidate.left_target_edge.supported {
            boundary_blockers.push(format!(
                "{} left target edge is unsupported: {}",
                candidate.section, candidate.left_target_edge.reason
            ));
        }
        if !candidate.right_target_edge.supported {
            boundary_blockers.push(format!(
                "{} right target edge is unsupported: {}",
                candidate.section, candidate.right_target_edge.reason
            ));
        }
    }
    boundary_blockers.sort();
    boundary_blockers.dedup();

    let mut application_blockers = Vec::new();
    if !boundary_blockers.is_empty() {
        application_blockers.push("boundary evidence is incomplete".into());
    }
    let foreign: BTreeSet<&str> = attributions
        .iter()
        .filter_map(|item| item.current_target_owner.as_deref())
        .filter(|owner| *owner != unit)
        .collect();
    if !foreign.is_empty() {
        application_blockers.push(format!(
            "observed target members are currently owned by {}",
            foreign.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    if !unresolved_helpers.is_empty() {
        application_blockers.push("weak or template members need emitted-owner evidence".into());
    }

    UnitIdentification {
        unit: unit.to_string(),
        autogenerated,
        confidence,
        basis,
        source_functions: members.len() as u32,
        matched_functions: attributions.len() as u32,
        strong_functions,
        binary_functions,
        independently_supported_functions,
        name_only_functions,
        candidates,
        evidence: attributions.iter().map(|item| item.id.clone()).collect(),
        competing_explanations,
        missing_members,
        unresolved_helpers,
        boundary_blockers,
        application_blockers,
    }
}

fn candidate_sequence(
    unit: &str,
    mut items: Vec<&FunctionAttribution>,
    source_members: &[SourceMember],
    target: &MatchTarget,
    attributions_by_target: &BTreeMap<(&str, &str, u32), &FunctionAttribution>,
) -> CandidateSequence {
    items.sort_by_key(|item| parse_hex(&item.target.address));
    let first = items[0];
    let last = items[items.len() - 1];
    let start = parse_hex(&first.target.address);
    let end = parse_hex(&last.target.end);
    let section = first.target.section.as_str();
    let target_members: Vec<(NodeIndex, _)> = target
        .graph
        .iter()
        .filter(|(_, node)| {
            target.obj.sections[node.section].name == section
                && node.address >= start
                && node.address < end
        })
        .collect();
    let mut section_members: Vec<(NodeIndex, _)> = target
        .graph
        .iter()
        .filter(|(_, node)| target.obj.sections[node.section].name == section)
        .collect();
    section_members.sort_by_key(|(_, node)| node.address);
    let attributed_target: BTreeSet<u32> =
        items.iter().map(|item| parse_hex(&item.target.address)).collect();
    let unexplained_target_members = target_members
        .iter()
        .filter(|(_, node)| !attributed_target.contains(&node.address))
        .map(|(node, function)| TargetMember {
            name: target.symbol_name(*node).to_string(),
            address: hex(function.address),
            end: hex(function.address + function.size),
        })
        .collect::<Vec<_>>();

    let source_section = first.source.section.as_str();
    let edge_members: Vec<&SourceMember> =
        source_members.iter().filter(|member| member.section == source_section).collect();
    let attributed_source: BTreeSet<u32> =
        items.iter().map(|item| parse_hex(&item.source.address)).collect();
    let left_source_edge_observed =
        edge_members.first().is_some_and(|member| attributed_source.contains(&member.address));
    let right_source_edge_observed =
        edge_members.last().is_some_and(|member| attributed_source.contains(&member.address));
    let current_owners: BTreeSet<String> = target_members
        .iter()
        .filter_map(|(node, _)| target.unit_of(*node).map(str::to_string))
        .collect();
    let left_neighbor = section_members.iter().rev().find(|(_, node)| node.address < start);
    let right_neighbor = section_members.iter().find(|(_, node)| node.address >= end);
    let left_target_edge = edge_evidence(
        unit,
        first.target.module.as_str(),
        section,
        left_neighbor,
        "candidate starts at the beginning of the target section",
        attributions_by_target,
    );
    let right_target_edge = edge_evidence(
        unit,
        first.target.module.as_str(),
        section,
        right_neighbor,
        "candidate ends at the end of the target section",
        attributions_by_target,
    );

    CandidateSequence {
        module: first.target.module.clone(),
        source_section: first.source.section.clone(),
        section: first.target.section.clone(),
        start: first.target.address.clone(),
        end: last.target.end.clone(),
        attribution_ids: items.iter().map(|item| item.id.clone()).collect(),
        matched_members: items.len() as u32,
        target_functions_in_envelope: target_members.len() as u32,
        contiguous_target_members: unexplained_target_members.is_empty(),
        left_source_edge_observed,
        right_source_edge_observed,
        left_target_edge,
        right_target_edge,
        unexplained_target_members,
        current_owners: current_owners.into_iter().collect(),
    }
}

fn edge_evidence(
    unit: &str,
    module: &str,
    section: &str,
    neighbor: Option<&(NodeIndex, &crate::analysis::callgraph::FunctionNode)>,
    section_boundary_reason: &str,
    attributions_by_target: &BTreeMap<(&str, &str, u32), &FunctionAttribution>,
) -> EdgeEvidence {
    let Some((_, node)) = neighbor else {
        return EdgeEvidence {
            supported: true,
            reason: section_boundary_reason.into(),
            adjacent_attribution_id: None,
        };
    };
    let Some(attribution) = attributions_by_target.get(&(module, section, node.address)) else {
        return EdgeEvidence {
            supported: false,
            reason: format!("adjacent target function {} is not attributed", hex(node.address)),
            adjacent_attribution_id: None,
        };
    };
    if attribution.source.unit == unit {
        return EdgeEvidence {
            supported: false,
            reason: "the adjacent target function is attributed to the same source unit".into(),
            adjacent_attribution_id: Some(attribution.id.clone()),
        };
    }
    if !attribution.independent || attribution.ambiguous {
        return EdgeEvidence {
            supported: false,
            reason: format!(
                "the adjacent {} attribution is not independent and decisive",
                attribution.source.unit
            ),
            adjacent_attribution_id: Some(attribution.id.clone()),
        };
    }
    EdgeEvidence {
        supported: true,
        reason: format!(
            "adjacent target function is independently attributed to {}",
            attribution.source.unit
        ),
        adjacent_attribution_id: Some(attribution.id.clone()),
    }
}

fn confidence_for(
    matches: usize,
    independently_supported_functions: u32,
    contested: bool,
) -> IdentificationConfidence {
    if matches == 0 {
        IdentificationConfidence::Absent
    } else if contested {
        IdentificationConfidence::Ambiguous
    } else if independently_supported_functions >= 2 {
        IdentificationConfidence::Corroborated
    } else {
        IdentificationConfidence::Tentative
    }
}

fn exact_hash_counts(target: &MatchTarget) -> HashMap<u64, u32> {
    let mut counts = HashMap::new();
    for fingerprint in &target.fingerprints {
        if fingerprint.instruction_count >= 4 {
            *counts.entry(fingerprint.exact_hash).or_default() += 1;
        }
    }
    counts
}

fn unique_exact_body(
    source: &MatchTarget,
    target: &MatchTarget,
    matched: &Match,
    source_hash_counts: &HashMap<u64, u32>,
    target_hash_counts: &HashMap<u64, u32>,
) -> bool {
    let source_fingerprint = &source.fingerprints[matched.source as usize];
    let target_fingerprint = &target.fingerprints[matched.target as usize];
    if source_fingerprint.instruction_count < 4
        || source_fingerprint.exact_hash != target_fingerprint.exact_hash
        || source_hash_counts.get(&source_fingerprint.exact_hash) != Some(&1)
        || target_hash_counts.get(&target_fingerprint.exact_hash) != Some(&1)
    {
        return false;
    }
    let source_node = source.graph.node(matched.source);
    let target_node = target.graph.node(matched.target);
    source.obj.symbols[source_node.symbol].size_known
        && target.obj.symbols[target_node.symbol].size_known
        && source_node.size == target_node.size
        && normalized_body(&source.obj, source_node) == normalized_body(&target.obj, target_node)
}

fn origin(method: MatchMethod) -> AttributionOrigin {
    match method {
        MatchMethod::Name => AttributionOrigin::InputName,
        MatchMethod::ExactHash => AttributionOrigin::NormalizedBody,
        MatchMethod::StringRef => AttributionOrigin::StringReference,
        MatchMethod::CallSite | MatchMethod::CallerSite => AttributionOrigin::CallGraph,
        MatchMethod::Layout => AttributionOrigin::LinkOrder,
    }
}

fn method_detail(method: MatchMethod) -> &'static str {
    match method {
        MatchMethod::Name => "the two input binaries already carry the same name",
        MatchMethod::ExactHash => "relocation-masked instruction bodies are uniquely equal",
        MatchMethod::StringRef => "a uniquely referenced string identifies both functions",
        MatchMethod::CallSite => "position among calls from an already matched function agrees",
        MatchMethod::CallerSite => "matched caller/callee topology leaves one pairing",
        MatchMethod::Layout => "position between already matched link-order anchors agrees",
    }
}

fn is_template(target: &MatchTarget, node: NodeIndex) -> bool {
    let symbol = &target.obj.symbols[target.graph.node(node).symbol];
    let name = symbol.demangled_name.as_deref().unwrap_or(&symbol.name);
    let callable = callable_name(name);
    callable.contains('<') && callable.contains('>')
}

/// Return the qualified callable, excluding a demangler's optional return type.
/// A simple split on `(` is not enough: `rstl::rc_ptr<T> C::Get()` is an
/// ordinary method whose return type happens to be a template. The separator
/// we want is the last space outside angle brackets before the argument list.
fn callable_name(name: &str) -> &str {
    let declaration = name.split_once('(').map_or(name, |(declaration, _)| declaration);
    let mut depth = 0_u32;
    let mut separator = None;
    for (offset, character) in declaration.char_indices() {
        match character {
            '<' => depth += 1,
            '>' => depth = depth.saturating_sub(1),
            ' ' if depth == 0 => separator = Some(offset + character.len_utf8()),
            _ => {}
        }
    }
    separator.map_or(declaration, |offset| &declaration[offset..])
}

fn round(value: f32) -> f32 { (value * 1000.0).round() / 1000.0 }

fn hex(value: u32) -> String { format!("{value:#010X}") }

fn parse_hex(value: &str) -> u32 {
    u32::from_str_radix(value.trim_start_matches("0x").trim_start_matches("0X"), 16).unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use decomp_toolkit::obj::{
        ObjArchitecture, ObjInfo, ObjKind, ObjRelocations, ObjSection, ObjSectionKind, ObjSplit,
        ObjSplits, ObjSymbol, ObjSymbolFlagSet, ObjSymbolFlags, ObjSymbolKind,
    };

    use super::*;

    fn section(
        name: &str,
        kind: ObjSectionKind,
        index: u32,
        base: u32,
        size: u32,
        unit: &str,
    ) -> ObjSection {
        let mut splits = ObjSplits::default();
        splits.push(base, ObjSplit {
            unit: unit.into(),
            end: base + size,
            align: None,
            common: false,
            autogenerated: false,
            skip: false,
            rename: None,
        });
        ObjSection {
            name: name.into(),
            kind,
            address: u64::from(base),
            size: u64::from(size),
            data: vec![0; size as usize],
            align: 4,
            elf_index: index,
            relocations: ObjRelocations::default(),
            virtual_address: None,
            file_offset: 0,
            section_known: true,
            splits,
        }
    }

    fn function(name: &str, section: u32, address: u32, size: u32) -> ObjSymbol {
        ObjSymbol {
            name: name.into(),
            address: u64::from(address),
            section: Some(section),
            size: u64::from(size),
            size_known: true,
            kind: ObjSymbolKind::Function,
            ..Default::default()
        }
    }

    fn target(name: &str, symbols: Vec<ObjSymbol>, sections: Vec<ObjSection>) -> MatchTarget {
        MatchTarget::new(
            name.into(),
            ObjInfo::new(
                ObjKind::Executable,
                ObjArchitecture::PowerPc,
                name.into(),
                symbols,
                sections,
            ),
        )
    }

    fn matched(
        source: NodeIndex,
        target: NodeIndex,
        method: MatchMethod,
        runner_up: Option<(NodeIndex, f32)>,
    ) -> Match {
        Match {
            source,
            target,
            method,
            confidence: 1.0,
            evidence: 1,
            round: 0,
            distinctive_body: method == MatchMethod::ExactHash,
            runner_up: runner_up.map(|(source, relative_score)| {
                crate::analysis::matching::Alternative { source, relative_score }
            }),
        }
    }

    fn result(matches: Vec<Match>, source_len: usize, target_len: usize) -> MatchResult {
        let mut source_to_target = vec![None; source_len];
        let mut target_to_source = vec![None; target_len];
        for item in &matches {
            source_to_target[item.source as usize] = Some(item.target);
            target_to_source[item.target as usize] = Some(item.source);
        }
        MatchResult { matches, source_to_target, target_to_source, rounds: 1 }
    }

    #[test]
    fn names_alone_are_not_independent_corroboration() {
        assert_eq!(confidence_for(6, 0, false), IdentificationConfidence::Tentative);
    }

    #[test]
    fn a_template_return_type_does_not_make_an_ordinary_method_a_template() {
        assert_eq!(
            callable_name("rstl::rc_ptr<IMetaTrans> CTransitionDatabaseGame::GetMetaTrans() const"),
            "CTransitionDatabaseGame::GetMetaTrans"
        );
        assert!(
            !callable_name(
                "rstl::rc_ptr<IMetaTrans> CTransitionDatabaseGame::GetMetaTrans() const"
            )
            .contains('<')
        );
        assert!(callable_name("void rstl::sort<int>(int*, int*)").contains('<'));
        assert!(callable_name("rstl::vector<int>::size() const").contains('<'));
    }

    #[test]
    fn two_binary_members_can_corroborate_a_unit() {
        assert_eq!(confidence_for(2, 2, false), IdentificationConfidence::Corroborated);
    }

    #[test]
    fn a_competing_explanation_remains_ambiguous() {
        assert_eq!(confidence_for(8, 8, true), IdentificationConfidence::Ambiguous);
    }

    #[test]
    fn a_weak_runner_up_is_retained_without_making_the_unit_ambiguous() {
        let source = target(
            "source",
            vec![function("A", 0, 0x1000, 4), function("Other", 0, 0x1004, 4)],
            vec![section(".text", ObjSectionKind::Code, 0, 0x1000, 8, "A.cpp")],
        );
        let target = target("target", vec![function("fn_2000", 0, 0x2000, 4)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x2000,
            4,
            "unknown.cpp",
        )]);
        let report = identify_units(
            &source,
            &target,
            &result(vec![matched(0, 0, MatchMethod::CallSite, Some((1, 0.2)))], 2, 1),
        );
        let unit = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        assert_ne!(unit.confidence, IdentificationConfidence::Ambiguous);
        assert_eq!(unit.competing_explanations.len(), 1, "the diagnostic runner-up is retained");
        assert!(!report.attributions[0].ambiguous);
    }

    #[test]
    fn source_sections_form_separate_candidate_sequences() {
        let source = target(
            "source",
            vec![function("Init", 0, 0x1000, 4), function("Text", 1, 0x2000, 4)],
            vec![
                section(".init", ObjSectionKind::Code, 0, 0x1000, 4, "A.cpp"),
                section(".text", ObjSectionKind::Code, 1, 0x2000, 4, "A.cpp"),
            ],
        );
        let target = target(
            "target",
            vec![function("fn_3000", 0, 0x3000, 4), function("fn_3004", 0, 0x3004, 4)],
            vec![section(".text", ObjSectionKind::Code, 0, 0x3000, 8, "unknown.cpp")],
        );
        let report = identify_units(
            &source,
            &target,
            &result(
                vec![
                    matched(0, 0, MatchMethod::ExactHash, None),
                    matched(1, 1, MatchMethod::ExactHash, None),
                ],
                2,
                2,
            ),
        );
        let unit = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        assert_eq!(unit.candidates.len(), 2);
        assert_eq!(
            unit.candidates
                .iter()
                .map(|item| item.source_section.as_str())
                .collect::<BTreeSet<_>>(),
            BTreeSet::from([".init", ".text"]),
        );
        assert!(
            unit.candidates
                .iter()
                .all(|item| { item.left_source_edge_observed && item.right_source_edge_observed })
        );
    }

    #[test]
    fn a_candidate_cannot_borrow_source_edges_from_another_target_section() {
        let source = target(
            "source",
            vec![function("First", 0, 0x1000, 4), function("Last", 0, 0x1004, 4)],
            vec![section(".text", ObjSectionKind::Code, 0, 0x1000, 8, "A.cpp")],
        );
        let target = target(
            "target",
            vec![function("fn_2000", 0, 0x2000, 4), function("fn_3000", 1, 0x3000, 4)],
            vec![
                section(".init", ObjSectionKind::Code, 0, 0x2000, 4, "unknown.cpp"),
                section(".text", ObjSectionKind::Code, 1, 0x3000, 4, "unknown.cpp"),
            ],
        );
        let report = identify_units(
            &source,
            &target,
            &result(
                vec![
                    matched(0, 0, MatchMethod::ExactHash, None),
                    matched(1, 1, MatchMethod::ExactHash, None),
                ],
                2,
                2,
            ),
        );
        let unit = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        let init = unit.candidates.iter().find(|candidate| candidate.section == ".init").unwrap();
        assert!(init.left_source_edge_observed);
        assert!(!init.right_source_edge_observed);
        let text = unit.candidates.iter().find(|candidate| candidate.section == ".text").unwrap();
        assert!(!text.left_source_edge_observed);
        assert!(text.right_source_edge_observed);
    }

    #[test]
    fn data_only_units_remain_in_the_complete_inventory() {
        let source = target("source", vec![function("A", 0, 0x1000, 4)], vec![
            section(".text", ObjSectionKind::Code, 0, 0x1000, 4, "A.cpp"),
            section(".data", ObjSectionKind::Data, 1, 0x2000, 4, "Data.cpp"),
        ]);
        let target = target("target", vec![function("A", 0, 0x3000, 4)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x3000,
            4,
            "A.cpp",
        )]);
        let report = identify_units(
            &source,
            &target,
            &result(vec![matched(0, 0, MatchMethod::Name, None)], 1, 1),
        );
        let named = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        assert_eq!(named.basis, IdentificationBasis::NamesOnly);
        assert_eq!(named.strong_functions, 0, "input names are not strong binary evidence");
        let data = report.units.iter().find(|unit| unit.unit == "Data.cpp").unwrap();
        assert_eq!(data.source_functions, 0);
        assert_eq!(data.confidence, IdentificationConfidence::Absent);
    }

    #[test]
    fn a_name_match_retains_independent_exact_body_evidence() {
        let source = target("source", vec![function("A", 0, 0x1000, 16)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x1000,
            16,
            "A.cpp",
        )]);
        let target = target("target", vec![function("A", 0, 0x2000, 16)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x2000,
            16,
            "A.cpp",
        )]);
        let mut item = matched(0, 0, MatchMethod::Name, None);
        item.distinctive_body = true;
        let report = identify_units(&source, &target, &result(vec![item], 1, 1));
        let attribution = &report.attributions[0];
        assert_eq!(attribution.origin, AttributionOrigin::InputName);
        assert!(attribution.binary_supported);
        assert!(attribution.independent);
        assert_eq!(attribution.target.module, "main");
        assert_eq!(attribution.source.module, "main");
        assert!(attribution.id.starts_with("main:.text:0x00002000<-main:.text:"));
        assert!(attribution.evidence.iter().any(|item| item.kind == "unique-exact-body"));
        let unit = &report.units[0];
        assert_eq!(unit.basis, IdentificationBasis::Mixed);
        assert_eq!(unit.binary_functions, 1);
        assert_eq!(unit.strong_functions, 1);
        assert_eq!(unit.name_only_functions, 0);
    }

    #[test]
    fn a_weak_exact_body_does_not_corroborate_emitted_tu_ownership() {
        let mut source_symbol = function("Weak", 0, 0x1000, 16);
        source_symbol.flags = ObjSymbolFlagSet(ObjSymbolFlags::Weak.into());
        let mut target_symbol = function("Weak", 0, 0x2000, 16);
        target_symbol.flags = ObjSymbolFlagSet(ObjSymbolFlags::Weak.into());
        let source = target("source", vec![source_symbol], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x1000,
            16,
            "A.cpp",
        )]);
        let target = target("target", vec![target_symbol], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x2000,
            16,
            "unknown.cpp",
        )]);
        let mut item = matched(0, 0, MatchMethod::Name, None);
        item.distinctive_body = true;
        let report = identify_units(&source, &target, &result(vec![item], 1, 1));
        assert!(report.attributions[0].binary_supported);
        assert!(!report.attributions[0].independent);
        assert_eq!(report.units[0].confidence, IdentificationConfidence::Tentative);
        assert_eq!(report.units[0].unresolved_helpers.len(), 1);
    }
}
