//! Source-independent observations about function identity and translation-unit membership.
//!
//! This module deliberately stops before deciding whether a split may be changed. Existing
//! ownership, policy byte thresholds, `--only`, source-object availability and build results are
//! application concerns. Keeping the observations separate means an uncompilable project still
//! gets a useful inventory, and a rejected mutation does not erase what identified the unit.

use std::{
    collections::{BTreeMap, BTreeSet, HashMap},
    path::Path,
};

use anyhow::{Result, bail};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::analysis::{
    callgraph::NodeIndex,
    fingerprint::normalized_body,
    matching::{
        CONTESTED_MARGIN, Match, MatchMethod, MatchResult, MatchTarget, MatchTier, classify_tier,
    },
};

pub const IDENTIFICATION_SCHEMA: u32 = 2;
const EXECUTABLE_MODULE: &str = "main";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdentificationReport {
    pub schema: u32,
    pub source: String,
    pub target: String,
    pub attributions: Vec<FunctionAttribution>,
    #[serde(default)]
    pub source_functions: Vec<SourceFunctionObservation>,
    #[serde(default)]
    pub target_functions: Vec<TargetFunctionObservation>,
    pub units: Vec<UnitIdentification>,
}

impl IdentificationReport {
    pub fn empty(source: impl Into<String>, target: impl Into<String>) -> Self {
        Self {
            schema: IDENTIFICATION_SCHEMA,
            source: source.into(),
            target: target.into(),
            attributions: Vec::new(),
            source_functions: Vec::new(),
            target_functions: Vec::new(),
            units: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionAttribution {
    /// Stable within this source/target pair and suitable for references from unit records.
    pub id: String,
    pub target: FunctionLocation,
    pub source: SourceFunction,
    pub method: MatchMethod,
    pub tier: MatchTier,
    pub confidence: f32,
    pub evidence_count: u32,
    pub origin: AttributionOrigin,
    /// Raw observation used to derive `binary_supported`. Kept separately so a
    /// serialized diagnostic flag can never become policy input when evidence
    /// is loaded again.
    #[serde(default)]
    pub distinctive_body: bool,
    /// The normalized body is equal and unique in both binaries.
    #[serde(default)]
    pub unique_exact_body: bool,
    pub binary_supported: bool,
    pub independent: bool,
    /// True only when an alternative is close enough to make the selected
    /// identity non-decisive. Weaker runner-ups remain in `competing` without
    /// poisoning the unit-level result.
    pub ambiguous: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub competing: Option<CompetingAttribution>,
    pub source_weak: bool,
    pub target_weak: bool,
    pub template_instantiation: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_target_owner: Option<String>,
    pub evidence: Vec<EvidenceReference>,
}

/// Canonical address used by ownership policy. The module is explicit even
/// though Prime currently has one executable module; later REL support must
/// not make two identical section addresses alias one another.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct AddressKey {
    pub module: String,
    pub section: String,
    pub address: u32,
}

/// A validated, canonicalized identification report and its address indexes.
///
/// Fields such as `independent`, unit counts and confidence are serialized for
/// people and old tooling, but are recomputed here before any migration policy
/// consumes them. The report digest is therefore a digest of canonical facts,
/// not of whichever aggregate values an input happened to claim.
#[derive(Debug, Clone)]
pub struct ObservationIndex {
    report: IdentificationReport,
    digest: String,
    by_id: BTreeMap<String, usize>,
    by_target: BTreeMap<AddressKey, usize>,
    by_unit: BTreeMap<String, usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ObservationReference {
    pub schema: u32,
    pub sha256: String,
    /// Path used while the run is active. Published summaries replace this
    /// with a run-relative path so copied run directories remain readable.
    pub file: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TargetExtent {
    pub module: String,
    pub section: String,
    pub start: u32,
    pub end: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TargetFunctionObservation {
    pub name: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_owner: Option<String>,
    #[serde(default)]
    pub owner_autogenerated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceFunctionObservation {
    pub name: String,
    pub unit: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ClaimClass {
    IndependentlyAttributed,
    SharedHelper,
    ConflictingAttribution,
    UnresolvedFunction,
    Padding,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClaimRecord {
    pub module: String,
    pub section: String,
    pub start: String,
    pub end: String,
    pub class: ClaimClass,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attribution_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributed_unit: Option<String>,
    pub retained: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct OwnershipAssessment {
    pub observation_sha256: String,
    pub records: Vec<ClaimRecord>,
    pub independent_members: u32,
    pub padding_bytes: u32,
    pub retained_questionable: u32,
    pub complete_membership: bool,
    pub supported_edges: u32,
    pub new_shared_helpers: u32,
    pub new_conflicts: u32,
    pub new_unresolved: u32,
}

impl OwnershipAssessment {
    pub fn permits_automatic_claim(&self) -> bool {
        self.independent_members > 0
            && self.new_shared_helpers == 0
            && self.new_conflicts == 0
            && self.new_unresolved == 0
    }
}

impl ObservationIndex {
    pub fn load_self_contained(
        report: IdentificationReport,
        source: &str,
        target: &str,
    ) -> Result<Self> {
        let expected = report.units.iter().map(|unit| unit.unit.clone()).collect();
        Self::load(report, source, target, &expected)
    }

    pub fn load(
        mut report: IdentificationReport,
        source: &str,
        target: &str,
        expected_units: &BTreeSet<String>,
    ) -> Result<Self> {
        if report.schema != IDENTIFICATION_SCHEMA {
            bail!(
                "identification schema {} is incompatible; this build understands {IDENTIFICATION_SCHEMA}",
                report.schema
            );
        }
        if report.source != source || report.target != target {
            bail!("Identification source/target does not match its enclosing evidence");
        }
        report.attributions.sort_by(|left, right| left.id.cmp(&right.id));

        let mut by_id = BTreeMap::new();
        let mut by_target = BTreeMap::new();
        let mut source_locations = BTreeSet::new();
        let mut source_functions = BTreeSet::new();
        for function in &mut report.source_functions {
            let start =
                parse_address_checked(&function.address, "source function", &function.name)?;
            let end = parse_address_checked(&function.end, "source function", &function.name)?;
            if !expected_units.contains(&function.unit)
                || function.module.is_empty()
                || function.section.is_empty()
                || end <= start
            {
                bail!("Source function {} has an invalid extent or unit", function.name);
            }
            if !source_functions.insert((
                function.module.clone(),
                function.section.clone(),
                start,
                end,
                function.unit.clone(),
            )) {
                bail!("Identification contains a duplicate source function extent");
            }
            function.address = hex(start);
            function.end = hex(end);
        }
        for pair in source_functions.iter().collect::<Vec<_>>().windows(2) {
            let (left, right) = (pair[0], pair[1]);
            if left.0 == right.0 && left.1 == right.1 && left.3 > right.2 {
                bail!("Identification contains overlapping source function extents");
            }
        }
        let mut target_functions = BTreeSet::new();
        let mut target_owners = BTreeMap::new();
        for function in &mut report.target_functions {
            let start =
                parse_address_checked(&function.address, "target function", &function.name)?;
            let end = parse_address_checked(&function.end, "target function", &function.name)?;
            if function.module.is_empty()
                || function.section.is_empty()
                || end <= start
                || (function.current_owner.is_none() && function.owner_autogenerated)
            {
                bail!("Target function {} has an invalid extent", function.name);
            }
            if !target_functions.insert((
                function.module.clone(),
                function.section.clone(),
                start,
                end,
            )) {
                bail!("Identification contains a duplicate target function extent");
            }
            if target_owners
                .insert(
                    (function.module.clone(), function.section.clone(), start),
                    function.current_owner.clone(),
                )
                .is_some()
            {
                bail!("Identification contains two target functions at one address");
            }
            function.address = hex(start);
            function.end = hex(end);
        }
        for pair in target_functions.iter().collect::<Vec<_>>().windows(2) {
            let (left, right) = (pair[0], pair[1]);
            if left.0 == right.0 && left.1 == right.1 && left.3 > right.2 {
                bail!("Identification contains overlapping target function extents");
            }
        }
        report.source_functions.sort_by(|left, right| {
            (&left.module, &left.section, &left.address, &left.end, &left.unit, &left.name).cmp(&(
                &right.module,
                &right.section,
                &right.address,
                &right.end,
                &right.unit,
                &right.name,
            ))
        });
        report.target_functions.sort_by(|left, right| {
            (&left.module, &left.section, &left.address, &left.end, &left.name).cmp(&(
                &right.module,
                &right.section,
                &right.address,
                &right.end,
                &right.name,
            ))
        });
        for (index, item) in report.attributions.iter_mut().enumerate() {
            validate_location(&item.target, "target", &item.id)?;
            validate_source(&item.source, &item.id)?;
            if !expected_units.contains(&item.source.unit) {
                bail!(
                    "Identification attributes {} to unknown source unit {}",
                    item.id,
                    item.source.unit
                );
            }
            if by_id.insert(item.id.clone(), index).is_some() {
                bail!("Identification contains duplicate attribution {}", item.id);
            }
            let key = AddressKey {
                module: item.target.module.clone(),
                section: item.target.section.clone(),
                address: parse_address_checked(&item.target.address, "target", &item.id)?,
            };
            if by_target.insert(key, index).is_some() {
                bail!("Identification contains two attributions for one target function");
            }
            let target_start = parse_address_checked(&item.target.address, "target", &item.id)?;
            let target_end = parse_address_checked(&item.target.end, "target", &item.id)?;
            if !target_functions.contains(&(
                item.target.module.clone(),
                item.target.section.clone(),
                target_start,
                target_end,
            )) {
                bail!("Attribution {} is absent from the target function inventory", item.id);
            }
            let source_key = (
                item.source.module.clone(),
                item.source.section.clone(),
                parse_address_checked(&item.source.address, "source", &item.id)?,
            );
            if !source_locations.insert(source_key) {
                bail!("Identification contains two attributions for one source function");
            }
            let source_start = parse_address_checked(&item.source.address, "source", &item.id)?;
            let source_end = parse_address_checked(&item.source.end, "source", &item.id)?;
            if !source_functions.contains(&(
                item.source.module.clone(),
                item.source.section.clone(),
                source_start,
                source_end,
                item.source.unit.clone(),
            )) {
                bail!("Attribution {} is absent from the source function inventory", item.id);
            }
            item.target.address = hex(target_start);
            item.target.end = hex(target_end);
            item.source.address = hex(source_start);
            item.source.end = hex(source_end);

            // These are derived diagnostics. Never trust their serialized
            // value when an artifact is resumed or injected by a test.
            item.origin = origin(item.method);
            item.binary_supported = item.method != MatchMethod::Name || item.distinctive_body;
            if item
                .competing
                .as_ref()
                .is_some_and(|competing| !competing.relative_score.is_finite())
            {
                bail!("Identification {} has an invalid competing score", item.id);
            }
            item.ambiguous = item
                .competing
                .as_ref()
                .is_some_and(|competing| competing.relative_score > 1.0 - CONTESTED_MARGIN);
            item.tier = classify_tier(
                item.method,
                item.distinctive_body,
                item.evidence_count,
                item.ambiguous,
            );
            item.independent = decisive(item);
            item.current_target_owner = target_owners
                .get(&(item.target.module.clone(), item.target.section.clone(), target_start))
                .cloned()
                .flatten();
        }

        let mut by_unit = BTreeMap::new();
        let supplied_count = report.units.len();
        let mut supplied: BTreeMap<String, UnitIdentification> =
            report.units.drain(..).map(|unit| (unit.unit.clone(), unit)).collect();
        if supplied_count != expected_units.len()
            || supplied.len() != expected_units.len()
            || supplied.keys().collect::<BTreeSet<_>>() != expected_units.iter().collect()
        {
            bail!("Identification inventory does not cover exactly the source split units");
        }
        let mut units = Vec::with_capacity(expected_units.len());
        for name in expected_units {
            let diagnostics = supplied.remove(name).expect("unit set was checked");
            let items: Vec<&FunctionAttribution> =
                report.attributions.iter().filter(|item| item.source.unit == *name).collect();
            let canonical = canonical_unit(
                diagnostics,
                &items,
                &report.attributions,
                &report.source_functions,
                &report.target_functions,
            );
            by_unit.insert(name.clone(), units.len());
            units.push(canonical);
        }
        report.units = units;

        let bytes = serde_json::to_vec(&report)?;
        let digest = format!("{:x}", Sha256::digest(bytes));
        Ok(Self { report, digest, by_id, by_target, by_unit })
    }

    pub fn report(&self) -> &IdentificationReport { &self.report }

    pub fn digest(&self) -> &str { &self.digest }

    pub fn attribution(&self, id: &str) -> Option<&FunctionAttribution> {
        self.by_id.get(id).map(|&index| &self.report.attributions[index])
    }

    pub fn at_target(
        &self,
        module: &str,
        section: &str,
        address: u32,
    ) -> Option<&FunctionAttribution> {
        self.by_target
            .get(&AddressKey { module: module.into(), section: section.into(), address })
            .map(|&index| &self.report.attributions[index])
    }

    pub fn unit(&self, name: &str) -> Option<&UnitIdentification> {
        self.by_unit.get(name).map(|&index| &self.report.units[index])
    }

    pub fn target_function_count(&self, module: &str, section: &str, start: u32, end: u32) -> u32 {
        self.report
            .target_functions
            .iter()
            .filter(|function| {
                function.module == module && function.section == section && {
                    let address = parse_hex(&function.address);
                    start <= address && address < end
                }
            })
            .count() as u32
    }

    pub fn source_function_count(&self, unit: &str, module: &str, section: &str) -> u32 {
        self.report
            .source_functions
            .iter()
            .filter(|function| {
                function.unit == unit && function.module == module && function.section == section
            })
            .count() as u32
    }

    pub fn independent_members(
        &self,
        unit: &str,
        module: &str,
        section: &str,
        start: u32,
        end: u32,
    ) -> u32 {
        self.report
            .attributions
            .iter()
            .filter(|item| {
                item.source.unit == unit
                    && item.target.module == module
                    && item.target.section == section
                    && item.independent
                    && {
                        let address = parse_hex(&item.target.address);
                        start <= address && address < end
                    }
            })
            .count() as u32
    }

    pub fn persist(&self, directory: &Path) -> Result<ObservationReference> {
        std::fs::create_dir_all(directory)?;
        let name = format!("ownership-{}.json", self.digest);
        let path = directory.join(&name);
        if path.exists() {
            let report: IdentificationReport = serde_json::from_slice(&std::fs::read(&path)?)?;
            let existing = ObservationIndex::load_self_contained(
                report,
                &self.report.source,
                &self.report.target,
            )?;
            if existing.digest != self.digest {
                bail!("Existing ownership observation artifact has the wrong digest");
            }
        } else {
            std::fs::write(&path, serde_json::to_vec_pretty(&self.report)?)?;
        }
        Ok(ObservationReference {
            schema: IDENTIFICATION_SCHEMA,
            sha256: self.digest.clone(),
            file: path.to_string_lossy().into_owned(),
        })
    }

    /// Classify every target function and padding interval in a resulting code
    /// body. `before` and `after` are section ranges; questionable ground that
    /// was already retained remains visible but does not veto an otherwise safe
    /// extension. Any questionable *new* function does.
    pub fn assess(
        &self,
        unit: &str,
        module: &str,
        before: &BTreeMap<String, Vec<(u32, u32)>>,
        after: &BTreeMap<String, Vec<(u32, u32)>>,
    ) -> OwnershipAssessment {
        let mut result =
            OwnershipAssessment { observation_sha256: self.digest.clone(), ..Default::default() };
        for (section, ranges) in after {
            let old = before.get(section).map(Vec::as_slice).unwrap_or_default();
            let members: Vec<TargetExtent> = self
                .report
                .target_functions
                .iter()
                .filter(|member| member.module == module && member.section == *section)
                .map(|member| TargetExtent {
                    module: member.module.clone(),
                    section: member.section.clone(),
                    start: parse_hex(&member.address),
                    end: parse_hex(&member.end),
                })
                .collect();
            for &(start, end) in ranges {
                let mut covered = Vec::new();
                for member in
                    members.iter().filter(|member| start < member.end && member.start < end)
                {
                    let left = start.max(member.start);
                    let right = end.min(member.end);
                    if right <= left {
                        continue;
                    }
                    covered.push((left, right));
                    let retained = interval_covered(old, left, right);
                    let attribution = self.at_target(module, section, member.start);
                    let cuts_member = left != member.start || right != member.end;
                    let (class, attribution_id, attributed_unit) = if cuts_member {
                        (
                            ClaimClass::UnresolvedFunction,
                            attribution.map(|item| item.id.clone()),
                            attribution.map(|item| item.source.unit.clone()),
                        )
                    } else {
                        match attribution {
                            Some(item)
                                if item.source_weak
                                    || item.target_weak
                                    || item.template_instantiation =>
                            {
                                (
                                    ClaimClass::SharedHelper,
                                    Some(item.id.clone()),
                                    Some(item.source.unit.clone()),
                                )
                            }
                            Some(item) if item.source.unit == unit && item.independent => (
                                ClaimClass::IndependentlyAttributed,
                                Some(item.id.clone()),
                                Some(item.source.unit.clone()),
                            ),
                            Some(item) if item.source.unit != unit && item.independent => (
                                ClaimClass::ConflictingAttribution,
                                Some(item.id.clone()),
                                Some(item.source.unit.clone()),
                            ),
                            Some(item) => (
                                ClaimClass::UnresolvedFunction,
                                Some(item.id.clone()),
                                Some(item.source.unit.clone()),
                            ),
                            None => (ClaimClass::UnresolvedFunction, None, None),
                        }
                    };
                    match (retained, class) {
                        (_, ClaimClass::IndependentlyAttributed) => {
                            result.independent_members += 1;
                        }
                        (true, _) => result.retained_questionable += 1,
                        (false, ClaimClass::SharedHelper) => result.new_shared_helpers += 1,
                        (false, ClaimClass::ConflictingAttribution) => result.new_conflicts += 1,
                        (false, ClaimClass::UnresolvedFunction) => result.new_unresolved += 1,
                        (false, ClaimClass::Padding) => unreachable!(),
                    }
                    result.records.push(ClaimRecord {
                        module: module.to_string(),
                        section: section.clone(),
                        start: hex(left),
                        end: hex(right),
                        class,
                        attribution_id,
                        attributed_unit,
                        retained,
                    });
                }

                covered.sort_unstable();
                let mut cursor = start;
                for (left, right) in covered {
                    if cursor < left {
                        record_padding(&mut result, module, section, cursor, left, old);
                    }
                    cursor = cursor.max(right);
                }
                if cursor < end {
                    record_padding(&mut result, module, section, cursor, end, old);
                }
            }
        }
        result.complete_membership = result.independent_members > 0
            && result.retained_questionable == 0
            && result.new_shared_helpers == 0
            && result.new_conflicts == 0
            && result.new_unresolved == 0;
        result.supported_edges = self
            .unit(unit)
            .into_iter()
            .flat_map(|identification| &identification.candidates)
            .filter(|candidate| candidate.module == module)
            .filter(|candidate| {
                let start = parse_hex(&candidate.start);
                let end = parse_hex(&candidate.end);
                after.get(&candidate.section).is_some_and(|ranges| ranges.contains(&(start, end)))
            })
            .map(|candidate| {
                u32::from(candidate.left_target_edge.supported)
                    + u32::from(candidate.right_target_edge.supported)
            })
            .max()
            .unwrap_or(0);
        result
    }
}

pub fn load_reference(
    reference: &ObservationReference,
    source: &str,
    target: &str,
) -> Result<ObservationIndex> {
    if reference.schema != IDENTIFICATION_SCHEMA {
        bail!("Ownership reference uses unsupported schema {}", reference.schema);
    }
    let text = std::fs::read_to_string(&reference.file).map_err(|error| {
        anyhow::anyhow!("Failed to read ownership observations {}: {error}", reference.file)
    })?;
    let report: IdentificationReport = serde_json::from_str(&text)?;
    let observations = ObservationIndex::load_self_contained(report, source, target)?;
    if observations.digest() != reference.sha256 {
        bail!("Ownership observation digest does not match the proposal");
    }
    Ok(observations)
}

fn interval_covered(ranges: &[(u32, u32)], start: u32, end: u32) -> bool {
    ranges.iter().any(|&(left, right)| left <= start && end <= right)
}

fn record_padding(
    assessment: &mut OwnershipAssessment,
    module: &str,
    section: &str,
    start: u32,
    end: u32,
    before: &[(u32, u32)],
) {
    let retained = interval_covered(before, start, end);
    if !retained {
        assessment.padding_bytes += end - start;
    }
    assessment.records.push(ClaimRecord {
        module: module.to_string(),
        section: section.to_string(),
        start: hex(start),
        end: hex(end),
        class: ClaimClass::Padding,
        attribution_id: None,
        attributed_unit: None,
        retained,
    });
}

fn parse_address_checked(value: &str, side: &str, id: &str) -> Result<u32> {
    let digits = value.strip_prefix("0x").or_else(|| value.strip_prefix("0X")).unwrap_or(value);
    u32::from_str_radix(digits, 16)
        .map_err(|_| anyhow::anyhow!("Attribution {id} has invalid {side} address {value}"))
}

fn validate_location(location: &FunctionLocation, side: &str, id: &str) -> Result<()> {
    let start = parse_address_checked(&location.address, side, id)?;
    let end = parse_address_checked(&location.end, side, id)?;
    if location.module.is_empty() || location.section.is_empty() || end <= start {
        bail!("Attribution {id} has an invalid {side} extent");
    }
    Ok(())
}

fn validate_source(source: &SourceFunction, id: &str) -> Result<()> {
    validate_location(
        &FunctionLocation {
            module: source.module.clone(),
            section: source.section.clone(),
            address: source.address.clone(),
            end: source.end.clone(),
        },
        "source",
        id,
    )
}

fn decisive(item: &FunctionAttribution) -> bool {
    !item.source_weak
        && !item.target_weak
        && !item.template_instantiation
        && !item.ambiguous
        && (item.unique_exact_body
            || item.method == MatchMethod::StringRef
            || (matches!(item.method, MatchMethod::CallSite | MatchMethod::CallerSite)
                && item.evidence_count >= 2))
}

fn canonical_edge(
    unit: &str,
    module: &str,
    section: &str,
    neighbor: Option<&TargetFunctionObservation>,
    section_boundary_reason: &str,
    all: &[FunctionAttribution],
) -> EdgeEvidence {
    let Some(neighbor) = neighbor else {
        return EdgeEvidence {
            supported: true,
            reason: section_boundary_reason.into(),
            adjacent_attribution_id: None,
        };
    };
    let address = parse_hex(&neighbor.address);
    let Some(attribution) = all.iter().find(|item| {
        item.target.module == module
            && item.target.section == section
            && parse_hex(&item.target.address) == address
    }) else {
        return EdgeEvidence {
            supported: false,
            reason: format!("adjacent target function {} is not attributed", neighbor.address),
            adjacent_attribution_id: None,
        };
    };
    if attribution.source.unit == unit {
        return EdgeEvidence {
            supported: false,
            reason: "the adjacent target function is attributed to the same source unit".into(),
            adjacent_attribution_id: Some(attribution.id.clone()),
        };
    }
    EdgeEvidence {
        supported: attribution.independent,
        reason: if attribution.independent {
            format!(
                "adjacent target function is independently attributed to {}",
                attribution.source.unit
            )
        } else {
            "adjacent attribution is not an independent foreign boundary".into()
        },
        adjacent_attribution_id: Some(attribution.id.clone()),
    }
}

fn canonical_unit(
    mut unit: UnitIdentification,
    items: &[&FunctionAttribution],
    all: &[FunctionAttribution],
    source_functions: &[SourceFunctionObservation],
    target_functions: &[TargetFunctionObservation],
) -> UnitIdentification {
    let matched = items.len() as u32;
    let source_members: Vec<&SourceFunctionObservation> =
        source_functions.iter().filter(|function| function.unit == unit.unit).collect();
    unit.source_functions = source_members.len() as u32;
    unit.matched_functions = matched;
    unit.strong_functions = items
        .iter()
        .filter(|item| item.binary_supported && item.tier != MatchTier::Candidate)
        .count() as u32;
    unit.binary_functions = items.iter().filter(|item| item.binary_supported).count() as u32;
    unit.independently_supported_functions =
        items.iter().filter(|item| item.independent).count() as u32;
    unit.name_only_functions = items
        .iter()
        .filter(|item| item.origin == AttributionOrigin::InputName && !item.binary_supported)
        .count() as u32;
    let named = items.iter().filter(|item| item.origin == AttributionOrigin::InputName).count();
    unit.basis = match (unit.binary_functions, named) {
        (0, 0) => IdentificationBasis::None,
        (0, _) => IdentificationBasis::NamesOnly,
        (_, 0) => IdentificationBasis::Binary,
        _ => IdentificationBasis::Mixed,
    };
    unit.confidence = confidence_for(
        items.len(),
        unit.independently_supported_functions,
        items.iter().any(|item| item.ambiguous),
    );
    unit.evidence = items.iter().map(|item| item.id.clone()).collect();
    unit.unresolved_helpers = items
        .iter()
        .filter(|item| item.source_weak || item.target_weak || item.template_instantiation)
        .map(|item| item.id.clone())
        .collect();
    unit.competing_explanations = items
        .iter()
        .filter_map(|item| {
            let competing = item.competing.as_ref()?;
            Some(CompetingExplanation {
                target_address: item.target.address.clone(),
                source_name: competing.source_name.clone(),
                source_unit: competing.source_unit.clone(),
                relative_score: competing.relative_score,
            })
        })
        .collect();
    let attributed_source: BTreeSet<(&str, &str, &str)> = items
        .iter()
        .map(|item| {
            (
                item.source.module.as_str(),
                item.source.section.as_str(),
                item.source.address.as_str(),
            )
        })
        .collect();
    unit.missing_members = source_members
        .iter()
        .filter(|function| {
            !attributed_source.contains(&(
                function.module.as_str(),
                function.section.as_str(),
                function.address.as_str(),
            ))
        })
        .map(|function| MissingMember {
            source_name: function.name.clone(),
            section: function.section.clone(),
            address: function.address.clone(),
        })
        .collect();

    // Candidate membership and edges are derived diagnostics. Rebuild the
    // groups from the attributions so a serialized candidate cannot omit,
    // duplicate or repartition evidence to manufacture better boundaries.
    let mut groups: BTreeMap<(&str, &str, &str), Vec<&FunctionAttribution>> = BTreeMap::new();
    for item in items {
        groups
            .entry((&item.target.module, &item.source.section, &item.target.section))
            .or_default()
            .push(item);
    }
    let mut candidates = Vec::with_capacity(groups.len());
    for ((module, source_section, section), mut members) in groups {
        members.sort_by_key(|item| parse_hex(&item.target.address));
        let start = parse_hex(&members[0].target.address);
        let end = parse_hex(&members[members.len() - 1].target.end);
        let matched_addresses: BTreeSet<u32> =
            members.iter().map(|item| parse_hex(&item.target.address)).collect();
        let envelope: Vec<&TargetFunctionObservation> = target_functions
            .iter()
            .filter(|function| {
                function.module == module && function.section == section && {
                    let address = parse_hex(&function.address);
                    start <= address && address < end
                }
            })
            .collect();
        let unexplained_target_members: Vec<TargetMember> = envelope
            .iter()
            .filter(|function| !matched_addresses.contains(&parse_hex(&function.address)))
            .map(|function| TargetMember {
                name: function.name.clone(),
                address: function.address.clone(),
                end: function.end.clone(),
            })
            .collect();
        let mut source_section_members: Vec<&SourceFunctionObservation> = source_members
            .iter()
            .copied()
            .filter(|function| function.section == source_section)
            .collect();
        source_section_members.sort_by_key(|function| parse_hex(&function.address));
        let attributed_source: BTreeSet<u32> =
            members.iter().map(|item| parse_hex(&item.source.address)).collect();
        let left_source_edge_observed = source_section_members
            .first()
            .is_some_and(|function| attributed_source.contains(&parse_hex(&function.address)));
        let right_source_edge_observed = source_section_members
            .last()
            .is_some_and(|function| attributed_source.contains(&parse_hex(&function.address)));

        let mut target_section_members: Vec<&TargetFunctionObservation> = target_functions
            .iter()
            .filter(|function| function.module == module && function.section == section)
            .collect();
        target_section_members.sort_by_key(|function| parse_hex(&function.address));
        let left = target_section_members
            .iter()
            .rev()
            .find(|function| parse_hex(&function.address) < start)
            .copied();
        let right = target_section_members
            .iter()
            .find(|function| parse_hex(&function.address) >= end)
            .copied();
        let left_target_edge = canonical_edge(
            &unit.unit,
            module,
            section,
            left,
            "candidate starts at the beginning of the target section",
            all,
        );
        let right_target_edge = canonical_edge(
            &unit.unit,
            module,
            section,
            right,
            "candidate ends at the end of the target section",
            all,
        );
        candidates.push(CandidateSequence {
            module: module.to_string(),
            source_section: source_section.to_string(),
            section: section.to_string(),
            start: hex(start),
            end: hex(end),
            attribution_ids: members.iter().map(|item| item.id.clone()).collect(),
            matched_members: members.len() as u32,
            target_functions_in_envelope: envelope.len() as u32,
            contiguous_target_members: unexplained_target_members.is_empty()
                && envelope.len() == members.len(),
            left_source_edge_observed,
            right_source_edge_observed,
            left_target_edge,
            right_target_edge,
            unexplained_target_members,
            current_owners: envelope
                .iter()
                .filter_map(|item| item.current_owner.clone())
                .collect::<BTreeSet<_>>()
                .into_iter()
                .collect(),
        });
    }
    unit.candidates = candidates;

    unit.boundary_blockers.clear();
    if items.is_empty() {
        unit.boundary_blockers.push("no target function is attributed to this source unit".into());
    }
    if unit.basis == IdentificationBasis::NamesOnly {
        unit.boundary_blockers.push("identity is supported only by pre-existing names".into());
    }
    if items.iter().any(|item| item.ambiguous) {
        unit.boundary_blockers
            .push("one or more function identities have a competing explanation".into());
    }
    if !unit.missing_members.is_empty() {
        unit.boundary_blockers.push("some source members have no target attribution".into());
    }
    for candidate in &unit.candidates {
        if !candidate.contiguous_target_members {
            unit.boundary_blockers.push(format!(
                "{} has unmatched target functions inside the observed envelope",
                candidate.section
            ));
        }
        if !candidate.left_source_edge_observed {
            unit.boundary_blockers
                .push(format!("{} left source edge is not observed", candidate.section));
        }
        if !candidate.right_source_edge_observed {
            unit.boundary_blockers
                .push(format!("{} right source edge is not observed", candidate.section));
        }
        if !candidate.left_target_edge.supported {
            unit.boundary_blockers.push(format!(
                "{} left target edge is unsupported: {}",
                candidate.section, candidate.left_target_edge.reason
            ));
        }
        if !candidate.right_target_edge.supported {
            unit.boundary_blockers.push(format!(
                "{} right target edge is unsupported: {}",
                candidate.section, candidate.right_target_edge.reason
            ));
        }
    }
    unit.boundary_blockers.sort();
    unit.boundary_blockers.dedup();

    unit.application_blockers.clear();
    if !unit.boundary_blockers.is_empty() {
        unit.application_blockers.push("boundary evidence is incomplete".into());
    }
    let foreign: BTreeSet<&str> = items
        .iter()
        .filter_map(|item| item.current_target_owner.as_deref())
        .filter(|owner| *owner != unit.unit)
        .collect();
    if !foreign.is_empty() {
        unit.application_blockers.push(format!(
            "observed target members are currently owned by {}",
            foreign.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    if !unit.unresolved_helpers.is_empty() {
        unit.application_blockers
            .push("weak or template members need emitted-owner evidence".into());
    }
    unit
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionLocation {
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceFunction {
    pub name: String,
    pub unit: String,
    pub module: String,
    pub section: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AttributionOrigin {
    InputName,
    NormalizedBody,
    StringReference,
    CallGraph,
    LinkOrder,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetingAttribution {
    pub source_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_unit: Option<String>,
    pub relative_score: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceReference {
    pub kind: String,
    pub detail: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UnitIdentification {
    pub unit: String,
    pub autogenerated: bool,
    pub confidence: IdentificationConfidence,
    pub basis: IdentificationBasis,
    pub source_functions: u32,
    pub matched_functions: u32,
    pub strong_functions: u32,
    pub binary_functions: u32,
    pub independently_supported_functions: u32,
    pub name_only_functions: u32,
    pub candidates: Vec<CandidateSequence>,
    pub evidence: Vec<String>,
    pub competing_explanations: Vec<CompetingExplanation>,
    pub missing_members: Vec<MissingMember>,
    pub unresolved_helpers: Vec<String>,
    pub boundary_blockers: Vec<String>,
    pub application_blockers: Vec<String>,
}

impl UnitIdentification {
    pub fn absent(unit: impl Into<String>, source_functions: u32) -> Self {
        Self {
            unit: unit.into(),
            autogenerated: false,
            confidence: IdentificationConfidence::Absent,
            basis: IdentificationBasis::None,
            source_functions,
            matched_functions: 0,
            strong_functions: 0,
            binary_functions: 0,
            independently_supported_functions: 0,
            name_only_functions: 0,
            candidates: Vec::new(),
            evidence: Vec::new(),
            competing_explanations: Vec::new(),
            missing_members: Vec::new(),
            unresolved_helpers: Vec::new(),
            boundary_blockers: vec!["no target function is attributed to this source unit".into()],
            application_blockers: vec![
                "no target function is attributed to this source unit".into(),
            ],
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum IdentificationConfidence {
    Absent,
    Tentative,
    Corroborated,
    Ambiguous,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum IdentificationBasis {
    None,
    NamesOnly,
    Binary,
    Mixed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateSequence {
    pub module: String,
    pub source_section: String,
    pub section: String,
    pub start: String,
    pub end: String,
    pub attribution_ids: Vec<String>,
    pub matched_members: u32,
    pub target_functions_in_envelope: u32,
    pub contiguous_target_members: bool,
    pub left_source_edge_observed: bool,
    pub right_source_edge_observed: bool,
    pub left_target_edge: EdgeEvidence,
    pub right_target_edge: EdgeEvidence,
    pub unexplained_target_members: Vec<TargetMember>,
    pub current_owners: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdgeEvidence {
    pub supported: bool,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adjacent_attribution_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TargetMember {
    pub name: String,
    pub address: String,
    pub end: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompetingExplanation {
    pub target_address: String,
    pub source_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_unit: Option<String>,
    pub relative_score: f32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MissingMember {
    pub source_name: String,
    pub section: String,
    pub address: String,
}

#[derive(Debug, Clone)]
struct SourceMember {
    name: String,
    section: String,
    address: u32,
    matched: bool,
}

/// Build the complete observation inventory directly from the function matcher.
pub fn identify_units(
    source: &MatchTarget,
    target: &MatchTarget,
    result: &MatchResult,
) -> IdentificationReport {
    let by_source: BTreeMap<NodeIndex, &Match> =
        result.matches.iter().map(|matched| (matched.source, matched)).collect();
    let mut source_members: BTreeMap<String, Vec<SourceMember>> = BTreeMap::new();
    // Seed from split ownership rather than call-graph membership. This keeps
    // data-only and empty code units in the complete identification inventory.
    for (_, _, _, split) in source.obj.sections.all_splits() {
        source_members.entry(split.unit.clone()).or_default();
    }
    for (node, function) in source.graph.iter() {
        let Some(unit) = source.unit_of(node) else { continue };
        source_members.entry(unit.to_string()).or_default().push(SourceMember {
            name: source.symbol_name(node).to_string(),
            section: source.obj.sections[function.section].name.clone(),
            address: function.address,
            matched: by_source.contains_key(&node),
        });
    }
    for members in source_members.values_mut() {
        members.sort_by_key(|member| (member.section.clone(), member.address));
    }

    let source_hash_counts = exact_hash_counts(source);
    let target_hash_counts = exact_hash_counts(target);
    let mut attributions = Vec::new();
    for matched in &result.matches {
        let Some(unit) = source.unit_of(matched.source) else { continue };
        attributions.push(attribution(
            source,
            target,
            matched,
            unit,
            &source_hash_counts,
            &target_hash_counts,
        ));
    }
    attributions.sort_by(|left, right| {
        left.target
            .module
            .cmp(&right.target.module)
            .then(left.target.section.cmp(&right.target.section))
            .then(left.target.address.cmp(&right.target.address))
            .then(left.source.unit.cmp(&right.source.unit))
    });

    let attributions_by_unit: BTreeMap<&str, Vec<&FunctionAttribution>> = source_members
        .keys()
        .map(|unit| {
            (unit.as_str(), attributions.iter().filter(|item| item.source.unit == *unit).collect())
        })
        .collect();
    let attributions_by_target: BTreeMap<(&str, &str, u32), &FunctionAttribution> = attributions
        .iter()
        .map(|item| {
            (
                (
                    item.target.module.as_str(),
                    item.target.section.as_str(),
                    parse_hex(&item.target.address),
                ),
                item,
            )
        })
        .collect();
    let units = source_members
        .iter()
        .map(|(unit, members)| {
            identify_unit(
                unit,
                members,
                attributions_by_unit.get(unit.as_str()).map(Vec::as_slice).unwrap_or_default(),
                target,
                &attributions_by_target,
                source.obj.is_unit_autogenerated(unit),
            )
        })
        .collect();

    IdentificationReport {
        schema: IDENTIFICATION_SCHEMA,
        source: source.name.clone(),
        target: target.name.clone(),
        attributions,
        source_functions: source
            .graph
            .iter()
            .filter_map(|(node, function)| {
                Some(SourceFunctionObservation {
                    name: source.symbol_name(node).to_string(),
                    unit: source.unit_of(node)?.to_string(),
                    module: EXECUTABLE_MODULE.into(),
                    section: source.obj.sections[function.section].name.clone(),
                    address: hex(function.address),
                    end: hex(function.address + function.size),
                })
            })
            .collect(),
        target_functions: target
            .graph
            .iter()
            .map(|(node, function)| TargetFunctionObservation {
                name: target.symbol_name(node).to_string(),
                module: EXECUTABLE_MODULE.into(),
                section: target.obj.sections[function.section].name.clone(),
                address: hex(function.address),
                end: hex(function.address + function.size),
                current_owner: target.unit_of(node).map(str::to_string),
                owner_autogenerated: target
                    .unit_of(node)
                    .is_some_and(|unit| target.obj.is_unit_autogenerated(unit)),
            })
            .collect(),
        units,
    }
}

fn attribution(
    source: &MatchTarget,
    target: &MatchTarget,
    matched: &Match,
    unit: &str,
    source_hash_counts: &HashMap<u64, u32>,
    target_hash_counts: &HashMap<u64, u32>,
) -> FunctionAttribution {
    let source_node = source.graph.node(matched.source);
    let target_node = target.graph.node(matched.target);
    let source_name = source.symbol_name(matched.source);
    let target_section = target.obj.sections[target_node.section].name.clone();
    let source_section = source.obj.sections[source_node.section].name.clone();
    let competing = matched.runner_up.map(|alternative| CompetingAttribution {
        source_name: source.symbol_name(alternative.source).to_string(),
        source_unit: source.unit_of(alternative.source).map(str::to_string),
        relative_score: round(alternative.relative_score),
    });
    let template = is_template(source, matched.source) || is_template(target, matched.target);
    let source_weak = source.is_weak(matched.source);
    let target_weak = target.is_weak(matched.target);
    let unique_exact =
        unique_exact_body(source, target, matched, source_hash_counts, target_hash_counts);
    let binary_supported = matched.method != MatchMethod::Name || matched.distinctive_body;
    let independent = !source_weak
        && !target_weak
        && !template
        && !matched.is_contested()
        && (unique_exact
            || matched.method == MatchMethod::StringRef
            || (matches!(matched.method, MatchMethod::CallSite | MatchMethod::CallerSite)
                && matched.evidence >= 2));
    let mut evidence = vec![EvidenceReference {
        kind: matched.method.as_str().to_string(),
        detail: method_detail(matched.method).to_string(),
    }];
    if unique_exact && matched.method != MatchMethod::ExactHash {
        evidence.push(EvidenceReference {
            kind: "unique-exact-body".into(),
            detail: "relocation-masked bodies are equal and unique in both binaries".into(),
        });
    } else if matched.distinctive_body && matched.method != MatchMethod::ExactHash {
        evidence.push(EvidenceReference {
            kind: "normalized-body".into(),
            detail: "relocation-masked bodies are equal but do not uniquely identify the pair"
                .into(),
        });
    }
    if matched.evidence > 1 {
        evidence.push(EvidenceReference {
            kind: "corroboration".into(),
            detail: format!("{} independently agreeing neighbours", matched.evidence),
        });
    }
    FunctionAttribution {
        id: format!(
            "{}:{}:{}<-{}:{}:{}",
            EXECUTABLE_MODULE,
            target_section,
            hex(target_node.address),
            EXECUTABLE_MODULE,
            source_section,
            hex(source_node.address)
        ),
        target: FunctionLocation {
            module: EXECUTABLE_MODULE.into(),
            section: target_section,
            address: hex(target_node.address),
            end: hex(target_node.address + target_node.size),
        },
        source: SourceFunction {
            name: source_name.to_string(),
            unit: unit.to_string(),
            module: EXECUTABLE_MODULE.into(),
            section: source_section,
            address: hex(source_node.address),
            end: hex(source_node.address + source_node.size),
        },
        method: matched.method,
        tier: matched.tier(),
        confidence: round(matched.confidence),
        evidence_count: matched.evidence,
        origin: origin(matched.method),
        distinctive_body: matched.distinctive_body,
        unique_exact_body: unique_exact,
        binary_supported,
        independent,
        ambiguous: matched.is_contested(),
        competing,
        source_weak,
        target_weak,
        template_instantiation: template,
        current_target_owner: target.unit_of(matched.target).map(str::to_string),
        evidence,
    }
}

fn identify_unit(
    unit: &str,
    members: &[SourceMember],
    attributions: &[&FunctionAttribution],
    target: &MatchTarget,
    attributions_by_target: &BTreeMap<(&str, &str, u32), &FunctionAttribution>,
    autogenerated: bool,
) -> UnitIdentification {
    let strong_functions = attributions
        .iter()
        .filter(|item| item.binary_supported && item.tier != MatchTier::Candidate)
        .count() as u32;
    let binary_functions = attributions.iter().filter(|item| item.binary_supported).count() as u32;
    let independently_supported_functions =
        attributions.iter().filter(|item| item.independent).count() as u32;
    let named_functions =
        attributions.iter().filter(|item| item.origin == AttributionOrigin::InputName).count()
            as u32;
    let name_only_functions = attributions
        .iter()
        .filter(|item| item.origin == AttributionOrigin::InputName && !item.binary_supported)
        .count() as u32;
    let competing_explanations: Vec<CompetingExplanation> = attributions
        .iter()
        .filter_map(|item| {
            let competing = item.competing.as_ref()?;
            Some(CompetingExplanation {
                target_address: item.target.address.clone(),
                source_name: competing.source_name.clone(),
                source_unit: competing.source_unit.clone(),
                relative_score: competing.relative_score,
            })
        })
        .collect();
    let basis = match (binary_functions, named_functions) {
        (0, 0) => IdentificationBasis::None,
        (0, _) => IdentificationBasis::NamesOnly,
        (_, 0) => IdentificationBasis::Binary,
        _ => IdentificationBasis::Mixed,
    };
    let confidence = confidence_for(
        attributions.len(),
        independently_supported_functions,
        attributions.iter().any(|item| item.ambiguous),
    );

    let missing_members: Vec<MissingMember> = members
        .iter()
        .filter(|member| !member.matched)
        .map(|member| MissingMember {
            source_name: member.name.clone(),
            section: member.section.clone(),
            address: hex(member.address),
        })
        .collect();
    let unresolved_helpers: Vec<String> = attributions
        .iter()
        .filter(|item| item.source_weak || item.target_weak || item.template_instantiation)
        .map(|item| item.id.clone())
        .collect();

    let mut grouped: BTreeMap<(&str, &str, &str), Vec<&FunctionAttribution>> = BTreeMap::new();
    for item in attributions {
        grouped
            .entry((&item.target.module, &item.source.section, &item.target.section))
            .or_default()
            .push(item);
    }
    let candidates: Vec<CandidateSequence> = grouped
        .into_values()
        .map(|items| candidate_sequence(unit, items, members, target, attributions_by_target))
        .collect();

    let mut boundary_blockers = Vec::new();
    if attributions.is_empty() {
        boundary_blockers.push("no target function is attributed to this source unit".into());
    }
    if basis == IdentificationBasis::NamesOnly {
        boundary_blockers.push("identity is supported only by pre-existing names".into());
    }
    if attributions.iter().any(|item| item.ambiguous) {
        boundary_blockers
            .push("one or more function identities have a competing explanation".into());
    }
    if !missing_members.is_empty() {
        boundary_blockers.push("some source members have no target attribution".into());
    }
    for candidate in &candidates {
        if !candidate.contiguous_target_members {
            boundary_blockers.push(format!(
                "{} has unmatched target functions inside the observed envelope",
                candidate.section
            ));
        }
        if !candidate.left_source_edge_observed {
            boundary_blockers
                .push(format!("{} left source edge is not observed", candidate.section));
        }
        if !candidate.right_source_edge_observed {
            boundary_blockers
                .push(format!("{} right source edge is not observed", candidate.section));
        }
        if !candidate.left_target_edge.supported {
            boundary_blockers.push(format!(
                "{} left target edge is unsupported: {}",
                candidate.section, candidate.left_target_edge.reason
            ));
        }
        if !candidate.right_target_edge.supported {
            boundary_blockers.push(format!(
                "{} right target edge is unsupported: {}",
                candidate.section, candidate.right_target_edge.reason
            ));
        }
    }
    boundary_blockers.sort();
    boundary_blockers.dedup();

    let mut application_blockers = Vec::new();
    if !boundary_blockers.is_empty() {
        application_blockers.push("boundary evidence is incomplete".into());
    }
    let foreign: BTreeSet<&str> = attributions
        .iter()
        .filter_map(|item| item.current_target_owner.as_deref())
        .filter(|owner| *owner != unit)
        .collect();
    if !foreign.is_empty() {
        application_blockers.push(format!(
            "observed target members are currently owned by {}",
            foreign.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    if !unresolved_helpers.is_empty() {
        application_blockers.push("weak or template members need emitted-owner evidence".into());
    }

    UnitIdentification {
        unit: unit.to_string(),
        autogenerated,
        confidence,
        basis,
        source_functions: members.len() as u32,
        matched_functions: attributions.len() as u32,
        strong_functions,
        binary_functions,
        independently_supported_functions,
        name_only_functions,
        candidates,
        evidence: attributions.iter().map(|item| item.id.clone()).collect(),
        competing_explanations,
        missing_members,
        unresolved_helpers,
        boundary_blockers,
        application_blockers,
    }
}

fn candidate_sequence(
    unit: &str,
    mut items: Vec<&FunctionAttribution>,
    source_members: &[SourceMember],
    target: &MatchTarget,
    attributions_by_target: &BTreeMap<(&str, &str, u32), &FunctionAttribution>,
) -> CandidateSequence {
    items.sort_by_key(|item| parse_hex(&item.target.address));
    let first = items[0];
    let last = items[items.len() - 1];
    let start = parse_hex(&first.target.address);
    let end = parse_hex(&last.target.end);
    let section = first.target.section.as_str();
    let target_members: Vec<(NodeIndex, _)> = target
        .graph
        .iter()
        .filter(|(_, node)| {
            target.obj.sections[node.section].name == section
                && node.address >= start
                && node.address < end
        })
        .collect();
    let mut section_members: Vec<(NodeIndex, _)> = target
        .graph
        .iter()
        .filter(|(_, node)| target.obj.sections[node.section].name == section)
        .collect();
    section_members.sort_by_key(|(_, node)| node.address);
    let attributed_target: BTreeSet<u32> =
        items.iter().map(|item| parse_hex(&item.target.address)).collect();
    let unexplained_target_members = target_members
        .iter()
        .filter(|(_, node)| !attributed_target.contains(&node.address))
        .map(|(node, function)| TargetMember {
            name: target.symbol_name(*node).to_string(),
            address: hex(function.address),
            end: hex(function.address + function.size),
        })
        .collect::<Vec<_>>();

    let source_section = first.source.section.as_str();
    let edge_members: Vec<&SourceMember> =
        source_members.iter().filter(|member| member.section == source_section).collect();
    let attributed_source: BTreeSet<u32> =
        items.iter().map(|item| parse_hex(&item.source.address)).collect();
    let left_source_edge_observed =
        edge_members.first().is_some_and(|member| attributed_source.contains(&member.address));
    let right_source_edge_observed =
        edge_members.last().is_some_and(|member| attributed_source.contains(&member.address));
    let current_owners: BTreeSet<String> = target_members
        .iter()
        .filter_map(|(node, _)| target.unit_of(*node).map(str::to_string))
        .collect();
    let left_neighbor = section_members.iter().rev().find(|(_, node)| node.address < start);
    let right_neighbor = section_members.iter().find(|(_, node)| node.address >= end);
    let left_target_edge = edge_evidence(
        unit,
        first.target.module.as_str(),
        section,
        left_neighbor,
        "candidate starts at the beginning of the target section",
        attributions_by_target,
    );
    let right_target_edge = edge_evidence(
        unit,
        first.target.module.as_str(),
        section,
        right_neighbor,
        "candidate ends at the end of the target section",
        attributions_by_target,
    );

    CandidateSequence {
        module: first.target.module.clone(),
        source_section: first.source.section.clone(),
        section: first.target.section.clone(),
        start: first.target.address.clone(),
        end: last.target.end.clone(),
        attribution_ids: items.iter().map(|item| item.id.clone()).collect(),
        matched_members: items.len() as u32,
        target_functions_in_envelope: target_members.len() as u32,
        contiguous_target_members: unexplained_target_members.is_empty(),
        left_source_edge_observed,
        right_source_edge_observed,
        left_target_edge,
        right_target_edge,
        unexplained_target_members,
        current_owners: current_owners.into_iter().collect(),
    }
}

fn edge_evidence(
    unit: &str,
    module: &str,
    section: &str,
    neighbor: Option<&(NodeIndex, &crate::analysis::callgraph::FunctionNode)>,
    section_boundary_reason: &str,
    attributions_by_target: &BTreeMap<(&str, &str, u32), &FunctionAttribution>,
) -> EdgeEvidence {
    let Some((_, node)) = neighbor else {
        return EdgeEvidence {
            supported: true,
            reason: section_boundary_reason.into(),
            adjacent_attribution_id: None,
        };
    };
    let Some(attribution) = attributions_by_target.get(&(module, section, node.address)) else {
        return EdgeEvidence {
            supported: false,
            reason: format!("adjacent target function {} is not attributed", hex(node.address)),
            adjacent_attribution_id: None,
        };
    };
    if attribution.source.unit == unit {
        return EdgeEvidence {
            supported: false,
            reason: "the adjacent target function is attributed to the same source unit".into(),
            adjacent_attribution_id: Some(attribution.id.clone()),
        };
    }
    if !attribution.independent || attribution.ambiguous {
        return EdgeEvidence {
            supported: false,
            reason: format!(
                "the adjacent {} attribution is not independent and decisive",
                attribution.source.unit
            ),
            adjacent_attribution_id: Some(attribution.id.clone()),
        };
    }
    EdgeEvidence {
        supported: true,
        reason: format!(
            "adjacent target function is independently attributed to {}",
            attribution.source.unit
        ),
        adjacent_attribution_id: Some(attribution.id.clone()),
    }
}

fn confidence_for(
    matches: usize,
    independently_supported_functions: u32,
    contested: bool,
) -> IdentificationConfidence {
    if matches == 0 {
        IdentificationConfidence::Absent
    } else if contested {
        IdentificationConfidence::Ambiguous
    } else if independently_supported_functions >= 2 {
        IdentificationConfidence::Corroborated
    } else {
        IdentificationConfidence::Tentative
    }
}

fn exact_hash_counts(target: &MatchTarget) -> HashMap<u64, u32> {
    let mut counts = HashMap::new();
    for fingerprint in &target.fingerprints {
        if fingerprint.instruction_count >= 4 {
            *counts.entry(fingerprint.exact_hash).or_default() += 1;
        }
    }
    counts
}

fn unique_exact_body(
    source: &MatchTarget,
    target: &MatchTarget,
    matched: &Match,
    source_hash_counts: &HashMap<u64, u32>,
    target_hash_counts: &HashMap<u64, u32>,
) -> bool {
    let source_fingerprint = &source.fingerprints[matched.source as usize];
    let target_fingerprint = &target.fingerprints[matched.target as usize];
    if source_fingerprint.instruction_count < 4
        || source_fingerprint.exact_hash != target_fingerprint.exact_hash
        || source_hash_counts.get(&source_fingerprint.exact_hash) != Some(&1)
        || target_hash_counts.get(&target_fingerprint.exact_hash) != Some(&1)
    {
        return false;
    }
    let source_node = source.graph.node(matched.source);
    let target_node = target.graph.node(matched.target);
    source.obj.symbols[source_node.symbol].size_known
        && target.obj.symbols[target_node.symbol].size_known
        && source_node.size == target_node.size
        && normalized_body(&source.obj, source_node) == normalized_body(&target.obj, target_node)
}

fn origin(method: MatchMethod) -> AttributionOrigin {
    match method {
        MatchMethod::Name => AttributionOrigin::InputName,
        MatchMethod::ExactHash => AttributionOrigin::NormalizedBody,
        MatchMethod::StringRef => AttributionOrigin::StringReference,
        MatchMethod::CallSite | MatchMethod::CallerSite => AttributionOrigin::CallGraph,
        MatchMethod::Layout => AttributionOrigin::LinkOrder,
    }
}

fn method_detail(method: MatchMethod) -> &'static str {
    match method {
        MatchMethod::Name => "the two input binaries already carry the same name",
        MatchMethod::ExactHash => "relocation-masked instruction bodies are uniquely equal",
        MatchMethod::StringRef => "a uniquely referenced string identifies both functions",
        MatchMethod::CallSite => "position among calls from an already matched function agrees",
        MatchMethod::CallerSite => "matched caller/callee topology leaves one pairing",
        MatchMethod::Layout => "position between already matched link-order anchors agrees",
    }
}

fn is_template(target: &MatchTarget, node: NodeIndex) -> bool {
    let symbol = &target.obj.symbols[target.graph.node(node).symbol];
    let name = symbol.demangled_name.as_deref().unwrap_or(&symbol.name);
    let callable = callable_name(name);
    callable.contains('<') && callable.contains('>')
}

/// Return the qualified callable, excluding a demangler's optional return type.
/// A simple split on `(` is not enough: `rstl::rc_ptr<T> C::Get()` is an
/// ordinary method whose return type happens to be a template. The separator
/// we want is the last space outside angle brackets before the argument list.
fn callable_name(name: &str) -> &str {
    let declaration = name.split_once('(').map_or(name, |(declaration, _)| declaration);
    let mut depth = 0_u32;
    let mut separator = None;
    for (offset, character) in declaration.char_indices() {
        match character {
            '<' => depth += 1,
            '>' => depth = depth.saturating_sub(1),
            ' ' if depth == 0 => separator = Some(offset + character.len_utf8()),
            _ => {}
        }
    }
    separator.map_or(declaration, |offset| &declaration[offset..])
}

fn round(value: f32) -> f32 { (value * 1000.0).round() / 1000.0 }

fn hex(value: u32) -> String { format!("{value:#010X}") }

fn parse_hex(value: &str) -> u32 {
    u32::from_str_radix(value.trim_start_matches("0x").trim_start_matches("0X"), 16).unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use decomp_toolkit::obj::{
        ObjArchitecture, ObjInfo, ObjKind, ObjRelocations, ObjSection, ObjSectionKind, ObjSplit,
        ObjSplits, ObjSymbol, ObjSymbolFlagSet, ObjSymbolFlags, ObjSymbolKind,
    };

    use super::*;

    fn fixture_index(units: Vec<crate::analysis::coverage::CoverageUnit>) -> ObservationIndex {
        let report = crate::analysis::coverage_fixture::report("source", "target", units);
        let expected = report.source_units.iter().map(|unit| unit.name.clone()).collect();
        ObservationIndex::load(report.identifications, "source", "target", &expected).unwrap()
    }

    #[test]
    fn forged_aggregate_and_independent_flags_are_recomputed() {
        let unit = crate::analysis::coverage_fixture::unit("A.cpp", vec![
            crate::analysis::coverage_fixture::anchor("A", 0x8000_1000, 0x8000_1100),
        ]);
        let mut report = crate::analysis::coverage_fixture::report("source", "target", vec![unit]);
        let attribution = &mut report.identifications.attributions[0];
        attribution.method = MatchMethod::Name;
        attribution.distinctive_body = false;
        attribution.unique_exact_body = false;
        attribution.independent = true;
        attribution.tier = MatchTier::Confident;
        attribution.ambiguous = false;
        attribution.competing = Some(CompetingAttribution {
            source_name: "runner_up".into(),
            source_unit: Some("A.cpp".into()),
            relative_score: 0.9,
        });
        let diagnostic = &mut report.identifications.units[0];
        diagnostic.matched_functions = 99;
        diagnostic.independently_supported_functions = 99;
        diagnostic.confidence = IdentificationConfidence::Corroborated;
        diagnostic.candidates.clear();

        let expected = BTreeSet::from(["A.cpp".to_string()]);
        let index =
            ObservationIndex::load(report.identifications, "source", "target", &expected).unwrap();
        assert!(!index.report().attributions[0].independent);
        assert!(index.report().attributions[0].ambiguous);
        assert_eq!(index.report().attributions[0].tier, MatchTier::Candidate);
        assert_eq!(index.unit("A.cpp").unwrap().matched_functions, 1);
        assert_eq!(index.unit("A.cpp").unwrap().independently_supported_functions, 0);
        assert_eq!(index.unit("A.cpp").unwrap().candidates.len(), 1);
        assert_eq!(index.unit("A.cpp").unwrap().confidence, IdentificationConfidence::Ambiguous);
        assert_eq!(index.unit("A.cpp").unwrap().basis, IdentificationBasis::NamesOnly);
    }

    #[test]
    fn a_platform_shaped_claim_cannot_take_sounds_tail() {
        let a = crate::analysis::coverage_fixture::unit("Platform.cpp", vec![
            crate::analysis::coverage_fixture::anchor("Platform", 0x8000_1000, 0x8000_1100),
        ]);
        let b = crate::analysis::coverage_fixture::unit("Sound.cpp", vec![
            crate::analysis::coverage_fixture::anchor("Sound", 0x8000_1180, 0x8000_1280),
        ]);
        let index = fixture_index(vec![a, b]);
        let after = BTreeMap::from([(".text".into(), vec![(0x8000_1000, 0x8000_1280)])]);
        let assessment = index.assess("Platform.cpp", "main", &BTreeMap::new(), &after);
        assert_eq!(assessment.new_conflicts, 1);
        assert!(!assessment.permits_automatic_claim());
        assert!(assessment.records.iter().any(|record| {
            record.class == ClaimClass::ConflictingAttribution
                && record.attributed_unit.as_deref() == Some("Sound.cpp")
        }));
    }

    #[test]
    fn a_player_state_claim_cannot_take_a_timer_cluster() {
        let player = crate::analysis::coverage_fixture::unit("CPlayerState.cpp", vec![
            crate::analysis::coverage_fixture::anchor("Player", 0x8000_2000, 0x8000_2100),
        ]);
        let timer = crate::analysis::coverage_fixture::unit("CTime.cpp", vec![
            crate::analysis::coverage_fixture::anchor("TimerCtor", 0x8000_2200, 0x8000_2300),
        ]);
        let index = fixture_index(vec![player, timer]);
        let after = BTreeMap::from([(".text".into(), vec![(0x8000_2000, 0x8000_2300)])]);
        let assessment = index.assess("CPlayerState.cpp", "main", &BTreeMap::new(), &after);
        assert_eq!(assessment.new_conflicts, 1);
        assert!(!assessment.permits_automatic_claim());
    }

    #[test]
    fn a_weak_foreign_function_is_unresolved_shared_evidence_not_a_hard_conflict() {
        let a = crate::analysis::coverage_fixture::unit("A.cpp", vec![
            crate::analysis::coverage_fixture::anchor("A", 0x8000_3000, 0x8000_3100),
        ]);
        let mut helper =
            crate::analysis::coverage_fixture::anchor("helper", 0x8000_3100, 0x8000_3200);
        helper.target_weak = true;
        let b = crate::analysis::coverage_fixture::unit("B.cpp", vec![helper]);
        let index = fixture_index(vec![a, b]);
        let after = BTreeMap::from([(".text".into(), vec![(0x8000_3000, 0x8000_3200)])]);
        let assessment = index.assess("A.cpp", "main", &BTreeMap::new(), &after);
        assert_eq!(assessment.new_conflicts, 0);
        assert_eq!(assessment.new_shared_helpers, 1);
        assert!(assessment.records.iter().any(|record| record.class == ClaimClass::SharedHelper));
    }

    #[test]
    fn cutting_through_an_attributed_function_is_unresolved() {
        let unit = crate::analysis::coverage_fixture::unit("A.cpp", vec![
            crate::analysis::coverage_fixture::anchor("A", 0x8000_4000, 0x8000_4100),
        ]);
        let index = fixture_index(vec![unit]);
        let after = BTreeMap::from([(".text".into(), vec![(0x8000_4004, 0x8000_4100)])]);
        let assessment = index.assess("A.cpp", "main", &BTreeMap::new(), &after);
        assert_eq!(assessment.new_unresolved, 1);
        assert_eq!(assessment.independent_members, 0);
        assert!(!assessment.permits_automatic_claim());
    }

    #[test]
    fn padding_without_an_attributed_member_is_not_automatic_ownership() {
        let unit = crate::analysis::coverage_fixture::unit("A.cpp", Vec::new());
        let index = fixture_index(vec![unit]);
        let after = BTreeMap::from([(".text".into(), vec![(0x8000_4000, 0x8000_4100)])]);
        let assessment = index.assess("A.cpp", "main", &BTreeMap::new(), &after);
        assert_eq!(assessment.padding_bytes, 0x100);
        assert_eq!(assessment.independent_members, 0);
        assert!(!assessment.complete_membership);
        assert!(!assessment.permits_automatic_claim());
    }

    #[test]
    fn persistence_rejects_a_corrupt_existing_content_address() {
        let first = fixture_index(vec![crate::analysis::coverage_fixture::unit("A.cpp", vec![
            crate::analysis::coverage_fixture::anchor("A", 0x8000_4000, 0x8000_4100),
        ])]);
        let second = fixture_index(vec![crate::analysis::coverage_fixture::unit("A.cpp", vec![
            crate::analysis::coverage_fixture::anchor("A", 0x8000_5000, 0x8000_5100),
        ])]);
        let directory = tempfile::tempdir().unwrap();
        let reference = first.persist(directory.path()).unwrap();
        std::fs::write(&reference.file, serde_json::to_vec_pretty(second.report()).unwrap())
            .unwrap();

        let error = first.persist(directory.path()).unwrap_err();
        assert!(error.to_string().contains("wrong digest"), "{error}");
    }

    fn section(
        name: &str,
        kind: ObjSectionKind,
        index: u32,
        base: u32,
        size: u32,
        unit: &str,
    ) -> ObjSection {
        let mut splits = ObjSplits::default();
        splits.push(base, ObjSplit {
            unit: unit.into(),
            end: base + size,
            align: None,
            common: false,
            autogenerated: false,
            skip: false,
            rename: None,
        });
        ObjSection {
            name: name.into(),
            kind,
            address: u64::from(base),
            size: u64::from(size),
            data: vec![0; size as usize],
            align: 4,
            elf_index: index,
            relocations: ObjRelocations::default(),
            virtual_address: None,
            file_offset: 0,
            section_known: true,
            splits,
        }
    }

    fn function(name: &str, section: u32, address: u32, size: u32) -> ObjSymbol {
        ObjSymbol {
            name: name.into(),
            address: u64::from(address),
            section: Some(section),
            size: u64::from(size),
            size_known: true,
            kind: ObjSymbolKind::Function,
            ..Default::default()
        }
    }

    fn target(name: &str, symbols: Vec<ObjSymbol>, sections: Vec<ObjSection>) -> MatchTarget {
        MatchTarget::new(
            name.into(),
            ObjInfo::new(
                ObjKind::Executable,
                ObjArchitecture::PowerPc,
                name.into(),
                symbols,
                sections,
            ),
        )
    }

    fn matched(
        source: NodeIndex,
        target: NodeIndex,
        method: MatchMethod,
        runner_up: Option<(NodeIndex, f32)>,
    ) -> Match {
        Match {
            source,
            target,
            method,
            confidence: 1.0,
            evidence: 1,
            round: 0,
            distinctive_body: method == MatchMethod::ExactHash,
            runner_up: runner_up.map(|(source, relative_score)| {
                crate::analysis::matching::Alternative { source, relative_score }
            }),
        }
    }

    fn result(matches: Vec<Match>, source_len: usize, target_len: usize) -> MatchResult {
        let mut source_to_target = vec![None; source_len];
        let mut target_to_source = vec![None; target_len];
        for item in &matches {
            source_to_target[item.source as usize] = Some(item.target);
            target_to_source[item.target as usize] = Some(item.source);
        }
        MatchResult { matches, source_to_target, target_to_source, rounds: 1 }
    }

    #[test]
    fn names_alone_are_not_independent_corroboration() {
        assert_eq!(confidence_for(6, 0, false), IdentificationConfidence::Tentative);
    }

    #[test]
    fn a_template_return_type_does_not_make_an_ordinary_method_a_template() {
        assert_eq!(
            callable_name("rstl::rc_ptr<IMetaTrans> CTransitionDatabaseGame::GetMetaTrans() const"),
            "CTransitionDatabaseGame::GetMetaTrans"
        );
        assert!(
            !callable_name(
                "rstl::rc_ptr<IMetaTrans> CTransitionDatabaseGame::GetMetaTrans() const"
            )
            .contains('<')
        );
        assert!(callable_name("void rstl::sort<int>(int*, int*)").contains('<'));
        assert!(callable_name("rstl::vector<int>::size() const").contains('<'));
    }

    #[test]
    fn two_binary_members_can_corroborate_a_unit() {
        assert_eq!(confidence_for(2, 2, false), IdentificationConfidence::Corroborated);
    }

    #[test]
    fn a_competing_explanation_remains_ambiguous() {
        assert_eq!(confidence_for(8, 8, true), IdentificationConfidence::Ambiguous);
    }

    #[test]
    fn a_weak_runner_up_is_retained_without_making_the_unit_ambiguous() {
        let source = target(
            "source",
            vec![function("A", 0, 0x1000, 4), function("Other", 0, 0x1004, 4)],
            vec![section(".text", ObjSectionKind::Code, 0, 0x1000, 8, "A.cpp")],
        );
        let target = target("target", vec![function("fn_2000", 0, 0x2000, 4)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x2000,
            4,
            "unknown.cpp",
        )]);
        let report = identify_units(
            &source,
            &target,
            &result(vec![matched(0, 0, MatchMethod::CallSite, Some((1, 0.2)))], 2, 1),
        );
        let unit = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        assert_ne!(unit.confidence, IdentificationConfidence::Ambiguous);
        assert_eq!(unit.competing_explanations.len(), 1, "the diagnostic runner-up is retained");
        assert!(!report.attributions[0].ambiguous);
    }

    #[test]
    fn source_sections_form_separate_candidate_sequences() {
        let source = target(
            "source",
            vec![function("Init", 0, 0x1000, 4), function("Text", 1, 0x2000, 4)],
            vec![
                section(".init", ObjSectionKind::Code, 0, 0x1000, 4, "A.cpp"),
                section(".text", ObjSectionKind::Code, 1, 0x2000, 4, "A.cpp"),
            ],
        );
        let target = target(
            "target",
            vec![function("fn_3000", 0, 0x3000, 4), function("fn_3004", 0, 0x3004, 4)],
            vec![section(".text", ObjSectionKind::Code, 0, 0x3000, 8, "unknown.cpp")],
        );
        let report = identify_units(
            &source,
            &target,
            &result(
                vec![
                    matched(0, 0, MatchMethod::ExactHash, None),
                    matched(1, 1, MatchMethod::ExactHash, None),
                ],
                2,
                2,
            ),
        );
        let unit = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        assert_eq!(unit.candidates.len(), 2);
        assert_eq!(
            unit.candidates
                .iter()
                .map(|item| item.source_section.as_str())
                .collect::<BTreeSet<_>>(),
            BTreeSet::from([".init", ".text"]),
        );
        assert!(
            unit.candidates
                .iter()
                .all(|item| { item.left_source_edge_observed && item.right_source_edge_observed })
        );
    }

    #[test]
    fn a_candidate_cannot_borrow_source_edges_from_another_target_section() {
        let source = target(
            "source",
            vec![function("First", 0, 0x1000, 4), function("Last", 0, 0x1004, 4)],
            vec![section(".text", ObjSectionKind::Code, 0, 0x1000, 8, "A.cpp")],
        );
        let target = target(
            "target",
            vec![function("fn_2000", 0, 0x2000, 4), function("fn_3000", 1, 0x3000, 4)],
            vec![
                section(".init", ObjSectionKind::Code, 0, 0x2000, 4, "unknown.cpp"),
                section(".text", ObjSectionKind::Code, 1, 0x3000, 4, "unknown.cpp"),
            ],
        );
        let report = identify_units(
            &source,
            &target,
            &result(
                vec![
                    matched(0, 0, MatchMethod::ExactHash, None),
                    matched(1, 1, MatchMethod::ExactHash, None),
                ],
                2,
                2,
            ),
        );
        let unit = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        let init = unit.candidates.iter().find(|candidate| candidate.section == ".init").unwrap();
        assert!(init.left_source_edge_observed);
        assert!(!init.right_source_edge_observed);
        let text = unit.candidates.iter().find(|candidate| candidate.section == ".text").unwrap();
        assert!(!text.left_source_edge_observed);
        assert!(text.right_source_edge_observed);
    }

    #[test]
    fn data_only_units_remain_in_the_complete_inventory() {
        let source = target("source", vec![function("A", 0, 0x1000, 4)], vec![
            section(".text", ObjSectionKind::Code, 0, 0x1000, 4, "A.cpp"),
            section(".data", ObjSectionKind::Data, 1, 0x2000, 4, "Data.cpp"),
        ]);
        let target = target("target", vec![function("A", 0, 0x3000, 4)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x3000,
            4,
            "A.cpp",
        )]);
        let report = identify_units(
            &source,
            &target,
            &result(vec![matched(0, 0, MatchMethod::Name, None)], 1, 1),
        );
        let named = report.units.iter().find(|unit| unit.unit == "A.cpp").unwrap();
        assert_eq!(named.basis, IdentificationBasis::NamesOnly);
        assert_eq!(named.strong_functions, 0, "input names are not strong binary evidence");
        let data = report.units.iter().find(|unit| unit.unit == "Data.cpp").unwrap();
        assert_eq!(data.source_functions, 0);
        assert_eq!(data.confidence, IdentificationConfidence::Absent);
    }

    #[test]
    fn a_name_match_retains_independent_exact_body_evidence() {
        let source = target("source", vec![function("A", 0, 0x1000, 16)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x1000,
            16,
            "A.cpp",
        )]);
        let target = target("target", vec![function("A", 0, 0x2000, 16)], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x2000,
            16,
            "A.cpp",
        )]);
        let mut item = matched(0, 0, MatchMethod::Name, None);
        item.distinctive_body = true;
        let report = identify_units(&source, &target, &result(vec![item], 1, 1));
        let attribution = &report.attributions[0];
        assert_eq!(attribution.origin, AttributionOrigin::InputName);
        assert!(attribution.binary_supported);
        assert!(attribution.independent);
        assert_eq!(attribution.target.module, "main");
        assert_eq!(attribution.source.module, "main");
        assert!(attribution.id.starts_with("main:.text:0x00002000<-main:.text:"));
        assert!(attribution.evidence.iter().any(|item| item.kind == "unique-exact-body"));
        let unit = &report.units[0];
        assert_eq!(unit.basis, IdentificationBasis::Mixed);
        assert_eq!(unit.binary_functions, 1);
        assert_eq!(unit.strong_functions, 1);
        assert_eq!(unit.name_only_functions, 0);
    }

    #[test]
    fn a_weak_exact_body_does_not_corroborate_emitted_tu_ownership() {
        let mut source_symbol = function("Weak", 0, 0x1000, 16);
        source_symbol.flags = ObjSymbolFlagSet(ObjSymbolFlags::Weak.into());
        let mut target_symbol = function("Weak", 0, 0x2000, 16);
        target_symbol.flags = ObjSymbolFlagSet(ObjSymbolFlags::Weak.into());
        let source = target("source", vec![source_symbol], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x1000,
            16,
            "A.cpp",
        )]);
        let target = target("target", vec![target_symbol], vec![section(
            ".text",
            ObjSectionKind::Code,
            0,
            0x2000,
            16,
            "unknown.cpp",
        )]);
        let mut item = matched(0, 0, MatchMethod::Name, None);
        item.distinctive_body = true;
        let report = identify_units(&source, &target, &result(vec![item], 1, 1));
        assert!(report.attributions[0].binary_supported);
        assert!(!report.attributions[0].independent);
        assert_eq!(report.units[0].confidence, IdentificationConfidence::Tentative);
        assert_eq!(report.units[0].unresolved_helpers.len(), 1);
    }
}
