//! Reuse function analysis only when fresh DOL analysis has the same inputs.
//!
//! A changed `splits.txt` cannot be ignored before loading: dtk consults
//! ownership while applying constructor, destructor and init signatures. We
//! load both objects every round and compare the resulting symbol/section
//! inputs exactly. Only graph construction, fingerprints, function matching
//! and data pairing are reused; the fresh objects carry current ownership
//! into identification, object evidence and every proposal generator.

use std::sync::Arc;

use decomp_toolkit::obj::ObjInfo;

use crate::analysis::{
    data_matching::{DataMatch, match_data},
    matching::{MatchOptions, MatchResult, MatchTarget, match_functions, same_matching_inputs},
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CacheUse {
    Rebuilt,
    Reused,
}

#[derive(Default)]
pub(crate) struct MatchingCache {
    entry: Option<Entry>,
}

struct Entry {
    options: MatchOptions,
    source: Arc<MatchTarget>,
    target: Arc<MatchTarget>,
    result: Arc<MatchResult>,
    data_matches: Arc<Vec<DataMatch>>,
}

pub(crate) struct PreparedMatch {
    pub source: Arc<MatchTarget>,
    pub target: Arc<MatchTarget>,
    pub result: Arc<MatchResult>,
    pub data_matches: Arc<Vec<DataMatch>>,
    pub cache_use: CacheUse,
}

impl MatchingCache {
    pub fn prepare(
        &mut self,
        source_name: String,
        target_name: String,
        source_obj: ObjInfo,
        target_obj: ObjInfo,
        options: &MatchOptions,
    ) -> PreparedMatch {
        if let Some(entry) = &self.entry
            && entry.options == *options
            && same_matching_inputs(&entry.source.obj, &source_obj)
            && same_matching_inputs(&entry.target.obj, &target_obj)
        {
            return PreparedMatch {
                source: Arc::new(MatchTarget::with_cached_analysis(
                    source_name,
                    source_obj,
                    &entry.source,
                )),
                target: Arc::new(MatchTarget::with_cached_analysis(
                    target_name,
                    target_obj,
                    &entry.target,
                )),
                result: Arc::clone(&entry.result),
                data_matches: Arc::clone(&entry.data_matches),
                cache_use: CacheUse::Reused,
            };
        }

        let source = Arc::new(MatchTarget::new(source_name, source_obj));
        let target = Arc::new(MatchTarget::new(target_name, target_obj));
        let result = Arc::new(match_functions(&source, &target, options));
        let data_matches = Arc::new(match_data(&source, &target, &result));
        self.entry = Some(Entry {
            options: options.clone(),
            source: Arc::clone(&source),
            target: Arc::clone(&target),
            result: Arc::clone(&result),
            data_matches: Arc::clone(&data_matches),
        });
        PreparedMatch { source, target, result, data_matches, cache_use: CacheUse::Rebuilt }
    }
}

#[cfg(test)]
mod tests {
    use decomp_toolkit::obj::{
        ObjArchitecture, ObjInfo, ObjKind, ObjReloc, ObjRelocKind, ObjRelocations, ObjSection,
        ObjSectionKind, ObjSplit, ObjSplits, ObjSymbol, ObjSymbolKind,
    };

    use super::*;
    use crate::{analysis::ownership::identify_units, matching::report::Report};

    fn object(symbol_name: &str, last_word: u32) -> ObjInfo {
        let data: Vec<u8> = [0x6000_0000, 0x6000_0000, 0x6000_0000, last_word]
            .into_iter()
            .flat_map(u32::to_be_bytes)
            .collect();
        ObjInfo::new(
            ObjKind::Executable,
            ObjArchitecture::PowerPc,
            "fixture".into(),
            vec![ObjSymbol {
                name: symbol_name.into(),
                address: 0x8000_1000,
                section: Some(0),
                size: data.len() as u64,
                size_known: true,
                kind: ObjSymbolKind::Function,
                ..Default::default()
            }],
            vec![ObjSection {
                name: ".text".into(),
                kind: ObjSectionKind::Code,
                address: 0x8000_1000,
                size: data.len() as u64,
                data,
                align: 4,
                elf_index: 0,
                relocations: ObjRelocations::default(),
                virtual_address: None,
                file_offset: 0,
                section_known: true,
                splits: ObjSplits::default(),
            }],
        )
    }

    fn own(obj: &mut ObjInfo, unit: &str) {
        obj.sections.get_mut(0).unwrap().splits.push(0x8000_1000, ObjSplit {
            unit: unit.into(),
            end: 0x8000_1010,
            align: None,
            common: false,
            autogenerated: false,
            skip: false,
            rename: None,
        });
    }

    fn prepare(cache: &mut MatchingCache, source: ObjInfo, target: ObjInfo) -> PreparedMatch {
        cache.prepare(
            "source-config".into(),
            "target-config".into(),
            source,
            target,
            &MatchOptions::default(),
        )
    }

    #[test]
    fn changed_ownership_reuses_functions_but_rebuilds_ownership_outputs() {
        let mut source = object("Method__5ClassFv", 0x4E80_0020);
        own(&mut source, "A.cpp");
        let target = object("Method__5ClassFv", 0x4E80_0020);
        let mut cache = MatchingCache::default();
        assert_eq!(
            prepare(&mut cache, source.clone(), target.clone()).cache_use,
            CacheUse::Rebuilt
        );

        let mut owned_target = target;
        own(&mut owned_target, "B.cpp");
        let warm = prepare(&mut cache, source.clone(), owned_target.clone());
        let cold = prepare(&mut MatchingCache::default(), source, owned_target);
        assert_eq!(warm.cache_use, CacheUse::Reused);
        assert_eq!(warm.target.unit_of(0), Some("B.cpp"));
        assert!(Arc::ptr_eq(&warm.result, &cache.entry.as_ref().unwrap().result));
        assert_eq!(warm.data_matches.as_ref(), cold.data_matches.as_ref());
        assert_eq!(
            serde_json::to_value(Report::build(&warm.source, &warm.target, &warm.result, false))
                .unwrap(),
            serde_json::to_value(Report::build(&cold.source, &cold.target, &cold.result, false))
                .unwrap(),
        );
        assert_eq!(
            serde_json::to_value(identify_units(&warm.source, &warm.target, &warm.result)).unwrap(),
            serde_json::to_value(identify_units(&cold.source, &cold.target, &cold.result)).unwrap(),
        );
    }

    #[test]
    fn changed_symbols_or_code_invalidate_the_cache() {
        let source = object("Method__5ClassFv", 0x4E80_0020);
        let target = source.clone();
        let mut cache = MatchingCache::default();
        assert_eq!(
            prepare(&mut cache, source.clone(), target.clone()).cache_use,
            CacheUse::Rebuilt
        );

        // This models a split-dependent signature adding or changing a
        // function. Even though the DOL bytes are unchanged, the graph and
        // name anchors must be rebuilt.
        assert_eq!(
            prepare(&mut cache, source.clone(), object("Other__5ClassFv", 0x4E80_0020)).cache_use,
            CacheUse::Rebuilt
        );
        assert_eq!(
            prepare(&mut cache, source, object("Other__5ClassFv", 0x6000_0000)).cache_use,
            CacheUse::Rebuilt
        );
    }

    #[test]
    fn changed_relocations_invalidate_fingerprints_and_call_edges() {
        let obj = object("Method__5ClassFv", 0x4E80_0020);
        let mut cache = MatchingCache::default();
        prepare(&mut cache, obj.clone(), obj.clone());
        let mut changed = obj.clone();
        changed
            .sections
            .get_mut(0)
            .unwrap()
            .relocations
            .insert(0x8000_1000, ObjReloc {
                kind: ObjRelocKind::PpcRel24,
                target_symbol: 0,
                addend: 0,
                module: None,
            })
            .unwrap();
        assert_eq!(prepare(&mut cache, obj, changed).cache_use, CacheUse::Rebuilt);
    }

    #[test]
    fn matching_options_invalidate_the_cache() {
        let obj = object("Method__5ClassFv", 0x4E80_0020);
        let mut cache = MatchingCache::default();
        assert_eq!(prepare(&mut cache, obj.clone(), obj.clone()).cache_use, CacheUse::Rebuilt);
        let options = MatchOptions { ignore_names: true, ..Default::default() };
        assert_eq!(
            cache
                .prepare("source-config".into(), "target-config".into(), obj.clone(), obj, &options)
                .cache_use,
            CacheUse::Rebuilt
        );
    }
}
